//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "ICMGridItemView.h"

@class SSFacade, UIImageView, UILabel;

@interface AGShareItemView : UIControl <ICMGridItemView>
{
    SSFacade *_facade;
    UIImageView *_imageView;
    UILabel *_label;
    id _data;
    _Bool _needLayout;
    long long _index;
}

- (void)setIndex:(long long)arg1;
- (long long)index;
- (void)setData:(id)arg1;
- (id)data;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

