//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol BikeSiteInforProtocol
- (void)loadBikeSitesUpdate:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
- (void)loadBikeSitesUpdateCount:(NSArray *)arg1 success:(void (^)(NSString *))arg2 failure:(void (^)(NSError *))arg3;
- (void)saveBikeSitesException:(NSArray *)arg1 success:(void (^)(_Bool *))arg2 failure:(void (^)(NSError *))arg3;
- (void)loadBikeSitesReal:(NSArray *)arg1 success:(void (^)(NSArray *))arg2 failure:(void (^)(NSError *))arg3;
- (void)loadBikeSitesAnalysis:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
- (void)loadBikeSites:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
@end

