//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSMutableDictionary, UIScrollView;

@interface CMHTableView : UIView <UIScrollViewDelegate>
{
    NSMutableDictionary *_reuseItemDictionary;
    NSMutableArray *_visibleItemArray;
    id <CMHTableViewDataSource> _dataSource;
    id <CMHTableViewDelegate> _delegate;
    NSMutableArray *_itemsMeasureArray;
    _Bool _needLayout;
    long long _itemCount;
    double _itemWidth;
    double _currX;
    UIScrollView *_contentView;
    _Bool showsHorizontalScrollIndicator;
}

@property(nonatomic) double itemWidth; // @synthesize itemWidth=_itemWidth;
@property(nonatomic) id <CMHTableViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <CMHTableViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)scrollViewDidScroll:(id)arg1;
- (void)recoverItem:(id)arg1;
- (void)recoverAllVisibleItems;
- (id)dequeueReusableItemWithIdentifier:(id)arg1;
- (void)reloadData;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic) _Bool showsHorizontalScrollIndicator; // @synthesize showsHorizontalScrollIndicator;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

