//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CMImageCacheManager : NSObject
{
    NSMutableArray *_loaderQueue;
    NSString *_cachePath;
}

- (void)onImageLoadError:(id)arg1;
- (void)onImageLoadComplete:(id)arg1;
- (id)getCornerRadiusPath:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3 clipType:(int)arg4;
- (id)getCornerRadiusPath:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3;
- (id)getCornerRadiusPath:(id)arg1 cornerRadius:(double)arg2;
- (id)getClipImagePath:(id)arg1 size:(struct CGSize)arg2 clipType:(int)arg3;
- (id)getImageLoaderWithUrl:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3 clipType:(int)arg4;
- (id)getImageLoaderWithUrl:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3;
- (id)getImageLoaderWithUrl:(id)arg1 cornerRadius:(double)arg2;
- (id)getImageLoaderWithUrl:(id)arg1 size:(struct CGSize)arg2 clipType:(int)arg3;
- (id)getImageLoaderWithUrl:(id)arg1;
- (id)getLoaderByQueue:(id)arg1;
- (id)getCacheFileName:(id)arg1;
- (_Bool)existsLocalCache:(id)arg1;
- (id)getCachePath;
- (_Bool)existsImageCache:(id)arg1 size:(struct CGSize)arg2 clipType:(int)arg3 cornerRadius:(double)arg4;
- (_Bool)existsImageCache:(id)arg1 cornerRadius:(double)arg2;
- (_Bool)existsImageCache:(id)arg1 size:(struct CGSize)arg2 clipType:(int)arg3;
- (_Bool)existsImageCache:(id)arg1;
- (id)getImage:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3 clipType:(int)arg4;
- (id)getImage:(id)arg1 cornerRadius:(double)arg2 size:(struct CGSize)arg3;
- (id)getImage:(id)arg1 cornerRadius:(double)arg2;
- (id)getImage:(id)arg1 size:(struct CGSize)arg2 clipType:(int)arg3;
- (id)getImage:(id)arg1;
- (void)dealloc;
- (id)init;

@end

