//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ICMPageContentView.h"

@class NSString;

@interface CMPageContentView : UIView <ICMPageContentView>
{
    NSString *_reuseIdentifier;
}

@property(readonly, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (id)initWithReuseIdentifier:(id)arg1 frame:(struct CGRect)arg2;
- (void)dealloc;

@end

