//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CMRefreshTableHeaderView, NSDate;

@protocol CMRefreshTableHeaderDelegate
- (_Bool)refreshTableHeaderDataSourceIsLoading:(CMRefreshTableHeaderView *)arg1;
- (void)refreshTableHeaderDidTriggerRefresh:(CMRefreshTableHeaderView *)arg1;

@optional
- (NSDate *)refreshTableHeaderDataSourceLastUpdated:(CMRefreshTableHeaderView *)arg1;
@end

