//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIButton, UIImage, UIImageView, UIPageControl, UIScrollView;

@interface EAIntroView : UIView <UIScrollViewDelegate>
{
    NSMutableArray *pageViews;
    long long LastPageIndex;
    _Bool _swipeToExit;
    _Bool _hideOffscreenPages;
    id <EAIntroDelegate> _delegate;
    UIImage *_bgImage;
    UIView *_titleView;
    double _titleViewY;
    UIPageControl *_pageControl;
    double _pageControlY;
    UIButton *_skipButton;
    long long _currentPageIndex;
    UIScrollView *_scrollView;
    UIImageView *_bgImageView;
    UIImageView *_pageBgBack;
    UIImageView *_pageBgFront;
    NSArray *_pages;
}

@property(retain, nonatomic) NSArray *pages; // @synthesize pages=_pages;
@property(retain, nonatomic) UIImageView *pageBgFront; // @synthesize pageBgFront=_pageBgFront;
@property(retain, nonatomic) UIImageView *pageBgBack; // @synthesize pageBgBack=_pageBgBack;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(nonatomic) double pageControlY; // @synthesize pageControlY=_pageControlY;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) double titleViewY; // @synthesize titleViewY=_titleViewY;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIImage *bgImage; // @synthesize bgImage=_bgImage;
@property(nonatomic) _Bool hideOffscreenPages; // @synthesize hideOffscreenPages=_hideOffscreenPages;
@property(nonatomic) _Bool swipeToExit; // @synthesize swipeToExit=_swipeToExit;
@property(nonatomic) id <EAIntroDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showInView:(id)arg1 animateDuration:(double)arg2;
- (void)hideWithFadeOutDuration:(double)arg1;
- (void)skipIntroduction;
- (void)showPanelAtPageControl;
- (void)makePanelVisibleAtIndex:(long long)arg1;
- (id)bgForPage:(int)arg1;
- (void)crossDissolveForOffset:(float)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)buildFooterView;
- (void)removeCloseViewAtXIndex:(double *)arg1;
- (void)appendCloseViewAtXIndex:(double *)arg1;
- (id)viewForPage:(id)arg1 atXIndex:(double *)arg2;
- (void)buildScrollViewWithFrame:(struct CGRect)arg1;
- (void)buildBackgroundImage;
- (void)buildUIWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andPages:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

