//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIBarButtonItem, UIView, UIViewController;

@protocol ISSContainer <NSObject>
- (void)setIPadContainerWithBarButtonItem:(UIBarButtonItem *)arg1 arrowDirect:(unsigned long long)arg2;
- (void)setIPadContainerWithView:(UIView *)arg1 rect:(struct CGRect)arg2 arrowDirect:(unsigned long long)arg3;
- (void)setIPadContainerWithView:(UIView *)arg1 arrowDirect:(unsigned long long)arg2;
- (void)setIPhoneContainerWithViewController:(UIViewController *)arg1;
- (id <ISSiPadViewController>)iPadViewController;
- (UIViewController *)iPhoneViewController;
@end

