//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ISSPage <NSObject>
- (void)setCursor:(long long)arg1;
- (long long)cursor;
- (void)setPageSize:(long long)arg1;
- (long long)pageSize;
- (void)setPageNo:(long long)arg1;
- (long long)pageNo;
@end

