//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@protocol ISSPlatform <NSObject>
- (NSArray *)registeredApps;
- (id <ISSPlatformApp>)appForKey:(NSString *)arg1;
- (_Bool)hasRegisteredWithAppInfo:(NSDictionary *)arg1;
- (void)unregisterApp:(id <ISSPlatformApp>)arg1;
- (id <ISSPlatformApp>)registerAppWithAccount:(id <ISSCAccount>)arg1 appInfo:(NSDictionary *)arg2;
- (void)setCurrentApp:(id <ISSPlatformApp>)arg1;
- (id <ISSPlatformApp>)currentApp;
- (int)type;
- (NSString *)name;
- (id)initWithType:(int)arg1;
@end

