//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol ISSShareActionSheet <NSObject>
- (void)dismiss;
- (void)showWithContainer:(id <ISSContainer>)arg1 items:(NSArray *)arg2 onItemClick:(void (^)(int))arg3 onCancel:(void (^)(void))arg4;
@end

