//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISSViewDelegate.h"

@class NSArray, UIViewController;

@protocol ISSShareViewDelegate <ISSViewDelegate>

@optional
- (void)viewOnCancelPublish:(UIViewController *)arg1;
- (id <ISSContent>)view:(UIViewController *)arg1 willPublishContent:(id <ISSContent>)arg2 shareList:(NSArray *)arg3;
- (id <ISSContent>)view:(UIViewController *)arg1 willPublishContent:(id <ISSContent>)arg2;
@end

