//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol ISSShareOptions <NSObject>
- (void)setSmsViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)smsViewDelegate;
- (void)setMailViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)mailViewDelegate;
- (void)setPicViewerViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)picViewerViewDelegate;
- (void)setFriendsViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)friendsViewDelegate;
- (void)setShareViewDelegate:(id <ISSShareViewDelegate>)arg1;
- (id <ISSShareViewDelegate>)shareViewDelegate;
- (void)setShowKeyboardOnAppear:(_Bool)arg1;
- (_Bool)showKeyboardOnAppear;
- (void)setTopicButtonHidden:(_Bool)arg1;
- (_Bool)topicButtonHidden;
- (void)setMentionButtonHidden:(_Bool)arg1;
- (_Bool)mentionButtonHidden;
- (void)setCameraButtonHidden:(_Bool)arg1;
- (_Bool)cameraButtonHidden;
- (void)setWxTimelineButtonHidden:(_Bool)arg1;
- (_Bool)wxTimelineButtonHidden;
- (void)setWxSessionButtonHidden:(_Bool)arg1;
- (_Bool)wxSessionButtonHidden;
- (void)setQqButtonHidden:(_Bool)arg1;
- (_Bool)qqButtonHidden;
- (void)setTitle:(NSString *)arg1;
- (NSString *)title;
- (void)setOneKeyShareList:(NSArray *)arg1;
- (NSArray *)oneKeyShareList;
@end

