//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@protocol ISSViewDelegate <NSObject>

@optional
- (void)view:(UIViewController *)arg1 autorotateToInterfaceOrientation:(long long)arg2 shareType:(int)arg3;
- (void)viewOnWillDismiss:(UIViewController *)arg1 shareType:(int)arg2;
- (void)viewOnWillDisplay:(UIViewController *)arg1 shareType:(int)arg2;
@end

