//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface KHFlatButton : UIButton
{
    UIColor *_buttonColor;
}

+ (id)barButtonWithTitle:(id)arg1 backgroundColor:(id)arg2;
+ (id)buttonWithFrame:(struct CGRect)arg1 withTitle:(id)arg2 backgroundColor:(id)arg3;
+ (id)buttonWithFrame:(struct CGRect)arg1 withTitle:(id)arg2 backgroundColor:(id)arg3 cornerRadius:(double)arg4;
@property(retain, nonatomic) UIColor *buttonColor; // @synthesize buttonColor=_buttonColor;
- (void).cxx_destruct;
- (void)endedPress;
- (void)wasPressed;
- (void)makeFlat:(id)arg1 withBackgroundColor:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 withTitle:(id)arg2 backgroundColor:(id)arg3 cornerRadius:(double)arg4;
- (id)initWithFrame:(struct CGRect)arg1 withBackgroundColor:(id)arg2;
- (void)awakeFromNib;

@end

