//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol LostAndFoundProtocol
- (void)saveLostAndFound:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
@end

