//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (SSToolkitAdditions)
+ (id)timeInWordsFromTimeInterval:(double)arg1 includingSeconds:(_Bool)arg2;
+ (id)dateFromISO8601String:(id)arg1;
- (id)timeInWordsIncludingSeconds:(_Bool)arg1;
- (id)timeInWords;
- (id)briefTimeInWords;
- (id)ISO8601String;
@end

