//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Common)
- (id)dataByUsingMD5;
- (id)uncompressGZipData;
- (id)gzipData;
- (id)dataUsingAES256DecryptWithKey:(id)arg1 iv:(id)arg2 options:(unsigned int)arg3;
- (id)dataUsingAES256EncryptWithKey:(id)arg1 iv:(id)arg2 options:(unsigned int)arg3;
- (id)dataUsingAES256DecryptWithKey:(id)arg1 iv:(id)arg2 encoding:(unsigned long long)arg3;
- (id)dataUsingAES256EncryptWithKey:(id)arg1 iv:(id)arg2 encoding:(unsigned long long)arg3;
- (id)dataUsingAES128DecryptWithKey:(id)arg1 iv:(id)arg2 options:(unsigned int)arg3;
- (id)dataUsingAES128EncryptWithKey:(id)arg1 iv:(id)arg2 options:(unsigned int)arg3;
- (id)dataUsingAES128DecryptWithKey:(id)arg1 iv:(id)arg2 encoding:(unsigned long long)arg3;
- (id)dataUsingAES128EncryptWithKey:(id)arg1 iv:(id)arg2 encoding:(unsigned long long)arg3;
- (id)hexString;
- (id)stringWithBase64Encode;
- (id)dataByUsingHMacSHA1WithKey:(id)arg1;
@end

