//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMQuiltView, NSIndexPath, UIView<ICMQuiltItemView>;

@protocol QuiltViewDelegate <NSObject>

@optional
- (void)quiltViewDidEndDragging:(CMQuiltView *)arg1 willDecelerate:(_Bool)arg2;
- (void)quiltViewDidScroll:(CMQuiltView *)arg1;
- (void)quiltView:(CMQuiltView *)arg1 willDisplayItemView:(UIView<ICMQuiltItemView> *)arg2 indexPath:(NSIndexPath *)arg3;
@end

