//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIWebViewDelegate.h"

@class UIWebView;

@interface SSAwardViewController : UIViewController <UIWebViewDelegate>
{
    UIWebView *_contentView;
    CDUnknownBlockType _backHandler;
}

- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)backHandler:(id)arg1;
- (void)onBack:(CDUnknownBlockType)arg1;
- (void)back;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

