//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSCLogInfo.h"

@class NSString;

@interface SSCApiLogInfo : SSCLogInfo
{
    int _shareType;
    NSString *_api;
}

+ (id)apiLogWithType:(int)arg1 api:(id)arg2 account:(id)arg3;
- (id)stringValue;
- (void)dealloc;
- (id)initWithType:(int)arg1 api:(id)arg2 account:(id)arg3;

@end

