//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SSCLocationCoordinate2D : NSObject
{
    double _latitude;
    double _longitude;
}

+ (id)locationCoordinate2DWithLatitude:(double)arg1 longitude:(double)arg2;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;

@end

