//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSFacade;

@interface SSClientShareSession : NSObject
{
    SSFacade *_facade;
    int _shareType;
    id <ISSContent> _content;
    _Bool _statusBarTips;
    CDUnknownBlockType _publishContentHandler;
    id _sessionResult;
}

- (void)start;
- (void)dealloc;
- (id)initWithShareType:(int)arg1 content:(id)arg2 statusBarTips:(_Bool)arg3 publishContentHandler:(CDUnknownBlockType)arg4 sessionResult:(CDUnknownBlockType)arg5;

@end

