//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSContent.h"
#import "NSCoding.h"

@class NSMutableDictionary, NSString, SSCLocationCoordinate2D;

@interface SSContent : NSObject <ISSContent, NSCoding>
{
    NSMutableDictionary *_metadata;
    NSMutableDictionary *_units;
    int mediaType;
    NSString *title;
    NSString *url;
    NSString *desc;
    NSString *content;
    id <ISSCAttachment> image;
    NSString *defaultContent;
    SSCLocationCoordinate2D *locationCoordinate;
    NSString *groupId;
}

- (void)setShareContentEntityDict:(id)arg1 forType:(int)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)addWeixinFavUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 thumbImage:(id)arg5 image:(id)arg6 musicFileUrl:(id)arg7 extInfo:(id)arg8 fileData:(id)arg9 emoticonData:(id)arg10;
- (void)addWeixinTimelineUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 thumbImage:(id)arg5 image:(id)arg6 musicFileUrl:(id)arg7 extInfo:(id)arg8 fileData:(id)arg9 emoticonData:(id)arg10;
- (void)addWeixinSessionUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 thumbImage:(id)arg5 image:(id)arg6 musicFileUrl:(id)arg7 extInfo:(id)arg8 fileData:(id)arg9 emoticonData:(id)arg10;
- (void)addYiXinTimelineUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 thumbImage:(id)arg5 image:(id)arg6 musicFileUrl:(id)arg7 extInfo:(id)arg8 fileData:(id)arg9;
- (void)addYiXinSessionUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 thumbImage:(id)arg5 image:(id)arg6 musicFileUrl:(id)arg7 extInfo:(id)arg8 fileData:(id)arg9;
- (void)addInstagramUnitWithTitle:(id)arg1 image:(id)arg2;
- (void)addVKontakteUnitWithMessage:(id)arg1 attachments:(id)arg2 url:(id)arg3 groupId:(id)arg4 friendsOnly:(id)arg5 locationCoordinate:(id)arg6;
- (void)addDropboxUnitWithFile:(id)arg1;
- (void)addTumblrUnitWithText:(id)arg1 title:(id)arg2 image:(id)arg3 url:(id)arg4 blogName:(id)arg5;
- (void)addFlickrUnitWithPhoto:(id)arg1 title:(id)arg2 description:(id)arg3 tags:(id)arg4 isPublic:(id)arg5 isFriend:(id)arg6 isFamily:(id)arg7 safetyLevel:(id)arg8 contentType:(id)arg9 hidden:(id)arg10;
- (void)addTencentWeiboUnitWithContent:(id)arg1 image:(id)arg2 locationCoordinate:(id)arg3;
- (void)addSinaWeiboUnitWithContent:(id)arg1 image:(id)arg2 locationCoordinate:(id)arg3;
- (void)addPinterestUnitWithImage:(id)arg1 url:(id)arg2 description:(id)arg3;
- (void)addGooglePlusUnitWithText:(id)arg1 image:(id)arg2 url:(id)arg3 deepLinkId:(id)arg4 title:(id)arg5 description:(id)arg6 thumbnail:(id)arg7;
- (void)addLinkedInUnitWithComment:(id)arg1 title:(id)arg2 description:(id)arg3 url:(id)arg4 image:(id)arg5 visibility:(id)arg6;
- (void)addKaiXinUnitWithContent:(id)arg1 image:(id)arg2;
- (void)addTwitterWithContent:(id)arg1 image:(id)arg2 locationCoordinate:(id)arg3;
- (void)addTwitterWithContent:(id)arg1 image:(id)arg2;
- (void)addFacebookWithContent:(id)arg1 image:(id)arg2;
- (void)addDouBanWithContent:(id)arg1 image:(id)arg2;
- (void)addAirPrintWithContent:(id)arg1 image:(id)arg2;
- (void)addCopyUnitWithContent:(id)arg1 image:(id)arg2;
- (void)add163WeiboUnitWithContent:(id)arg1 image:(id)arg2;
- (void)addSohuWeiboUnitWithContent:(id)arg1 image:(id)arg2;
- (void)addTencentWeiboUnitWithContent:(id)arg1 image:(id)arg2;
- (void)addSinaWeiboUnitWithContent:(id)arg1 image:(id)arg2;
- (void)addEvernoteUnitWithContent:(id)arg1 title:(id)arg2 resources:(id)arg3 notebookGuid:(id)arg4 tagsGuid:(id)arg5;
- (void)addEvernoteUnitWithContent:(id)arg1 title:(id)arg2 resources:(id)arg3;
- (void)addPocketUnitWithUrl:(id)arg1 title:(id)arg2 tags:(id)arg3 tweetId:(id)arg4;
- (void)addSohuKanUnitWithUrl:(id)arg1;
- (void)addRenRenUnitWithName:(id)arg1 description:(id)arg2 url:(id)arg3 message:(id)arg4 image:(id)arg5 caption:(id)arg6;
- (void)addMailUnitWithSubject:(id)arg1 content:(id)arg2 isHTML:(id)arg3 attachments:(id)arg4 to:(id)arg5 cc:(id)arg6 bcc:(id)arg7;
- (void)addInstapaperContentWithUrl:(id)arg1 title:(id)arg2 description:(id)arg3;
- (void)addYouDaoNoteUnitWithContent:(id)arg1 title:(id)arg2 author:(id)arg3 source:(id)arg4 attachments:(id)arg5;
- (void)addSMSUnitWithContent:(id)arg1;
- (void)addQQSpaceUnitWithTitle:(id)arg1 url:(id)arg2 site:(id)arg3 fromUrl:(id)arg4 comment:(id)arg5 summary:(id)arg6 image:(id)arg7 type:(id)arg8 playUrl:(id)arg9 nswb:(id)arg10;
- (void)addQQUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 image:(id)arg5;
- (void)addWeixinTimelineUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 image:(id)arg5 musicFileUrl:(id)arg6 extInfo:(id)arg7 fileData:(id)arg8 emoticonData:(id)arg9;
- (void)addWeixinSessionUnitWithType:(id)arg1 content:(id)arg2 title:(id)arg3 url:(id)arg4 image:(id)arg5 musicFileUrl:(id)arg6 extInfo:(id)arg7 fileData:(id)arg8 emoticonData:(id)arg9;
- (void)setShareContentEntity:(id)arg1 type:(int)arg2;
- (id)shareContentEntityWithType:(int)arg1;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId;
@property(retain, nonatomic) SSCLocationCoordinate2D *locationCoordinate; // @synthesize locationCoordinate;
@property(retain, nonatomic) id <ISSCAttachment> image; // @synthesize image;
@property(copy, nonatomic) NSString *defaultContent; // @synthesize defaultContent;
@property(copy, nonatomic) NSString *content; // @synthesize content;
@property(nonatomic) int mediaType; // @synthesize mediaType;
@property(copy, nonatomic) NSString *desc; // @synthesize desc;
@property(copy, nonatomic) NSString *url; // @synthesize url;
@property(copy, nonatomic) NSString *title; // @synthesize title;
- (void)removeMetadata:(id)arg1;
- (void)setMetadata:(id)arg1 value:(id)arg2;
- (id)getMetadata:(id)arg1;
- (void)dealloc;
- (id)init;

@end

