//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSCParameters.h"

@class CMHTTPRequestParameters;

@interface SSCParameters : NSObject <ISSCParameters>
{
    CMHTTPRequestParameters *_parameters;
}

@property(readonly, nonatomic) CMHTTPRequestParameters *parameters; // @synthesize parameters=_parameters;
- (id)dataValue:(unsigned long long)arg1 boundary:(id)arg2;
- (id)dataValue:(unsigned long long)arg1;
- (id)stringValue:(unsigned long long)arg1;
- (id)dictionaryValue;
- (long long)parameterCount;
- (id)parameterWithName:(id)arg1;
- (void)clear;
- (void)addParametersWithDictionary:(id)arg1;
- (void)addParameters:(id)arg1;
- (void)addParameter:(id)arg1 fileName:(id)arg2 data:(id)arg3 mimeType:(id)arg4 transferEncoding:(id)arg5;
- (void)addParameter:(id)arg1 filePath:(id)arg2 mimeType:(id)arg3;
- (void)addParameter:(id)arg1 value:(id)arg2;
- (void)dealloc;
- (id)initWithQuery:(id)arg1;
- (id)init;

@end

