//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSCServerInterfaceToken;

@interface SSCServerRequest : NSObject
{
    SSCServerInterfaceToken *_token;
    id _result;
    _Bool _retainSelf;
}

- (void)callApiFaiHandler:(id)arg1;
- (void)callApiSucHandler:(id)arg1;
- (void)releaseToken;
- (void)cancel;
- (void)multipartPost:(id)arg1 parameters:(id)arg2 parseData:(_Bool)arg3 userData:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)post:(id)arg1 parameters:(id)arg2 parseData:(_Bool)arg3 userData:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)get:(id)arg1 parameters:(id)arg2 parseData:(_Bool)arg3 userData:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)dealloc;
- (id)init;

@end

