//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMPageContentView.h"

#import "CMGridViewDelegate.h"

@class CMGridView, NSArray;

@interface SSFlatShareActionSheetPageContentView : CMPageContentView <CMGridViewDelegate>
{
    CMGridView *_gridView;
    NSArray *_shareList;
    id <SSFlatShareActionSheetDelegate> _delegate;
}

@property(retain, nonatomic) NSArray *shareList; // @synthesize shareList=_shareList;
@property(nonatomic) id <SSFlatShareActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void)statusBarOrientationDicChangeHandler:(id)arg1;
- (void)itemClickHandler:(id)arg1;
- (void)gridView:(id)arg1 itemRenderer:(id)arg2 itemData:(id)arg3 index:(long long)arg4;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1 frame:(struct CGRect)arg2;

@end

