//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CMHTableViewDataSource.h"
#import "CMHTableViewDelegate.h"
#import "SSFlatShareToolbarItemViewDelegate.h"

@class CMHTableView, NSArray, UILabel;

@interface SSFlatShareToolbar : UIView <CMHTableViewDataSource, CMHTableViewDelegate, SSFlatShareToolbarItemViewDelegate>
{
    CMHTableView *_platTableView;
    UILabel *_textLabel;
    int _platType;
    NSArray *_platformArray;
    id <ISSAuthOptions> _authOptions;
    NSArray *selectedPlatforms;
}

- (void)itemOnClick:(id)arg1;
- (id)tableView:(id)arg1 itemForIndexPath:(id)arg2;
- (long long)itemNumberOfTableView:(id)arg1;
- (void)updateWithType:(int)arg1 platforms:(id)arg2 authOptions:(id)arg3;
@property(readonly, nonatomic) NSArray *selectedPlatforms; // @synthesize selectedPlatforms;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

