//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SSFlatShareActionSheetDelegate.h"

@class NSArray, NSMutableArray, SSFlatShareActionSheetView;

@interface SSFlatShareActionSheetViewController : UIViewController <SSFlatShareActionSheetDelegate>
{
    SSFlatShareActionSheetView *_contentView;
    NSMutableArray *_items;
    _Bool _isShow;
    NSArray *_originItems;
    id <SSFlatShareActionSheetDelegate> _delegate;
}

@property(nonatomic) id <SSFlatShareActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutViewWithWidth:(double)arg1 height:(double)arg2;
- (void)shareActionSheetOnCancel;
- (void)shareActionSheetOnItemClick:(id)arg1;
- (void)shareActionSheetOnDismiss;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)dismissWithCompleted:(CDUnknownBlockType)arg1;
- (void)showWithItems:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

