//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SSAuthOptions, SSFacade;

@interface SSGetUserInfoSession : NSObject
{
    SSFacade *_facade;
    int _shareType;
    SSAuthOptions *_authOptions;
    NSString *_field;
    int _fieldType;
    CDUnknownBlockType _getInfoResult;
    id _sessionResult;
}

- (void)execute;
- (void)start;
- (void)dealloc;
- (id)initWithShareType:(int)arg1 field:(id)arg2 fieldType:(int)arg3 authOptions:(id)arg4 getInfoResult:(CDUnknownBlockType)arg5 sessionResult:(CDUnknownBlockType)arg6;
- (id)initWithShareType:(int)arg1 authOptions:(id)arg2 getInfoResult:(CDUnknownBlockType)arg3 sessionResult:(CDUnknownBlockType)arg4;

@end

