//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSAuthOptions, SSFacade, SSPage;

@interface SSGetMyFriendsSession : NSObject
{
    SSFacade *_facade;
    int _shareType;
    SSPage *_page;
    SSAuthOptions *_authOptions;
    CDUnknownBlockType _getFriendsHandler;
    id _sessionResult;
}

- (void)execute;
- (void)start;
- (void)dealloc;
- (id)initWithShareType:(int)arg1 page:(id)arg2 authOptions:(id)arg3 getFriendsResult:(CDUnknownBlockType)arg4 sessionResult:(CDUnknownBlockType)arg5;

@end

