//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMHTTPRequestParameters;

@interface SSHTTPParameters : NSObject
{
    CMHTTPRequestParameters *_parameters;
}

- (id)dictionaryValue;
- (id)stringUsingEncoding:(unsigned long long)arg1;
- (id)multipartDataUsingEncoding:(unsigned long long)arg1 boundary:(id)arg2;
- (id)dataUsingEncoding:(unsigned long long)arg1;
- (void)clear;
- (id)getValueForName:(id)arg1;
- (void)removeParameterWithName:(id)arg1;
- (void)addParametersWithDictionary:(id)arg1;
- (void)addPostedFileWithName:(id)arg1 fileName:(id)arg2 data:(id)arg3 contentType:(id)arg4 transferEncoding:(id)arg5;
- (void)addParameterWithName:(id)arg1 value:(id)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithQueryString:(id)arg1;
- (id)initWithURL:(id)arg1;

@end

