//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSPage.h"

@interface SSPage : NSObject <ISSPage>
{
    long long _pageNo;
    long long _pageSize;
    long long _cursor;
}

@property(nonatomic) long long cursor; // @synthesize cursor=_cursor;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
- (id)initWithCursor:(long long)arg1;
- (id)initWithPageNo:(long long)arg1 pageSize:(long long)arg2;
- (id)init;

@end

