//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ISSAuthView.h"

@class SSAuthOptions, SSFacade, UIButton;

@interface SSPopupAuthViewController : UIViewController <ISSAuthView>
{
    UIButton *_closeButton;
    _Bool _isAnimation;
    SSFacade *_facade;
    id <ISSPlatformAuthSession> _authController;
    SSAuthOptions *_options;
}

- (void)close:(CDUnknownBlockType)arg1;
- (void)statusBarOrientationDidChangeHandler:(id)arg1;
- (void)layout;
- (void)closeButtonClickHandler:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithAuthController:(id)arg1 options:(id)arg2 result:(CDUnknownBlockType)arg3;

@end

