//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UILabel;

@interface SSPowerByButton : UIControl
{
    UILabel *_poweredByLabel;
    UILabel *_logoLabel;
}

- (void)layoutSubviews;
- (void)sizeToFit;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

