//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSShareActionSheetItem.h"

@class NSString, UIImage;

@interface SSShareActionSheetCustomItem : NSObject <ISSShareActionSheetItem>
{
    NSString *_title;
    UIImage *_icon;
    CDUnknownBlockType _clickHandler;
}

@property(readonly, nonatomic) CDUnknownBlockType clickHandler; // @synthesize clickHandler=_clickHandler;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 clickHandler:(CDUnknownBlockType)arg3;

@end

