//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AGSharePageContentViewDelegate.h"
#import "CMPageViewDataSource.h"
#import "CMPageViewDelegate.h"

@class CMPageView, NSMutableArray;

@interface SSShareListViewController : UIViewController <CMPageViewDataSource, CMPageViewDelegate, AGSharePageContentViewDelegate>
{
    CMPageView *_pageView;
    NSMutableArray *_shareList;
    id _clickHandler;
    double _maxRow;
}

@property(readonly, nonatomic) double maxRow; // @synthesize maxRow=_maxRow;
- (void)pageContentView:(id)arg1 onItemClick:(id)arg2;
- (id)pageView:(id)arg1 pageForIndexPath:(id)arg2;
- (long long)pageViewNumberOfPage:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithShareList:(id)arg1 clickHandler:(CDUnknownBlockType)arg2;

@end

