//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface SSSinaWeiboUserManager : NSObject
{
    NSMutableArray *_users;
    id <ISSPlatformUser> _defaultUser;
    id <ISSPlatformApp> _app;
}

@property(readonly, nonatomic) NSArray *users; // @synthesize users=_users;
- (id)loadUser:(id)arg1;
- (void)clearUser:(id)arg1;
- (_Bool)saveUser:(id)arg1;
- (id)getUser:(id)arg1;
- (_Bool)unregisterUser:(id)arg1;
- (_Bool)registerUser:(id)arg1;
@property(retain, nonatomic) id <ISSPlatformUser> defaultUser; // @synthesize defaultUser=_defaultUser;
- (void)dealloc;
- (id)initWithApp:(id)arg1;

@end

