//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, SSSinaWeiboStatusInfoReader;

@interface SSSinaWeiboFavoriteReader : NSObject
{
    NSDictionary *_sourceData;
    SSSinaWeiboStatusInfoReader *_status;
    NSMutableArray *_tags;
    NSString *favoritedTime;
    SSSinaWeiboStatusInfoReader *status;
    NSArray *tags;
}

+ (id)readerWithSourceData:(id)arg1;
@property(readonly, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(readonly, nonatomic) NSArray *tags; // @synthesize tags;
@property(readonly, nonatomic) SSSinaWeiboStatusInfoReader *status; // @synthesize status;
@property(readonly, nonatomic) NSString *favoritedTime; // @synthesize favoritedTime;
- (void)dealloc;
- (id)initWithSourceData:(id)arg1;

@end

