//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSPlatformShareContentEntity.h"
#import "NSCoding.h"

@class NSMutableDictionary, NSString, SSCLocationCoordinate2D;

@interface SSSinaWeiboShareContentEntity : NSObject <ISSPlatformShareContentEntity, NSCoding>
{
    NSMutableDictionary *_dict;
    NSString *content;
    id <ISSCAttachment> image;
    SSCLocationCoordinate2D *locationCoordinate;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setField:(id)arg1 forName:(id)arg2;
- (id)fieldForName:(id)arg1;
- (void)parseWithContent:(id)arg1;
@property(retain, nonatomic) SSCLocationCoordinate2D *locationCoordinate; // @synthesize locationCoordinate;
@property(retain, nonatomic) id <ISSCAttachment> image; // @synthesize image;
@property(copy, nonatomic) NSString *content; // @synthesize content;
- (void)dealloc;
- (id)init;

@end

