//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSPlatformAuthSession.h"

@class SSSinaWeiboApp, SSSinaWeiboAuthView;

@interface SSSinaWeiboAuthSession : NSObject <ISSPlatformAuthSession>
{
    _Bool _isSSOLogin;
    _Bool _hasHandleOpenUrl;
    _Bool _allowCallback;
    CDUnknownBlockType _result;
    SSSinaWeiboApp *_app;
    SSSinaWeiboAuthView *_authView;
    id <SSSinaWeiboAuthSessionDelegate> _delegate;
}

@property(readonly, nonatomic) _Bool isSSOLogin; // @synthesize isSSOLogin=_isSSOLogin;
@property(nonatomic) id <SSSinaWeiboAuthSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (id)view;
- (void)cancel;
- (void)startWithAllowCallback:(_Bool)arg1 ssoLogin:(_Bool)arg2 scopes:(id)arg3 result:(CDUnknownBlockType)arg4;
- (int)type;
- (_Bool)checkUrlScheme:(id *)arg1;
- (void)becomeActiveHandler:(id)arg1;
- (void)callbackWithAuthInfo:(id)arg1;
- (void)writeAuthInfoLog;
- (void)handleSSOLoginURL:(id)arg1;
- (void)dealloc;
- (id)initWithApp:(id)arg1;

@end

