//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMPageContentView.h"

#import "CMGridViewDelegate.h"

@class CMGridView, NSArray;

@interface SSSNSPageContentView : CMPageContentView <CMGridViewDelegate>
{
    CMGridView *_gridView;
    NSArray *_listData;
    id <SSSNSPageContentViewDelegate> _delegate;
    _Bool _needLayout;
}

@property(nonatomic) id <SSSNSPageContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *listData; // @synthesize listData=_listData;
- (void)itemClickHandler:(id)arg1;
- (void)gridView:(id)arg1 itemRenderer:(id)arg2 itemData:(id)arg3 index:(long long)arg4;
- (void)layoutSubviews;
- (void)refreshData;
- (void)dealloc;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithReuseIdentifier:(id)arg1 frame:(struct CGRect)arg2;

@end

