//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, SSTencentWeiboMusicReader, SSTencentWeiboVideoReader;

@interface SSTencentWeiboTweetReader : NSObject
{
    NSDictionary *_sourceData;
    SSTencentWeiboMusicReader *_music;
    SSTencentWeiboVideoReader *_video;
    _Bool isSelf;
    NSString *Id;
    double timestamp;
    NSString *cityCode;
    NSString *countryCode;
    long long emotiontype;
    NSString *emotionurl;
    NSString *from;
    NSString *fromurl;
    NSString *geo;
    NSArray *image;
    NSString *latitude;
    NSString *location;
    NSString *longitude;
    SSTencentWeiboMusicReader *music;
    NSString *origtext;
    NSString *provinceCode;
    long long status;
    NSString *text;
    long long type;
    SSTencentWeiboVideoReader *video;
}

+ (id)readerWithSourceData:(id)arg1;
@property(readonly, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(readonly, nonatomic) SSTencentWeiboVideoReader *video; // @synthesize video;
@property(readonly, nonatomic) long long type; // @synthesize type;
@property(readonly, nonatomic) NSString *text; // @synthesize text;
@property(readonly, nonatomic) long long status; // @synthesize status;
@property(readonly, nonatomic) _Bool isSelf; // @synthesize isSelf;
@property(readonly, nonatomic) NSString *provinceCode; // @synthesize provinceCode;
@property(readonly, nonatomic) NSString *origtext; // @synthesize origtext;
@property(readonly, nonatomic) SSTencentWeiboMusicReader *music; // @synthesize music;
@property(readonly, nonatomic) NSString *longitude; // @synthesize longitude;
@property(readonly, nonatomic) NSString *location; // @synthesize location;
@property(readonly, nonatomic) NSString *latitude; // @synthesize latitude;
@property(readonly, nonatomic) NSArray *image; // @synthesize image;
@property(readonly, nonatomic) NSString *geo; // @synthesize geo;
@property(readonly, nonatomic) NSString *fromurl; // @synthesize fromurl;
@property(readonly, nonatomic) NSString *from; // @synthesize from;
@property(readonly, nonatomic) NSString *emotionurl; // @synthesize emotionurl;
@property(readonly, nonatomic) long long emotiontype; // @synthesize emotiontype;
@property(readonly, nonatomic) NSString *countryCode; // @synthesize countryCode;
@property(readonly, nonatomic) NSString *cityCode; // @synthesize cityCode;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp;
@property(readonly, nonatomic) NSString *Id; // @synthesize Id;
- (void)dealloc;
- (id)initWithSourceData:(id)arg1;

@end

