//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableArray, NSString;

@interface SSTencentWeiboUserReader : NSObject
{
    NSDictionary *_sourceData;
    NSMutableArray *_comp;
    NSMutableArray *_edu;
    NSMutableArray *_tag;
    NSMutableArray *_tweetinfo;
    _Bool isent;
    _Bool ismyblack;
    _Bool ismyfans;
    _Bool ismyidol;
    _Bool isvip;
    long long birthDay;
    long long birthMonth;
    long long birthYear;
    NSString *cityCode;
    NSArray *comp;
    NSString *countryCode;
    NSArray *edu;
    NSString *email;
    long long exp;
    long long fansnum;
    long long favnum;
    NSString *head;
    NSString *homecityCode;
    NSString *homecountryCode;
    NSString *homepage;
    NSString *homeprovinceCode;
    NSString *hometownCode;
    long long idolnum;
    long long industryCode;
    NSString *introduction;
    long long isrealname;
    long long level;
    NSString *location;
    long long mutualFansNum;
    NSString *name;
    NSString *nick;
    NSString *openid;
    NSString *provinceCode;
    double regtime;
    long long sendPrivateFlag;
    long long sex;
    NSArray *tag;
    NSArray *tweetinfo;
    long long tweetnum;
    NSString *verifyinfo;
}

+ (id)readerWithSourceData:(id)arg1;
@property(readonly, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(readonly, nonatomic) NSString *verifyinfo; // @synthesize verifyinfo;
@property(readonly, nonatomic) long long tweetnum; // @synthesize tweetnum;
@property(readonly, nonatomic) NSArray *tweetinfo; // @synthesize tweetinfo;
@property(readonly, nonatomic) NSArray *tag; // @synthesize tag;
@property(readonly, nonatomic) long long sex; // @synthesize sex;
@property(readonly, nonatomic) long long sendPrivateFlag; // @synthesize sendPrivateFlag;
@property(readonly, nonatomic) double regtime; // @synthesize regtime;
@property(readonly, nonatomic) NSString *provinceCode; // @synthesize provinceCode;
@property(readonly, nonatomic) NSString *openid; // @synthesize openid;
@property(readonly, nonatomic) NSString *nick; // @synthesize nick;
@property(readonly, nonatomic) NSString *name; // @synthesize name;
@property(readonly, nonatomic) long long mutualFansNum; // @synthesize mutualFansNum;
@property(readonly, nonatomic) NSString *location; // @synthesize location;
@property(readonly, nonatomic) long long level; // @synthesize level;
@property(readonly, nonatomic) _Bool isvip; // @synthesize isvip;
@property(readonly, nonatomic) long long isrealname; // @synthesize isrealname;
@property(readonly, nonatomic) _Bool ismyidol; // @synthesize ismyidol;
@property(readonly, nonatomic) _Bool ismyfans; // @synthesize ismyfans;
@property(readonly, nonatomic) _Bool ismyblack; // @synthesize ismyblack;
@property(readonly, nonatomic) _Bool isent; // @synthesize isent;
@property(readonly, nonatomic) NSString *introduction; // @synthesize introduction;
@property(readonly, nonatomic) long long industryCode; // @synthesize industryCode;
@property(readonly, nonatomic) long long idolnum; // @synthesize idolnum;
@property(readonly, nonatomic) NSString *hometownCode; // @synthesize hometownCode;
@property(readonly, nonatomic) NSString *homeprovinceCode; // @synthesize homeprovinceCode;
@property(readonly, nonatomic) NSString *homepage; // @synthesize homepage;
@property(readonly, nonatomic) NSString *homecountryCode; // @synthesize homecountryCode;
@property(readonly, nonatomic) NSString *homecityCode; // @synthesize homecityCode;
@property(readonly, nonatomic) NSString *head; // @synthesize head;
@property(readonly, nonatomic) long long favnum; // @synthesize favnum;
@property(readonly, nonatomic) long long fansnum; // @synthesize fansnum;
@property(readonly, nonatomic) long long exp; // @synthesize exp;
@property(readonly, nonatomic) NSString *email; // @synthesize email;
@property(readonly, nonatomic) NSArray *edu; // @synthesize edu;
@property(readonly, nonatomic) NSString *countryCode; // @synthesize countryCode;
@property(readonly, nonatomic) NSArray *comp; // @synthesize comp;
@property(readonly, nonatomic) NSString *cityCode; // @synthesize cityCode;
@property(readonly, nonatomic) long long birthYear; // @synthesize birthYear;
@property(readonly, nonatomic) long long birthMonth; // @synthesize birthMonth;
@property(readonly, nonatomic) long long birthDay; // @synthesize birthDay;
- (void)dealloc;
- (id)initWithSourceData:(id)arg1;

@end

