//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSPlatform.h"

@class SSTencentWeiboAppManager;

@interface TencentWeiboConnection : NSObject <ISSPlatform>
{
    int _type;
    SSTencentWeiboAppManager *_appManager;
}

- (id)registeredApps;
- (id)appForKey:(id)arg1;
- (void)unregisterApp:(id)arg1;
- (_Bool)hasRegisteredWithAppInfo:(id)arg1;
- (id)registerAppWithAccount:(id)arg1 appInfo:(id)arg2;
- (void)setCurrentApp:(id)arg1;
- (id)currentApp;
- (int)type;
- (id)name;
- (id)initWithType:(int)arg1;
- (id)appInfoWithAppKey:(id)arg1 appSecret:(id)arg2 redirectUri:(id)arg3;
- (void)dealloc;
- (id)init;

@end

