//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UILabel, UIScrollView, UITextField;

@interface THXLoginViewController : UIViewController <UITextFieldDelegate>
{
    UILabel *_userNameLable;
    UILabel *_pwdLable;
    UITextField *_userNameText;
    UILabel *_pwdText;
    UIButton *_jzPwd;
    UIButton *_zddl;
    UIButton *_loginBtn;
    UIScrollView *_loginScrollView;
    UITextField *_pwdTxt;
    UILabel *_tiplab;
    UIButton *_wangjimima;
    UIButton *_zhuce;
}

@property(nonatomic) __weak UIButton *zhuce; // @synthesize zhuce=_zhuce;
@property(nonatomic) __weak UIButton *wangjimima; // @synthesize wangjimima=_wangjimima;
@property(nonatomic) __weak UILabel *tiplab; // @synthesize tiplab=_tiplab;
@property(nonatomic) __weak UITextField *pwdTxt; // @synthesize pwdTxt=_pwdTxt;
@property(nonatomic) __weak UIScrollView *loginScrollView; // @synthesize loginScrollView=_loginScrollView;
@property(nonatomic) __weak UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(nonatomic) __weak UIButton *zddl; // @synthesize zddl=_zddl;
@property(nonatomic) __weak UIButton *jzPwd; // @synthesize jzPwd=_jzPwd;
@property(nonatomic) __weak UILabel *pwdText; // @synthesize pwdText=_pwdText;
@property(nonatomic) __weak UITextField *userNameText; // @synthesize userNameText=_userNameText;
@property(nonatomic) __weak UILabel *pwdLable; // @synthesize pwdLable=_pwdLable;
@property(nonatomic) __weak UILabel *userNameLable; // @synthesize userNameLable=_userNameLable;
- (void).cxx_destruct;
- (void)zhuce:(id)arg1;
- (void)loadMyFocusBites;
- (void)wangjiMM:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)login;
- (void)login:(id)arg1;
- (void)showTiplab;
- (_Bool)isNet;
- (void)zdbuttonPress:(id)arg1;
- (void)jzbuttonPress:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

