//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"
#import "UIPopoverListViewDataSource.h"
#import "UIPopoverListViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSDate, NSString, UIAlertView, UIButton, UIDatePicker, UILabel, UIScrollView, UITextField, UITextView;

@interface THXLostViewController : UIViewController <UITextViewDelegate, UITextFieldDelegate, UIPopoverListViewDataSource, UIPopoverListViewDelegate, UIAlertViewDelegate>
{
    UIButton *_TypeButton;
    UITextField *_ContactText;
    UIScrollView *_scrollView;
    UILabel *_OutLabel;
    UITextView *_InfoTextV;
    UIButton *_TimeButton;
    UIAlertView *_alert;
    UIButton *_subbtn;
    UILabel *_tiplab;
    UILabel *_gonggaolab;
    int *_isEmpty;
    NSDate *_date;
    UIDatePicker *_datePicker;
}

@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain) NSDate *date; // @synthesize date=_date;
@property int *isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) __weak UILabel *gonggaolab; // @synthesize gonggaolab=_gonggaolab;
@property(nonatomic) __weak UILabel *tiplab; // @synthesize tiplab=_tiplab;
@property(nonatomic) __weak UIButton *subbtn; // @synthesize subbtn=_subbtn;
@property(retain, nonatomic) UIAlertView *alert; // @synthesize alert=_alert;
@property(nonatomic) __weak UIButton *TimeButton; // @synthesize TimeButton=_TimeButton;
@property(nonatomic) __weak UITextView *InfoTextV; // @synthesize InfoTextV=_InfoTextV;
@property(nonatomic) __weak UILabel *OutLabel; // @synthesize OutLabel=_OutLabel;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UITextField *ContactText; // @synthesize ContactText=_ContactText;
@property(nonatomic) __weak UIButton *TypeButton; // @synthesize TypeButton=_TypeButton;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)keyboardHide:(id)arg1;
- (void)loadShiDate;
- (void)datePickerValueChanged:(id)arg1;
- (void)righttMenuSelected:(id)arg1;
- (void)SelTime:(id)arg1;
- (double)popoverListView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)popoverListView:(id)arg1 didSelectIndexPath:(id)arg2;
- (long long)popoverListView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)popoverListView:(id)arg1 cellForIndexPath:(id)arg2;
- (void)ChaType:(id)arg1;
- (void)showTiplab;
- (void)SubButton:(id)arg1;
- (_Bool)isNet;
- (void)didReceiveMemoryWarning;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)onClick:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

