//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIProgressView;

@interface THXMyFocusTableViewCell : UITableViewCell
{
    UILabel *_siteName;
    UILabel *_kejie;
    UIProgressView *_jindu;
    UILabel *_kehuan;
}

+ (id)viewWithXib;
@property(nonatomic) __weak UILabel *kehuan; // @synthesize kehuan=_kehuan;
@property(nonatomic) __weak UIProgressView *jindu; // @synthesize jindu=_jindu;
@property(nonatomic) __weak UILabel *kejie; // @synthesize kejie=_kejie;
@property(nonatomic) __weak UILabel *siteName; // @synthesize siteName=_siteName;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

