//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel;

@interface THXPathMaptTableViewCell : UITableViewCell
{
    UILabel *_tip;
    UIButton *_num;
}

+ (id)viewWithXib;
@property(nonatomic) __weak UIButton *num; // @synthesize num=_num;
@property(nonatomic) __weak UILabel *tip; // @synthesize tip=_tip;
- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

