//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface THXPersonalCenterViewController : UIViewController <UITextFieldDelegate>
{
    NSString *sextag;
    UIView *_beijing;
    UIButton *_saveBtn;
    UITextField *_shoujiText;
    UILabel *_shoujilabel;
    UITextField *_nichenText;
    UILabel *_nichenLable;
    UIImageView *_nanImage;
    UIImageView *_nvImage;
    UITextField *_nianlinText;
    UILabel *_nianlinLable;
    UILabel *_tiplab;
}

@property(nonatomic) __weak UILabel *tiplab; // @synthesize tiplab=_tiplab;
@property(nonatomic) __weak UILabel *nianlinLable; // @synthesize nianlinLable=_nianlinLable;
@property(nonatomic) __weak UITextField *nianlinText; // @synthesize nianlinText=_nianlinText;
@property(nonatomic) __weak UIImageView *nvImage; // @synthesize nvImage=_nvImage;
@property(nonatomic) __weak UIImageView *nanImage; // @synthesize nanImage=_nanImage;
@property(nonatomic) __weak UILabel *nichenLable; // @synthesize nichenLable=_nichenLable;
@property(nonatomic) __weak UITextField *nichenText; // @synthesize nichenText=_nichenText;
@property(nonatomic) __weak UILabel *shoujilabel; // @synthesize shoujilabel=_shoujilabel;
@property(nonatomic) __weak UITextField *shoujiText; // @synthesize shoujiText=_shoujiText;
@property(nonatomic) __weak UIButton *saveBtn; // @synthesize saveBtn=_saveBtn;
@property(nonatomic) __weak UIView *beijing; // @synthesize beijing=_beijing;
- (void).cxx_destruct;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)save:(id)arg1;
- (void)showTiplab;
- (_Bool)isNet;
- (void)didReceiveMemoryWarning;
- (void)imageClick:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

