//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, THXLeftViewController, UIBarButtonItem, UIPanGestureRecognizer, UITapGestureRecognizer, UIViewController;

@interface THXSearchSlideNavigationController : UINavigationController <UINavigationControllerDelegate, UIImagePickerControllerDelegate>
{
    _Bool enableSwipeGesture;
    _Bool _avoidSwitchingToSameClassViewController;
    UIViewController *righMenu;
    THXLeftViewController *leftMenu;
    UITapGestureRecognizer *tapRecognizer;
    UIPanGestureRecognizer *panRecognizer;
    UIBarButtonItem *leftbarButtonItem;
    UIBarButtonItem *rightBarButtonItem;
    NSString *_kai;
    struct CGPoint draggingPoint;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *kai; // @synthesize kai=_kai;
@property(nonatomic) _Bool avoidSwitchingToSameClassViewController; // @synthesize avoidSwitchingToSameClassViewController=_avoidSwitchingToSameClassViewController;
@property(nonatomic) _Bool enableSwipeGesture; // @synthesize enableSwipeGesture;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem;
@property(retain, nonatomic) UIBarButtonItem *leftbarButtonItem; // @synthesize leftbarButtonItem;
@property(nonatomic) struct CGPoint draggingPoint; // @synthesize draggingPoint;
@property(retain, nonatomic) UIPanGestureRecognizer *panRecognizer; // @synthesize panRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *tapRecognizer; // @synthesize tapRecognizer;
@property(retain, nonatomic) THXLeftViewController *leftMenu; // @synthesize leftMenu;
@property(retain, nonatomic) UIViewController *righMenu; // @synthesize righMenu;
- (void).cxx_destruct;
- (void)imagePickerController:(id)arg1 didFinishPickingImage:(id)arg2 editingInfo:(id)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)tanChuxc;
- (void)tanChuCm;
- (long long)maxXForDragging;
- (long long)minXForDragging;
- (void)panDetected:(id)arg1;
- (void)tapDetected:(id)arg1;
- (void)righttMenuSelected:(id)arg1;
- (void)leftMenuSelected:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)closeMenuWithCompletion:(CDUnknownBlockType)arg1;
- (void)closeMenuWithDuration:(float)arg1 andCompletion:(CDUnknownBlockType)arg2;
- (void)openMenu:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)openMenu:(int)arg1 withDuration:(float)arg2 andCompletion:(CDUnknownBlockType)arg3;
- (_Bool)shouldDisplayMenu:(int)arg1 forViewController:(id)arg2;
- (_Bool)isMenuOpen;
- (id)barButtonItemForMenu:(int)arg1;
- (id)popToViewController:(id)arg1 animated:(_Bool)arg2;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)popToRootViewControllerAnimated:(_Bool)arg1;
- (void)switchToViewController:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)setup;
- (id)init;
- (id)initWithRootViewController:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

