//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (ColorUtils)
+ (id)colorWithRGBAValue:(unsigned long long)arg1;
+ (id)colorWithRGBValue:(long long)arg1;
+ (id)colorWithString:(id)arg1;
+ (id)standardColors;
- (_Bool)isEquivalentToColor:(id)arg1;
- (_Bool)isEquivalent:(id)arg1;
- (_Bool)isMonochromeOrRGB;
@property(readonly, nonatomic) double alpha;
@property(readonly, nonatomic) double blue;
@property(readonly, nonatomic) double green;
@property(readonly, nonatomic) double red;
- (id)stringValue;
- (unsigned int)RGBAValue;
- (int)RGBValue;
- (id)initWithRGBAValue:(unsigned long long)arg1;
- (id)initWithRGBValue:(long long)arg1;
- (id)initWithString:(id)arg1;
- (void)getColorComponents:(double *)arg1;
@end

