//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@class UIView;

@interface UITableView (NXEmptyView)
+ (void)load;
- (void)nxEV_layoutSubviews;
- (void)nxEV_reloadData;
- (void)nxEV_updateEmptyView;
@property(nonatomic) _Bool nxEV_hideSeparatorLinesWheyShowingEmptyView; // @dynamic nxEV_hideSeparatorLinesWheyShowingEmptyView;
@property(retain, nonatomic) UIView *nxEV_emptyView; // @dynamic nxEV_emptyView;
- (_Bool)nxEV_hasRowsToDisplay;
@end

