//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface WYPopoverTheme : NSObject
{
    UIColor *tintColor;
    UIColor *fillTopColor;
    UIColor *fillBottomColor;
    UIColor *glossShadowColor;
    double glossShadowBlurRadius;
    double borderWidth;
    double arrowBase;
    double arrowHeight;
    UIColor *outerShadowColor;
    UIColor *outerStrokeColor;
    double outerShadowBlurRadius;
    double outerCornerRadius;
    double minOuterCornerRadius;
    UIColor *innerShadowColor;
    UIColor *innerStrokeColor;
    double innerShadowBlurRadius;
    double innerCornerRadius;
    UIColor *overlayColor;
    struct CGSize glossShadowOffset;
    struct CGSize outerShadowOffset;
    struct CGSize innerShadowOffset;
    struct UIEdgeInsets viewContentInsets;
}

+ (id)themeForIOS7;
+ (id)themeForIOS6;
+ (id)theme;
@property(retain, nonatomic) UIColor *overlayColor; // @synthesize overlayColor;
@property(nonatomic) struct UIEdgeInsets viewContentInsets; // @synthesize viewContentInsets;
@property(nonatomic) double innerCornerRadius; // @synthesize innerCornerRadius;
@property(nonatomic) struct CGSize innerShadowOffset; // @synthesize innerShadowOffset;
@property(nonatomic) double innerShadowBlurRadius; // @synthesize innerShadowBlurRadius;
@property(retain, nonatomic) UIColor *innerStrokeColor; // @synthesize innerStrokeColor;
@property(retain, nonatomic) UIColor *innerShadowColor; // @synthesize innerShadowColor;
@property(nonatomic) double minOuterCornerRadius; // @synthesize minOuterCornerRadius;
@property(nonatomic) double outerCornerRadius; // @synthesize outerCornerRadius;
@property(nonatomic) struct CGSize outerShadowOffset; // @synthesize outerShadowOffset;
@property(nonatomic) double outerShadowBlurRadius; // @synthesize outerShadowBlurRadius;
@property(retain, nonatomic) UIColor *outerStrokeColor; // @synthesize outerStrokeColor;
@property(retain, nonatomic) UIColor *outerShadowColor; // @synthesize outerShadowColor;
@property(nonatomic) double arrowHeight; // @synthesize arrowHeight;
@property(nonatomic) double arrowBase; // @synthesize arrowBase;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) double glossShadowBlurRadius; // @synthesize glossShadowBlurRadius;
@property(nonatomic) struct CGSize glossShadowOffset; // @synthesize glossShadowOffset;
@property(retain, nonatomic) UIColor *glossShadowColor; // @synthesize glossShadowColor;
@property(retain, nonatomic) UIColor *fillBottomColor; // @synthesize fillBottomColor;
@property(retain, nonatomic) UIColor *fillTopColor; // @synthesize fillTopColor;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor;
- (void).cxx_destruct;
- (id)observableKeypaths;

@end

