//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface WYPopoverBackgroundInnerView : UIView
{
    _Bool wantsDefaultContentAppearance;
    UIColor *innerStrokeColor;
    UIColor *gradientTopColor;
    UIColor *gradientBottomColor;
    double gradientHeight;
    double gradientTopPosition;
    UIColor *innerShadowColor;
    double innerShadowBlurRadius;
    double innerCornerRadius;
    double navigationBarHeight;
    double borderWidth;
    struct CGSize innerShadowOffset;
}

@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) _Bool wantsDefaultContentAppearance; // @synthesize wantsDefaultContentAppearance;
@property(nonatomic) double navigationBarHeight; // @synthesize navigationBarHeight;
@property(nonatomic) double innerCornerRadius; // @synthesize innerCornerRadius;
@property(nonatomic) double innerShadowBlurRadius; // @synthesize innerShadowBlurRadius;
@property(nonatomic) struct CGSize innerShadowOffset; // @synthesize innerShadowOffset;
@property(retain, nonatomic) UIColor *innerShadowColor; // @synthesize innerShadowColor;
@property(nonatomic) double gradientTopPosition; // @synthesize gradientTopPosition;
@property(nonatomic) double gradientHeight; // @synthesize gradientHeight;
@property(retain, nonatomic) UIColor *gradientBottomColor; // @synthesize gradientBottomColor;
@property(retain, nonatomic) UIColor *gradientTopColor; // @synthesize gradientTopColor;
@property(retain, nonatomic) UIColor *innerStrokeColor; // @synthesize innerStrokeColor;
- (void).cxx_destruct;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

