//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XHAutoSizeScrollViewController.h"

#import "UITextViewDelegate.h"

@class NSString, UIButton, UITextView;

@interface XHFeedbackViewController : XHAutoSizeScrollViewController <UITextViewDelegate>
{
    UITextView *_textviewFeedback;
    UITextView *_textviewContactInfo;
    UIButton *_btnSubmit;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) __weak UIButton *btnSubmit; // @synthesize btnSubmit=_btnSubmit;
@property(nonatomic) __weak UITextView *textviewContactInfo; // @synthesize textviewContactInfo=_textviewContactInfo;
@property(nonatomic) __weak UITextView *textviewFeedback; // @synthesize textviewFeedback=_textviewFeedback;
- (void).cxx_destruct;
- (void)textViewDidChange:(id)arg1;
- (void)endProgress:(_Bool)arg1 error:(id)arg2;
- (void)showProgress;
- (void)setSubmitBlock:(CDUnknownBlockType)arg1;
- (void)submit:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

