//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XHInstructionTools : NSObject
{
}

+ (void)reset;
+ (void)target:(id)arg1 version:(unsigned long long)arg2 openInstruction:(SEL)arg3 openMainView:(SEL)arg4;
+ (void)target:(id)arg1 version:(unsigned long long)arg2 openInstruction:(SEL)arg3;

@end

