//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XHAutoSizeScrollViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString, UIButton, UITextField;

@interface XHLoginViewController : XHAutoSizeScrollViewController <UIGestureRecognizerDelegate>
{
    UITextField *_textFieldUsername;
    UITextField *_textFieldPassword;
    UIButton *_btnRememberPassword;
    UIButton *_btnAutoLogin;
    UIButton *_btnLogin;
    CDUnknownBlockType _block;
    UITextField *_activeTextField;
}

+ (void)autoLogin:(CDUnknownBlockType)arg1;
+ (_Bool)isAutoLogin;
@property(nonatomic) __weak UITextField *activeTextField; // @synthesize activeTextField=_activeTextField;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) __weak UIButton *btnLogin; // @synthesize btnLogin=_btnLogin;
@property(nonatomic) __weak UIButton *btnAutoLogin; // @synthesize btnAutoLogin=_btnAutoLogin;
@property(nonatomic) __weak UIButton *btnRememberPassword; // @synthesize btnRememberPassword=_btnRememberPassword;
@property(nonatomic) __weak UITextField *textFieldPassword; // @synthesize textFieldPassword=_textFieldPassword;
@property(nonatomic) __weak UITextField *textFieldUsername; // @synthesize textFieldUsername=_textFieldUsername;
- (void).cxx_destruct;
- (void)clickRememberPassword:(id)arg1;
- (void)clickAutoLogin:(id)arg1;
- (void)clickLogin:(id)arg1;
- (void)endLoginProgress:(_Bool)arg1 error:(id)arg2;
- (void)showLoginProgress;
- (void)setLoginBlock:(CDUnknownBlockType)arg1;
- (void)showCheckFail:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

