//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AFHTTPRequestOperationManager.h"

@class NSURL;

@interface AFJSONRPCClient : AFHTTPRequestOperationManager
{
    NSURL *_endpointURL;
}

+ (id)clientWithEndpointURL:(id)arg1;
@property(retain, nonatomic) NSURL *endpointURL; // @synthesize endpointURL=_endpointURL;
- (void).cxx_destruct;
- (id)proxyWithProtocol:(id)arg1 moduleName:(id)arg2;
- (id)proxyWithProtocol:(id)arg1;
- (id)HTTPRequestOperationWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)requestWithMethod:(id)arg1 parameters:(id)arg2 requestId:(id)arg3;
- (void)invokeMethod:(id)arg1 withParameters:(id)arg2 requestId:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)invokeMethod:(id)arg1 withParameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)invokeMethod:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (id)initWithEndpointURL:(id)arg1;

@end

