//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol BikeSiteUserProtocol
- (void)uploadPortrait:(NSArray *)arg1 success:(void (^)(_Bool *))arg2 failure:(void (^)(NSError *))arg3;
- (void)downloadPortrait:(NSArray *)arg1 success:(void (^)(NSString *))arg2 failure:(void (^)(NSError *))arg3;
- (void)saveUserFocus:(NSArray *)arg1 success:(void (^)(_Bool *))arg2 failure:(void (^)(NSError *))arg3;
- (void)delUserFocus:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
- (void)loadUserFocus:(NSArray *)arg1 success:(void (^)(NSArray *))arg2 failure:(void (^)(NSError *))arg3;
- (void)saveUserInfor:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
- (void)saveOpinion:(NSArray *)arg1 success:(void (^)(NSDictionary *))arg2 failure:(void (^)(NSError *))arg3;
@end

