//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface CMCacheManager : NSObject
{
    NSMutableArray *_loaderQueue;
    NSString *_cachePath;
}

- (void)onImageLoadError:(id)arg1;
- (void)onImageLoadComplete:(id)arg1;
- (id)getLoaderByQueue:(id)arg1;
- (_Bool)existsLocalCache:(id)arg1;
- (id)getCacheFileName:(id)arg1;
- (id)getCachePath;
- (id)load:(id)arg1;
- (void)dealloc;
- (id)init;

@end

