//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CMDebugLog : NSObject
{
}

+ (id)getLogContent:(id)arg1;
+ (id)currentDateLogPath;
+ (id)logPath;
+ (void)writeContentWithDictionary:(id)arg1;
+ (void)writeError:(id)arg1;
+ (void)writeWarning:(id)arg1;
+ (void)writeInfo:(id)arg1;

@end

