//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICMErrorInfo.h"

@class NSString;

@interface CMErrorInfo : NSObject <ICMErrorInfo>
{
    long long _errorCode;
    NSString *_errorDescription;
    int _errorLevel;
}

@property(nonatomic) int errorLevel; // @synthesize errorLevel=_errorLevel;
@property(copy, nonatomic) NSString *errorDescription; // @synthesize errorDescription=_errorDescription;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
- (void)dealloc;

@end

