//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "ICMHTableViewItem.h"

@class NSIndexPath, NSString;

@interface CMHTableViewItem : UIView <ICMHTableViewItem>
{
    NSString *_reuseIdentifier;
    NSIndexPath *_indexPath;
}

@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(readonly, nonatomic) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)dealloc;

@end

