//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CALayer, UIActivityIndicatorView, UILabel;

@interface CMRefreshTableHeaderView : UIView
{
    id _delegate;
    int _state;
    UILabel *_lastUpdatedLabel;
    UILabel *_statusLabel;
    CALayer *_arrowImage;
    UIActivityIndicatorView *_activityView;
}

@property(readonly, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(readonly, nonatomic) CALayer *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(readonly, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(readonly, nonatomic) UILabel *lastUpdatedLabel; // @synthesize lastUpdatedLabel=_lastUpdatedLabel;
@property(nonatomic) id <CMRefreshTableHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)refreshScrollViewDataSourceDidFinishedLoading:(id)arg1;
- (void)refreshScrollViewDidEndDragging:(id)arg1;
- (void)refreshScrollViewDidScroll:(id)arg1;
- (void)setState:(int)arg1;
- (void)refreshLastUpdatedDate;
- (id)initWithFrame:(struct CGRect)arg1 arrowImage:(id)arg2 textColor:(id)arg3;

@end

