//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCopying.h"
#import "NSObject.h"

@class NSDictionary;

@protocol ISSAuthOptions <NSObject, NSCopying>
- (id <ISSAuthOptions>)clone;
- (void)setFollowAccounts:(NSDictionary *)arg1;
- (NSDictionary *)followAccounts;
- (void)setPowerByHidden:(_Bool)arg1;
- (_Bool)powerByHidden;
- (void)setScopes:(NSDictionary *)arg1;
- (NSDictionary *)scopes;
- (void)setAuthManagerViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)authManagerViewDelegate;
- (void)setViewDelegate:(id <ISSViewDelegate>)arg1;
- (id <ISSViewDelegate>)viewDelegate;
- (void)setAllowCallback:(_Bool)arg1;
- (_Bool)allowCallback;
- (void)setAutoAuth:(_Bool)arg1;
- (_Bool)autoAuth;
- (void)setViewStyle:(int)arg1;
- (int)viewStyle;
@end

