//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NSString;

@protocol ISSCParameters <NSObject>
- (NSData *)dataValue:(unsigned long long)arg1 boundary:(NSString *)arg2;
- (NSData *)dataValue:(unsigned long long)arg1;
- (NSString *)stringValue:(unsigned long long)arg1;
- (NSDictionary *)dictionaryValue;
- (long long)parameterCount;
- (id)parameterWithName:(NSString *)arg1;
- (void)clear;
- (void)addParametersWithDictionary:(NSDictionary *)arg1;
- (void)addParameters:(id <ISSCParameters>)arg1;
- (void)addParameter:(NSString *)arg1 fileName:(NSString *)arg2 data:(NSData *)arg3 mimeType:(NSString *)arg4 transferEncoding:(NSString *)arg5;
- (void)addParameter:(NSString *)arg1 filePath:(id)arg2 mimeType:(NSString *)arg3;
- (void)addParameter:(NSString *)arg1 value:(id)arg2;
@end

