//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol ISSCAttachment <NSObject>
- (void)load:(void (^)(void))arg1 faultHandler:(void (^)(NSError *))arg2;
- (_Bool)isRemoteFile;
- (NSString *)mimeType;
- (NSString *)fileName;
- (NSData *)data;
- (NSString *)url;
- (NSString *)path;
@end

