//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@protocol ISSPlatformUser <NSObject>
- (NSArray *)works;
- (NSArray *)educations;
- (long long)level;
- (double)regAt;
- (long long)shareCount;
- (long long)friendCount;
- (long long)followerCount;
- (NSString *)birthday;
- (NSString *)verifyReason;
- (long long)verifyType;
- (NSString *)aboutMe;
- (NSString *)url;
- (long long)gender;
- (NSString *)profileImage;
- (NSString *)nickname;
- (NSString *)uid;
- (int)type;
- (void)setSourceData:(NSDictionary *)arg1;
- (NSDictionary *)sourceData;
- (void)setCredential:(id <ISSPlatformCredential>)arg1;
- (id <ISSPlatformCredential>)credential;
- (id <ISSPlatformApp>)app;
@end

