//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIView;

@protocol ISSPlatformAuthSession <NSObject>
- (_Bool)isSSOLogin;
- (UIView *)view;
- (void)cancel;
- (void)startWithAllowCallback:(_Bool)arg1 ssoLogin:(_Bool)arg2 scopes:(NSArray *)arg3 result:(void (^)(int, id <ISSPlatformCredential>, CMErrorInfo *))arg4;
- (int)type;
@end

