//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol ISSShareView <NSObject>
- (void)dismiss;
- (void)showInContainer:(id <ISSContainer>)arg1 content:(id <ISSContent>)arg2 shareType:(int)arg3 statusBarTips:(_Bool)arg4 authOptions:(id <ISSAuthOptions>)arg5 shareOptions:(id <ISSShareOptions>)arg6 result:(void (^)(int, id <ISSContent>, NSArray *, id <ICMErrorInfo>))arg7;
@end

