//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray, UIImageView;

@interface KASlideShow : UIView
{
    _Bool _doStop;
    _Bool _isAnimating;
    float delay;
    float transitionDuration;
    id <KASlideShowDelegate> delegate;
    long long transitionType;
    NSMutableArray *images;
    id <KASlideShowDataSource> _dataSource;
    unsigned long long _currentIndex;
    UIImageView *_topImageView;
    UIImageView *_bottomImageView;
}

@property(retain, nonatomic) UIImageView *bottomImageView; // @synthesize bottomImageView=_bottomImageView;
@property(retain, nonatomic) UIImageView *topImageView; // @synthesize topImageView=_topImageView;
@property _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property _Bool doStop; // @synthesize doStop=_doStop;
@property(readonly, nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) id <KASlideShowDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images;
@property long long transitionType; // @synthesize transitionType;
@property float transitionDuration; // @synthesize transitionDuration;
@property float delay; // @synthesize delay;
@property(nonatomic) id <KASlideShowDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)handleSwipe:(id)arg1;
- (void)handleSingleTap:(id)arg1;
- (void)addGestureSwipe;
- (void)addGestureTap;
@property(readonly, nonatomic) unsigned long long state;
- (void)stop;
- (void)animateSlide:(long long)arg1;
- (void)animateFade;
- (void)previous;
- (void)next;
- (void)start;
- (void)emptyAndAddImagesFromResources:(id)arg1;
- (void)addImage:(id)arg1;
- (void)addImagesFromResources:(id)arg1;
- (void)addGesture:(long long)arg1;
@property long long imagesContentMode;
- (void)setDefaultValues;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

