//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface Loations : NSObject
{
    NSString *isStartOrEndloation;
    NSString *startLoactionName;
    NSString *endLoactionName;
    struct CLLocationCoordinate2D *startLoationPt;
    struct CLLocationCoordinate2D *endLoationPt;
    NSMutableArray *poinLoationList;
    CDStruct_02837cd9 rect;
    NSString *_isStartOrEndloation;
    NSString *_startLoactionName;
    NSString *_endLoactionName;
    NSMutableArray *_poinLoationList;
    NSString *_nowLoationName;
    struct CLLocationCoordinate2D _startLoationPt;
    struct CLLocationCoordinate2D _endLoationPt;
    struct CLLocationCoordinate2D _nowLoationPt;
    CDStruct_02837cd9 _rect;
}

+ (id)getLoatios;
@property(retain, nonatomic) NSString *nowLoationName; // @synthesize nowLoationName=_nowLoationName;
@property struct CLLocationCoordinate2D nowLoationPt; // @synthesize nowLoationPt=_nowLoationPt;
@property(nonatomic) CDStruct_90e2a262 rect; // @synthesize rect=_rect;
@property(retain, nonatomic) NSMutableArray *poinLoationList; // @synthesize poinLoationList=_poinLoationList;
@property struct CLLocationCoordinate2D endLoationPt; // @synthesize endLoationPt=_endLoationPt;
@property struct CLLocationCoordinate2D startLoationPt; // @synthesize startLoationPt=_startLoationPt;
@property(retain, nonatomic) NSString *endLoactionName; // @synthesize endLoactionName=_endLoactionName;
@property(retain, nonatomic) NSString *startLoactionName; // @synthesize startLoactionName=_startLoactionName;
@property(retain, nonatomic) NSString *isStartOrEndloation; // @synthesize isStartOrEndloation=_isStartOrEndloation;
- (void).cxx_destruct;

@end

