//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIFont, UILabel;

@interface MarqueeLabel : UIView
{
    _Bool labelShouldScroll;
    _Bool awayFromHome;
    _Bool labelize;
    UILabel *subLabel;
    NSString *labelText;
    double animationDuration;
    double lengthOfScroll;
    double rate;
    unsigned long long animationOptions;
    double baseAlpha;
    unsigned long long animationCurve;
    double fadeLength;
    NSString *text;
    UIColor *backgroundColor;
    struct CGRect homeLabelFrame;
    struct CGRect awayLabelFrame;
}

@property(nonatomic) double fadeLength; // @synthesize fadeLength;
@property(nonatomic) _Bool labelize; // @synthesize labelize;
@property(nonatomic) unsigned long long animationCurve; // @synthesize animationCurve;
@property(nonatomic) _Bool awayFromHome; // @synthesize awayFromHome;
@property(nonatomic) double baseAlpha; // @synthesize baseAlpha;
@property(nonatomic) struct CGRect awayLabelFrame; // @synthesize awayLabelFrame;
@property(nonatomic) struct CGRect homeLabelFrame; // @synthesize homeLabelFrame;
@property(nonatomic) unsigned long long animationOptions; // @synthesize animationOptions;
@property(nonatomic) double rate; // @synthesize rate;
@property(nonatomic) double lengthOfScroll; // @synthesize lengthOfScroll;
@property(nonatomic) double animationDuration; // @synthesize animationDuration;
@property(retain, nonatomic) NSString *labelText; // @synthesize labelText;
@property(retain, nonatomic) UILabel *subLabel; // @synthesize subLabel;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;
- (id)valueForUndefinedKey:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
@property(readonly, nonatomic) _Bool labelShouldScroll; // @synthesize labelShouldScroll;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor;
@property(copy, nonatomic) NSString *text; // @synthesize text;
- (void)shutdownLabel;
- (void)restartLabel;
- (void)returnLabelToOriginImmediately;
- (void)scrollRightWithInterval:(double)arg1;
- (void)scrollLeftWithInterval:(double)arg1;
- (void)applyGradientMask;
- (void)observedViewControllerChange:(id)arg1;
- (void)setupLabel;
- (id)initWithFrame:(struct CGRect)arg1 rate:(float)arg2 andFadeLength:(float)arg3;
- (id)initWithFrame:(struct CGRect)arg1 duration:(double)arg2 andFadeLength:(float)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) _Bool adjustsFontSizeToFitWidth; // @dynamic adjustsFontSizeToFitWidth;
@property(nonatomic) long long baselineAdjustment; // @dynamic baselineAdjustment;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @dynamic enabled;
@property(retain, nonatomic) UIFont *font; // @dynamic font;
@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @dynamic highlighted;
@property(retain, nonatomic) UIColor *highlightedTextColor; // @dynamic highlightedTextColor;
@property(nonatomic) long long lineBreakMode; // @dynamic lineBreakMode;
@property(nonatomic) double minimumFontSize; // @dynamic minimumFontSize;
@property(nonatomic) long long numberOfLines; // @dynamic numberOfLines;
@property(retain, nonatomic) UIColor *shadowColor; // @dynamic shadowColor;
@property(nonatomic) struct CGSize shadowOffset; // @dynamic shadowOffset;
@property(nonatomic) long long textAlignment; // @dynamic textAlignment;
@property(retain, nonatomic) UIColor *textColor; // @dynamic textColor;
@property(nonatomic, getter=isUserInteractionEnabled) _Bool userInteractionEnabled; // @dynamic userInteractionEnabled;

@end

