//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Common)
+ (id)guidString;
- (id)dataUsingBase64Decode;
- (id)dataForHexString;
- (long long)hexValue;
- (id)pinyinFirstLetter;
- (id)pinyinString;
- (id)base64Decode:(unsigned long long)arg1;
- (id)base64Encode:(unsigned long long)arg1;
- (id)urlDecode:(unsigned long long)arg1;
- (id)urlEncode:(unsigned long long)arg1;
- (_Bool)containURL;
- (_Bool)isURLString;
- (id)dataUsinghmacSha1StringWithKey:(id)arg1;
- (id)hmacSha1StringWithKey:(id)arg1;
- (id)md5DHexDigestString;
- (id)md5HexDigestString;
- (id)sha1String;
- (long long)versionStringCompare:(id)arg1;
@end

