//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ShareSDKCoreService : NSObject
{
}

+ (id)imageNamed:(id)arg1;
+ (id)localizableString:(id)arg1 comment:(id)arg2;
+ (id)oauthSignatureWithURL:(id)arg1 method:(id)arg2 parameters:(id)arg3 consumerSecret:(id)arg4 oauthTokenSecret:(id)arg5;
+ (id)attachmentWithData:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3;
+ (id)attachmentWithUrl:(id)arg1;
+ (id)attachmentWithPath:(id)arg1;
+ (id)requestWithAccount:(id)arg1;
+ (id)oauthParameters:(id)arg1 consumerSecret:(id)arg2 oauthToken:(id)arg3 oauthSecret:(id)arg4 query:(id)arg5;
+ (id)oauthParameters:(id)arg1 consumerSecret:(id)arg2 oauthToken:(id)arg3 oauthSecret:(id)arg4;
+ (id)parametersWithQuery:(id)arg1;
+ (id)parameters;
+ (_Bool)hasLogined:(id)arg1;
+ (id)loginWithAppKey:(id)arg1;
+ (id)loadUDID;
+ (void)saveWithUDID:(id)arg1;
+ (id)keychainQuery;
+ (id)openUDID;
+ (id)qzoneApiForAppId:(id)arg1;
+ (void)uploadImage:(id)arg1 result:(CDUnknownBlockType)arg2;
+ (void)getShortUrls:(id)arg1 account:(id)arg2 userDescriptor:(id)arg3 shareType:(int)arg4 result:(CDUnknownBlockType)arg5;

@end

