//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SSAwardApi : NSObject
{
}

+ (void)saveCache:(id)arg1;
+ (id)cacheData;
+ (void)setDailyActivation;
+ (_Bool)hasDailyActivation;
+ (void)setInitiaActivation;
+ (_Bool)hasInitialActivation;
+ (id)encryptData:(id)arg1;
+ (id)deviceData;
+ (id)requestData;
+ (void)shareWithInfo:(id)arg1 user:(id)arg2 platType:(int)arg3;
+ (void)getHomepageWithResult:(CDUnknownBlockType)arg1;
+ (void)intentDownloadAppWithCallbackId:(id)arg1;
+ (void)dailyActivation;
+ (void)initialActivation;

@end

