//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSCAccount.h"

@class NSArray, NSString, SSCLogManager;

@interface SSCAccount : NSObject <ISSCAccount>
{
    NSString *_appKey;
    NSString *_baseUrl;
    NSArray *_roles;
    SSCLogManager *_logManager;
    _Bool _ssoEnabled;
    _Bool _convertUrlEnabled;
    _Bool _statEnabled;
    _Bool _statDevEnabled;
    _Bool _statUserEnabled;
    _Bool _statShareEnabled;
    _Bool _useAppTrusteeship;
    _Bool _sendingDeviceInfo;
    _Bool _sendingProcessInfo;
    _Bool _isGetDate;
    double _diffTime;
    double _time;
    double _startupLogTime;
    NSString *cachePath;
}

@property(readonly, nonatomic) _Bool statUserEnabled; // @synthesize statUserEnabled=_statUserEnabled;
@property(readonly, nonatomic) _Bool statShareEnabled; // @synthesize statShareEnabled=_statShareEnabled;
@property(readonly, nonatomic) _Bool statDevEnabled; // @synthesize statDevEnabled=_statDevEnabled;
@property(nonatomic) double startupLogTime; // @synthesize startupLogTime=_startupLogTime;
@property(nonatomic) _Bool statEnabled; // @synthesize statEnabled=_statEnabled;
@property(nonatomic) _Bool convertUrlEnabled; // @synthesize convertUrlEnabled=_convertUrlEnabled;
@property(nonatomic) _Bool ssoEnabled; // @synthesize ssoEnabled=_ssoEnabled;
@property(nonatomic) _Bool useAppTrusteeship; // @synthesize useAppTrusteeship=_useAppTrusteeship;
@property(readonly, nonatomic) NSString *appKey; // @synthesize appKey=_appKey;
- (double)serverTimeIntervalWithClientTimeInterval:(double)arg1;
- (double)currentTimeInterval;
- (void)updatePlatSetting:(CDUnknownBlockType)arg1;
- (int)statPolicy;
- (void)setStatPolicy:(int)arg1;
- (_Bool)checkRole:(Class)arg1;
- (id)roles;
- (void)applicationBecomeActiveHandler:(id)arg1;
- (void)enterBackgroundHandler:(id)arg1;
- (void)enterForegroundHandler:(id)arg1;
- (void)syncDate;
- (void)loadConfig;
- (void)resetConfig;
- (void)saveConfig;
- (double)time;
- (id)deviceData;
- (void)setServerTimeInterval:(double)arg1;
- (id)apiUrl:(id)arg1;
- (void)writeLog:(id)arg1;
- (id)dataWithAESEncrypt:(id)arg1;
@property(readonly, nonatomic) NSString *cachePath; // @synthesize cachePath;
- (void)setup;
- (void)dealloc;
- (id)initWithAppKey:(id)arg1;

@end

