//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSCAccount;

@interface SSCLogInfo : NSObject
{
    double _datetime;
    SSCAccount *_account;
    int _type;
}

@property(readonly, nonatomic) int type; // @synthesize type=_type;
- (id)stringValue;
- (void)dealloc;
- (id)initWithType:(int)arg1 account:(id)arg2;

@end

