//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SSCParameters.h"

#import "ISSCOAuthParameters.h"

@class CMHTTPRequestParameters, SSCConsumer;

@interface SSCOAuthParameters : SSCParameters <ISSCOAuthParameters>
{
    CMHTTPRequestParameters *_oauthParameters;
    SSCConsumer *_consumer;
}

@property(readonly, nonatomic) SSCConsumer *consumer; // @synthesize consumer=_consumer;
@property(readonly, nonatomic) CMHTTPRequestParameters *oauthParameters; // @synthesize oauthParameters=_oauthParameters;
- (id)oauthDictionaryValue;
- (long long)oauthParameterCount;
- (id)oauthParameterWithName:(id)arg1;
- (void)clear;
- (void)addOAuthParametersWithDictionary:(id)arg1;
- (void)addOAuthParameters:(id)arg1;
- (void)addOAuthParameter:(id)arg1 value:(id)arg2;
- (id)oauthSecret;
- (id)oauthToken;
- (id)consumerSecret;
- (id)consumerKey;
- (void)dealloc;
- (id)initWithConsumer:(id)arg1 query:(id)arg2;
- (id)initWithConsumer:(id)arg1;

@end

