//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CMPageViewDataSource.h"
#import "CMPageViewDelegate.h"
#import "SSFlatShareActionSheetDelegate.h"

@class CMPageView, NSArray, UIButton;

@interface SSFlatShareActionSheetView : UIView <CMPageViewDelegate, CMPageViewDataSource, SSFlatShareActionSheetDelegate>
{
    UIButton *_cancelButton;
    CMPageView *_pageView;
    NSArray *_dataSource;
    id <SSFlatShareActionSheetDelegate> _delegate;
}

@property(nonatomic) id <SSFlatShareActionSheetDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void)shareActionSheetOnItemClick:(id)arg1;
- (id)pageView:(id)arg1 pageForIndexPath:(id)arg2;
- (long long)pageViewNumberOfPage:(id)arg1;
- (void)cancelButtonClickHandler:(id)arg1;
- (void)setFrame:(struct CGRect)arg1 bounce:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

