//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SSAuthOptions, SSFacade;

@interface SSFollowUserSession : NSObject
{
    SSFacade *_facade;
    int _shareType;
    int _fieldType;
    NSString *_field;
    SSAuthOptions *_authOptions;
    CDUnknownBlockType _followUserResult;
    id _sessionResult;
    id <ISSViewDelegate> _viewDelegate;
}

- (void)execute;
- (void)start;
- (void)dealloc;
- (id)initWithShareType:(int)arg1 field:(id)arg2 fieldType:(int)arg3 authOptions:(id)arg4 viewDelegate:(id)arg5 followUserResult:(CDUnknownBlockType)arg6 sessionResult:(CDUnknownBlockType)arg7;

@end

