//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ISSAuthView.h"

@class SSAuthOptions, SSFacade, SSModalAuthViewToolbar;

@interface SSFullScreenPopupAuthViewController : UIViewController <ISSAuthView>
{
    id <ISSPlatformAuthSession> _authController;
    SSAuthOptions *_options;
    SSModalAuthViewToolbar *_toolbar;
    _Bool _initialized;
    id _closeHandler;
    SSFacade *_facade;
}

- (void)close:(CDUnknownBlockType)arg1;
- (void)layoutView:(long long)arg1;
- (void)layoutLandscape;
- (void)layoutPortrait;
- (void)powerByButtonClickHandler:(id)arg1;
- (void)cancelButtonClickHandler:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setTitle:(id)arg1;
- (void)dealloc;
- (id)initWithAuthController:(id)arg1 options:(id)arg2 result:(CDUnknownBlockType)arg3;

@end

