//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class SSIPadShareContentView;

@interface SSiPadFlatShareViewController : UIViewController
{
    SSIPadShareContentView *_contentView;
    int _platType;
    id <ISSShareOptions> _shareOptions;
    _Bool _initialized;
}

- (void)updateWithType:(int)arg1 content:(id)arg2 authOptions:(id)arg3 shareOptions:(id)arg4 delegate:(id)arg5;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

