//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CMImageLoader, CMImageView, SSFacade, UIActivityIndicatorView, UIImageView, UILabel;

@interface SSPublishUserInfoCell : UITableViewCell
{
    id <ISSPlatformUser> _userInfo;
    UIActivityIndicatorView *_indicatorView;
    CMImageView *_iconImageView;
    UIImageView *_vipImageView;
    UIImageView *_sexImageView;
    UILabel *_nickNameLabel;
    UILabel *_descLabel;
    _Bool _needLayout;
    SSFacade *_facade;
    CMImageLoader *_loader;
}

@property(retain, nonatomic) id <ISSPlatformUser> userInfo; // @synthesize userInfo=_userInfo;
- (void)iconLoadErrorHandler:(id)arg1;
- (void)iconLoadCompleteHandler:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

