//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SSAuthOptions, SSFacade, SSShareOptions;

@interface SSShareContentSession : NSObject
{
    SSFacade *_facade;
    int _shareType;
    id <ISSContent> _content;
    SSAuthOptions *_authOptions;
    SSShareOptions *_shareOptions;
    _Bool _statusBarTips;
    CDUnknownBlockType _publishContentHandler;
    id _sessionResult;
}

- (void)execute;
- (void)start;
- (void)dealloc;
- (id)initWithShareType:(int)arg1 content:(id)arg2 authOptions:(id)arg3 shareOptions:(id)arg4 statusBarTips:(_Bool)arg5 publishContentHandler:(CDUnknownBlockType)arg6 sessionResult:(CDUnknownBlockType)arg7;

@end

