//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSPlatformCredential.h"
#import "NSCoding.h"

@class NSDate, NSDictionary, NSString;

@interface SSSinaWeiboCredential : NSObject <ISSPlatformCredential, NSCoding>
{
    NSString *_uid;
    NSString *_token;
    NSDate *_expired;
    NSDictionary *_extInfo;
    _Bool available;
}

+ (id)credentialWithSourceData:(id)arg1;
@property(retain, nonatomic) NSDate *expired; // @synthesize expired=_expired;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(retain, nonatomic) NSDictionary *extInfo; // @synthesize extInfo=_extInfo;
@property(readonly, nonatomic) _Bool available; // @synthesize available;
- (id)secret;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;

@end

