//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, SSSinaWeiboStatusInfoReader, SSSinaWeiboUserInfoReader;

@interface SSSinaWeiboCommentReader : NSObject
{
    NSDictionary *_sourceData;
    SSSinaWeiboUserInfoReader *_user;
    SSSinaWeiboStatusInfoReader *_status;
    SSSinaWeiboCommentReader *_replyComment;
    NSString *createdAt;
    long long Id;
    NSString *text;
    NSString *source;
    SSSinaWeiboUserInfoReader *user;
    NSString *mid;
    NSString *idStr;
    SSSinaWeiboStatusInfoReader *status;
    SSSinaWeiboCommentReader *replyComment;
}

+ (id)readerWithSourceData:(id)arg1;
@property(readonly, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(readonly, nonatomic) SSSinaWeiboCommentReader *replyComment; // @synthesize replyComment;
@property(readonly, nonatomic) SSSinaWeiboStatusInfoReader *status; // @synthesize status;
@property(readonly, nonatomic) NSString *idStr; // @synthesize idStr;
@property(readonly, nonatomic) NSString *mid; // @synthesize mid;
@property(readonly, nonatomic) SSSinaWeiboUserInfoReader *user; // @synthesize user;
@property(readonly, nonatomic) NSString *source; // @synthesize source;
@property(readonly, nonatomic) NSString *text; // @synthesize text;
@property(readonly, nonatomic) long long Id; // @synthesize Id;
@property(readonly, nonatomic) NSString *createdAt; // @synthesize createdAt;
- (void)dealloc;
- (id)initWithSourceData:(id)arg1;

@end

