//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

#import "ICMGridItemView.h"

@class CMImageLoader, NSMutableDictionary, SSFacade, UIImageView, UILabel;

@interface SSSNSItemView : UIControl <ICMGridItemView>
{
    UIImageView *_shadowImageView;
    UIImageView *_iconImageView;
    UILabel *_nickNameLabel;
    UIImageView *_siconImageView;
    UIImageView *_selFlagImageView;
    UIImageView *_authImageView;
    SSFacade *_facade;
    CMImageLoader *_loader;
    NSMutableDictionary *_itemData;
    long long _index;
    _Bool _needLayout;
}

- (void)imageLoadErrorHandler:(id)arg1;
- (void)imageLoadCompleteHandler:(id)arg1;
- (void)setIndex:(long long)arg1;
- (long long)index;
- (void)setData:(id)arg1;
- (id)data;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

