//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CMPageViewDataSource.h"
#import "CMPageViewDelegate.h"
#import "SSSNSPageContentViewDelegate.h"

@class CMPageView, NSArray, NSMutableArray, SSFacade, UIImageView;

@interface SSSNSPanel : UIView <CMPageViewDataSource, CMPageViewDelegate, SSSNSPageContentViewDelegate>
{
    UIImageView *_bgImageView;
    CMPageView *_contentView;
    SSFacade *_facade;
    NSMutableArray *_shareList;
    NSMutableArray *_actualShareList;
    long long _pageCount;
    int _originShareType;
    id <ISSAuthOptions> _authOptions;
    _Bool _needLayout;
    CDUnknownBlockType _getUserInfoResult;
    NSArray *_selectedItems;
}

- (void)pageContentView:(id)arg1 itemOnTouch:(id)arg2;
- (id)pageView:(id)arg1 pageForIndexPath:(id)arg2;
- (long long)pageViewNumberOfPage:(id)arg1;
- (void)userInfoUpdateHandler:(id)arg1;
- (void)authorizeHandler:(id)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) NSArray *selectedItems; // @synthesize selectedItems=_selectedItems;
- (void)setOneKeyShareList:(id)arg1 originShareType:(int)arg2 authOptions:(id)arg3 getUserInfoResult:(CDUnknownBlockType)arg4;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

