//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIImageView, UILabel;

@interface SSStatusBarView : UIView
{
    UIActivityIndicatorView *_indicatorView;
    UIImageView *_iconView;
    UILabel *_textLabel;
    _Bool _needLayout;
}

- (void)setMessage:(id)arg1 loading:(_Bool)arg2;
- (void)setMessage:(id)arg1 icon:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

