//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface SSTencentWeiboTagReader : NSObject
{
    NSDictionary *_sourceData;
    NSString *Id;
    NSString *name;
}

+ (id)readerWithSourceData:(id)arg1;
@property(readonly, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(readonly, nonatomic) NSString *name; // @synthesize name;
@property(readonly, nonatomic) NSString *Id; // @synthesize Id;
- (void)dealloc;
- (id)initWithSourceData:(id)arg1;

@end

