//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSCDataObject.h"
#import "ISSPlatformUser.h"
#import "NSCoding.h"

@class NSArray, NSDictionary, NSString, SSTencentWeiboUserReader;

@interface SSTencentWeiboUser : NSObject <ISSPlatformUser, NSCoding, ISSCDataObject>
{
    NSDictionary *_sourceData;
    SSTencentWeiboUserReader *_reader;
    id <ISSPlatformCredential> _credential;
    id <ISSPlatformApp> _app;
    int type;
    NSString *uid;
    NSString *nickname;
    NSString *profileImage;
    long long gender;
    NSString *url;
    NSString *aboutMe;
    long long verifyType;
    NSString *verifyReason;
    NSString *birthday;
    long long followerCount;
    long long friendCount;
    long long shareCount;
    double regAt;
    long long level;
    NSArray *educations;
    NSArray *works;
}

@property(retain, nonatomic) NSDictionary *sourceData; // @synthesize sourceData=_sourceData;
@property(retain, nonatomic) id <ISSPlatformCredential> credential; // @synthesize credential=_credential;
@property(nonatomic) id <ISSPlatformApp> app; // @synthesize app=_app;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) NSArray *works; // @synthesize works;
@property(readonly, nonatomic) NSArray *educations; // @synthesize educations;
@property(readonly, nonatomic) long long level; // @synthesize level;
@property(readonly, nonatomic) double regAt; // @synthesize regAt;
@property(readonly, nonatomic) long long shareCount; // @synthesize shareCount;
@property(readonly, nonatomic) long long friendCount; // @synthesize friendCount;
@property(readonly, nonatomic) long long followerCount; // @synthesize followerCount;
@property(readonly, nonatomic) NSString *birthday; // @synthesize birthday;
@property(readonly, nonatomic) NSString *verifyReason; // @synthesize verifyReason;
@property(readonly, nonatomic) long long verifyType; // @synthesize verifyType;
@property(readonly, nonatomic) NSString *aboutMe; // @synthesize aboutMe;
@property(readonly, nonatomic) NSString *url; // @synthesize url;
@property(readonly, nonatomic) long long gender; // @synthesize gender;
@property(readonly, nonatomic) NSString *profileImage; // @synthesize profileImage;
@property(readonly, nonatomic) NSString *nickname; // @synthesize nickname;
@property(readonly, nonatomic) NSString *uid; // @synthesize uid;
@property(readonly, nonatomic) int type; // @synthesize type;
- (void)dealloc;
- (id)initWithApp:(id)arg1;

@end

