//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISSUserField.h"

@class NSString;

@interface SSUserField : NSObject <ISSUserField>
{
    NSString *_value;
    int _type;
}

@property(nonatomic) int type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
- (void)dealloc;

@end

