//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UILabel;

@interface THXAboutViewController : UIViewController
{
    UILabel *_about;
    UILabel *_server;
    UILabel *_underLine;
    UIButton *_ty7777;
    UIButton *_uwsxx;
}

@property(nonatomic) __weak UIButton *uwsxx; // @synthesize uwsxx=_uwsxx;
@property(nonatomic) __weak UIButton *ty7777; // @synthesize ty7777=_ty7777;
@property(nonatomic) __weak UILabel *underLine; // @synthesize underLine=_underLine;
@property(nonatomic) __weak UILabel *server; // @synthesize server=_server;
@property(nonatomic) __weak UILabel *about; // @synthesize about=_about;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)OpenUwsxx;
- (void)OpenTy7777;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

