//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface THXBikeSiteService : NSObject
{
}

- (id)getListBySiteId:(id)arg1;
- (id)getBySiteName:(id)arg1;
- (void)updateSiteStatus:(id)arg1;
- (id)getBySiteId:(id)arg1;
- (id)getByJuli:(CDStruct_90e2a262)arg1;
- (id)getByFanWei:(CDStruct_90e2a262)arg1;
- (void)saveBikeSite:(id)arg1;

@end

