//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPopoverListViewDataSource.h"
#import "UIPopoverListViewDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UIProgressView, UITextView, UIView;

@interface THXBikeSiteDetailViewController : UIViewController <UIPopoverListViewDataSource, UIPopoverListViewDelegate>
{
    NSString *jd;
    NSString *wd;
    long long *isshow;
    UILabel *_bikeNameLab;
    UILabel *_numlab;
    UILabel *_fromlab;
    UIButton *_sharebtn;
    UIButton *_concernBtn;
    UILabel *_bikeSiteName;
    UILabel *_bikeSiteNum;
    UILabel *_bikeSiteLocation;
    UILabel *_canUseBikeCount;
    UILabel *_canUsePosCount;
    UIProgressView *_progress;
    UILabel *_toHere;
    UILabel *_fromHere;
    UILabel *_searchNear;
    UILabel *_point;
    UIView *_jiucuoView;
    UILabel *_jiucuoTepyLable;
    UIImageView *_closeJiucuo;
    UIImageView *_jiucuoImage;
    UIImageView *_jiucuoweizhiImage;
    UILabel *_jiucuoJD;
    UILabel *_jiucuoWD;
    UILabel *_jiucuoTxtLable;
    UILabel *_jiucuoweizhi;
    UITextView *_jiucuoTextView;
    UIImageView *_jiucuoBeijin;
    NSString *_pointTitle;
    long long _exceptionType;
}

+ (void)setSite:(id)arg1;
@property long long exceptionType; // @synthesize exceptionType=_exceptionType;
@property(retain, nonatomic) NSString *pointTitle; // @synthesize pointTitle=_pointTitle;
@property(nonatomic) __weak UIImageView *jiucuoBeijin; // @synthesize jiucuoBeijin=_jiucuoBeijin;
@property(nonatomic) __weak UITextView *jiucuoTextView; // @synthesize jiucuoTextView=_jiucuoTextView;
@property(nonatomic) __weak UILabel *jiucuoweizhi; // @synthesize jiucuoweizhi=_jiucuoweizhi;
@property(nonatomic) __weak UILabel *jiucuoTxtLable; // @synthesize jiucuoTxtLable=_jiucuoTxtLable;
@property(nonatomic) __weak UILabel *jiucuoWD; // @synthesize jiucuoWD=_jiucuoWD;
@property(nonatomic) __weak UILabel *jiucuoJD; // @synthesize jiucuoJD=_jiucuoJD;
@property(nonatomic) __weak UIImageView *jiucuoweizhiImage; // @synthesize jiucuoweizhiImage=_jiucuoweizhiImage;
@property(nonatomic) __weak UIImageView *jiucuoImage; // @synthesize jiucuoImage=_jiucuoImage;
@property(nonatomic) __weak UIImageView *closeJiucuo; // @synthesize closeJiucuo=_closeJiucuo;
@property(nonatomic) __weak UILabel *jiucuoTepyLable; // @synthesize jiucuoTepyLable=_jiucuoTepyLable;
@property(nonatomic) __weak UIView *jiucuoView; // @synthesize jiucuoView=_jiucuoView;
@property(nonatomic) __weak UILabel *point; // @synthesize point=_point;
@property(nonatomic) __weak UILabel *searchNear; // @synthesize searchNear=_searchNear;
@property(nonatomic) __weak UILabel *fromHere; // @synthesize fromHere=_fromHere;
@property(nonatomic) __weak UILabel *toHere; // @synthesize toHere=_toHere;
@property(nonatomic) __weak UIProgressView *progress; // @synthesize progress=_progress;
@property(nonatomic) __weak UILabel *canUsePosCount; // @synthesize canUsePosCount=_canUsePosCount;
@property(nonatomic) __weak UILabel *canUseBikeCount; // @synthesize canUseBikeCount=_canUseBikeCount;
@property(nonatomic) __weak UILabel *bikeSiteLocation; // @synthesize bikeSiteLocation=_bikeSiteLocation;
@property(nonatomic) __weak UILabel *bikeSiteNum; // @synthesize bikeSiteNum=_bikeSiteNum;
@property(nonatomic) __weak UILabel *bikeSiteName; // @synthesize bikeSiteName=_bikeSiteName;
@property(nonatomic) __weak UIButton *concernBtn; // @synthesize concernBtn=_concernBtn;
@property(nonatomic) __weak UIButton *sharebtn; // @synthesize sharebtn=_sharebtn;
@property(nonatomic) __weak UILabel *fromlab; // @synthesize fromlab=_fromlab;
@property(nonatomic) __weak UILabel *numlab; // @synthesize numlab=_numlab;
@property(nonatomic) __weak UILabel *bikeNameLab; // @synthesize bikeNameLab=_bikeNameLab;
@property(nonatomic) long long *isshow; // @synthesize isshow;
@property(retain, nonatomic) NSString *wd; // @synthesize wd;
@property(retain, nonatomic) NSString *jd; // @synthesize jd;
- (void).cxx_destruct;
- (void)loaddata;
- (void)concernBikeSite:(id)arg1;
- (_Bool)isNet;
- (void)shareBikeSite:(id)arg1;
- (void)jiucuoClick:(id)arg1;
- (double)popoverListView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)popoverListView:(id)arg1 didSelectIndexPath:(id)arg2;
- (long long)popoverListView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)popoverListView:(id)arg1 cellForIndexPath:(id)arg2;
- (void)print;
- (void)searhNearEvent:(id)arg1;
- (void)fromHereEvent:(id)arg1;
- (void)toHereEvent:(id)arg1;
- (void)toBikeMapEvent:(id)arg1;
- (void)tomap:(id)arg1;
- (void)closekey:(id)arg1;
- (void)closejiucuo:(id)arg1;
- (void)typechange:(id)arg1;
- (void)reportEvent;
- (id)initWithCoder:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dataInit;
- (void)uiInit;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

