//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPopoverListViewDataSource.h"
#import "UIPopoverListViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"

@class NSString, UIButton, UILabel, UIScrollView, UITextField, UITextView;

@interface THXFeedbackViewController : UIViewController <UITextViewDelegate, UITextFieldDelegate, UIPopoverListViewDataSource, UIPopoverListViewDelegate>
{
    UIScrollView *_ScrollView;
    UIButton *_funButton;
    UILabel *_OutLabel;
    UITextView *_ViewText;
    UITextField *_ContactText;
    UIButton *_SubButton;
    UILabel *_tiplab;
    int *_isEmpty;
}

@property int *isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) __weak UILabel *tiplab; // @synthesize tiplab=_tiplab;
@property(nonatomic) __weak UIButton *SubButton; // @synthesize SubButton=_SubButton;
@property(nonatomic) __weak UITextField *ContactText; // @synthesize ContactText=_ContactText;
@property(nonatomic) __weak UITextView *ViewText; // @synthesize ViewText=_ViewText;
@property(nonatomic) __weak UILabel *OutLabel; // @synthesize OutLabel=_OutLabel;
@property(nonatomic) __weak UIButton *funButton; // @synthesize funButton=_funButton;
@property(nonatomic) __weak UIScrollView *ScrollView; // @synthesize ScrollView=_ScrollView;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)keyboardHide:(id)arg1;
- (void)loadShiDate;
- (double)popoverListView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)popoverListView:(id)arg1 didSelectIndexPath:(id)arg2;
- (long long)popoverListView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)popoverListView:(id)arg1 cellForIndexPath:(id)arg2;
- (void)SelectType:(id)arg1;
- (void)backgroundTap:(id)arg1;
- (void)submitView:(id)arg1;
- (void)showTiplab;
- (_Bool)isNet;
- (void)didReceiveMemoryWarning;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

