//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKLocationServiceDelegate.h"
#import "BMKMapViewDelegate.h"
#import "FDAlertViewDelegate.h"
#import "SlideNavigationControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIPopoverListViewDataSource.h"
#import "UIPopoverListViewDelegate.h"

@class BMKAnnotationView, BMKCircle, BMKGeoCodeSearch, BMKLocationService, BMKMapView, BMKPointAnnotation, MarqueeLabel, NSMutableArray, NSMutableDictionary, NSString, THXBikeSite, THXSearchViewController, UIActivityIndicatorView, UIImageView, UILabel, UIScrollView, UITabBar, UITextField, UITextView, UIView;

@interface THXNearbyController : UIViewController <BMKMapViewDelegate, SlideNavigationControllerDelegate, UIGestureRecognizerDelegate, UIPopoverListViewDataSource, UIPopoverListViewDelegate, BMKLocationServiceDelegate, BMKGeoCodeSearchDelegate, FDAlertViewDelegate>
{
    _Bool _isfirst;
    _Bool _loadAll;
    _Bool _isfresh;
    BMKAnnotationView *selectView;
    NSString *jingdu;
    NSString *weidu;
    long long *isshow;
    UITabBar *_tabBarClienck;
    CDUnknownBlockType _blocks;
    NSMutableArray *_sitees;
    THXNearbyController *_fujinVC;
    THXSearchViewController *_souSuoVC;
    BMKMapView *_mapView;
    UIImageView *_selectImage;
    UITextView *_text;
    UIImageView *_xximageView;
    UIImageView *_dwimageView;
    UIImageView *_tianqiImage;
    UIImageView *_shuaxin;
    UIView *_fanwei;
    UIView *_tianqi;
    UIView *_juliView;
    UIImageView *_juliImage;
    UILabel *_juliText;
    UIView *_juliImageView;
    UIImageView *_dingwei;
    UIImageView *_fangda;
    UIImageView *_suoxiao;
    UIScrollView *_xiangqingView;
    UILabel *_tishi;
    UITextField *_sizeNameText;
    UITextField *_sizeCodeText;
    UITextField *_kejie;
    UITextField *_chehuan;
    UIImageView *_closeImage;
    UIImageView *_guanzhu;
    UIImageView *_zhiyin;
    UIImageView *_sousuo;
    UIImageView *_jiucuo;
    UIActivityIndicatorView *_kejiz;
    UIActivityIndicatorView *_kehuanz;
    UIImageView *_hiddeImage;
    UIImageView *_allSite;
    UIImageView *_maxSite;
    UIImageView *_maxinSite;
    UIImageView *_minSite;
    BMKCircle *_circle;
    UIActivityIndicatorView *_indiview;
    MarqueeLabel *_tianqiLab;
    UIView *_jiucuoView;
    UILabel *_jiucuoTepyLable;
    UIImageView *_closeJiucuo;
    UIImageView *_jiucuoImage;
    UIImageView *_jiucuoweizhiImage;
    UILabel *_jiucuoJD;
    UILabel *_jiucuoWD;
    UILabel *_jiucuoTxtLable;
    UITextView *_jiucuoTextView;
    UIImageView *_jiucuoBeijin;
    UILabel *_jiucuoweizhi;
    BMKLocationService *_locService;
    BMKGeoCodeSearch *_geoCode;
    NSMutableArray *_itemDatas;
    long long _exceptionType;
    NSString *_tianqiInfo;
    MarqueeLabel *_rateLabelOne;
    NSMutableArray *_bikeitemDatas;
    BMKPointAnnotation *_annotationTan;
    UIView *_popview;
    THXBikeSite *_localBike;
    UIActivityIndicatorView *_activityIndicator;
    NSMutableDictionary *_weatherData;
}

+ (void)setSite:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *weatherData; // @synthesize weatherData=_weatherData;
@property _Bool isfresh; // @synthesize isfresh=_isfresh;
@property(retain) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property _Bool loadAll; // @synthesize loadAll=_loadAll;
@property(retain, nonatomic) THXBikeSite *localBike; // @synthesize localBike=_localBike;
@property(retain, nonatomic) UIView *popview; // @synthesize popview=_popview;
@property(retain) BMKPointAnnotation *annotationTan; // @synthesize annotationTan=_annotationTan;
@property _Bool isfirst; // @synthesize isfirst=_isfirst;
@property(retain, nonatomic) NSMutableArray *bikeitemDatas; // @synthesize bikeitemDatas=_bikeitemDatas;
@property(retain) MarqueeLabel *rateLabelOne; // @synthesize rateLabelOne=_rateLabelOne;
@property(retain) NSString *tianqiInfo; // @synthesize tianqiInfo=_tianqiInfo;
@property long long exceptionType; // @synthesize exceptionType=_exceptionType;
@property(retain, nonatomic) NSMutableArray *itemDatas; // @synthesize itemDatas=_itemDatas;
@property(retain, nonatomic) BMKGeoCodeSearch *geoCode; // @synthesize geoCode=_geoCode;
@property(retain, nonatomic) BMKLocationService *locService; // @synthesize locService=_locService;
@property(nonatomic) __weak UILabel *jiucuoweizhi; // @synthesize jiucuoweizhi=_jiucuoweizhi;
@property(nonatomic) __weak UIImageView *jiucuoBeijin; // @synthesize jiucuoBeijin=_jiucuoBeijin;
@property(nonatomic) __weak UITextView *jiucuoTextView; // @synthesize jiucuoTextView=_jiucuoTextView;
@property(nonatomic) __weak UILabel *jiucuoTxtLable; // @synthesize jiucuoTxtLable=_jiucuoTxtLable;
@property(nonatomic) __weak UILabel *jiucuoWD; // @synthesize jiucuoWD=_jiucuoWD;
@property(nonatomic) __weak UILabel *jiucuoJD; // @synthesize jiucuoJD=_jiucuoJD;
@property(nonatomic) __weak UIImageView *jiucuoweizhiImage; // @synthesize jiucuoweizhiImage=_jiucuoweizhiImage;
@property(nonatomic) __weak UIImageView *jiucuoImage; // @synthesize jiucuoImage=_jiucuoImage;
@property(nonatomic) __weak UIImageView *closeJiucuo; // @synthesize closeJiucuo=_closeJiucuo;
@property(nonatomic) __weak UILabel *jiucuoTepyLable; // @synthesize jiucuoTepyLable=_jiucuoTepyLable;
@property(nonatomic) __weak UIView *jiucuoView; // @synthesize jiucuoView=_jiucuoView;
@property(nonatomic) __weak MarqueeLabel *tianqiLab; // @synthesize tianqiLab=_tianqiLab;
@property(retain, nonatomic) UIActivityIndicatorView *indiview; // @synthesize indiview=_indiview;
@property(retain, nonatomic) BMKCircle *circle; // @synthesize circle=_circle;
@property(nonatomic) __weak UIImageView *minSite; // @synthesize minSite=_minSite;
@property(nonatomic) __weak UIImageView *maxinSite; // @synthesize maxinSite=_maxinSite;
@property(nonatomic) __weak UIImageView *maxSite; // @synthesize maxSite=_maxSite;
@property(nonatomic) __weak UIImageView *allSite; // @synthesize allSite=_allSite;
@property(nonatomic) __weak UIImageView *hiddeImage; // @synthesize hiddeImage=_hiddeImage;
@property(nonatomic) __weak UIActivityIndicatorView *kehuanz; // @synthesize kehuanz=_kehuanz;
@property(nonatomic) __weak UIActivityIndicatorView *kejiz; // @synthesize kejiz=_kejiz;
@property(nonatomic) __weak UIImageView *jiucuo; // @synthesize jiucuo=_jiucuo;
@property(nonatomic) __weak UIImageView *sousuo; // @synthesize sousuo=_sousuo;
@property(nonatomic) __weak UIImageView *zhiyin; // @synthesize zhiyin=_zhiyin;
@property(nonatomic) __weak UIImageView *guanzhu; // @synthesize guanzhu=_guanzhu;
@property(nonatomic) __weak UIImageView *closeImage; // @synthesize closeImage=_closeImage;
@property(nonatomic) __weak UITextField *chehuan; // @synthesize chehuan=_chehuan;
@property(nonatomic) __weak UITextField *kejie; // @synthesize kejie=_kejie;
@property(nonatomic) __weak UITextField *sizeCodeText; // @synthesize sizeCodeText=_sizeCodeText;
@property(nonatomic) __weak UITextField *sizeNameText; // @synthesize sizeNameText=_sizeNameText;
@property(nonatomic) __weak UILabel *tishi; // @synthesize tishi=_tishi;
@property(nonatomic) __weak UIScrollView *xiangqingView; // @synthesize xiangqingView=_xiangqingView;
@property(nonatomic) __weak UIImageView *suoxiao; // @synthesize suoxiao=_suoxiao;
@property(nonatomic) __weak UIImageView *fangda; // @synthesize fangda=_fangda;
@property(nonatomic) __weak UIImageView *dingwei; // @synthesize dingwei=_dingwei;
@property(nonatomic) __weak UIView *juliImageView; // @synthesize juliImageView=_juliImageView;
@property(nonatomic) __weak UILabel *juliText; // @synthesize juliText=_juliText;
@property(nonatomic) __weak UIImageView *juliImage; // @synthesize juliImage=_juliImage;
@property(nonatomic) __weak UIView *juliView; // @synthesize juliView=_juliView;
@property(nonatomic) __weak UIView *tianqi; // @synthesize tianqi=_tianqi;
@property(nonatomic) __weak UIView *fanwei; // @synthesize fanwei=_fanwei;
@property(nonatomic) __weak UIImageView *shuaxin; // @synthesize shuaxin=_shuaxin;
@property(nonatomic) __weak UIImageView *tianqiImage; // @synthesize tianqiImage=_tianqiImage;
@property(retain, nonatomic) UIImageView *dwimageView; // @synthesize dwimageView=_dwimageView;
@property(retain, nonatomic) UIImageView *xximageView; // @synthesize xximageView=_xximageView;
@property(retain, nonatomic) UITextView *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImageView *selectImage; // @synthesize selectImage=_selectImage;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) THXSearchViewController *souSuoVC; // @synthesize souSuoVC=_souSuoVC;
@property(retain, nonatomic) THXNearbyController *fujinVC; // @synthesize fujinVC=_fujinVC;
@property(retain, nonatomic) NSMutableArray *sitees; // @synthesize sitees=_sitees;
@property(copy, nonatomic) CDUnknownBlockType blocks; // @synthesize blocks=_blocks;
@property(nonatomic) __weak UITabBar *tabBarClienck; // @synthesize tabBarClienck=_tabBarClienck;
@property(nonatomic) long long *isshow; // @synthesize isshow;
@property(retain, nonatomic) NSString *weidu; // @synthesize weidu;
@property(retain, nonatomic) NSString *jingdu; // @synthesize jingdu;
@property(retain, nonatomic) BMKAnnotationView *selectView; // @synthesize selectView;
- (void).cxx_destruct;
- (void)addAllCity;
- (void)onMain;
- (void)beginSonThread;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loadAllCity;
- (void)loadMyFocusBites;
- (void)jiucuoClick:(id)arg1;
- (void)setBlock:(CDUnknownBlockType)arg1;
- (_Bool)slideNavigationControllerShouldDisplayRightMenu;
- (_Bool)slideNavigationControllerShouldDisplayLeftMenu;
- (void)bigDemo;
- (void)loadTianQi;
- (void)mapView:(id)arg1 onClickedMapBlank:(struct CLLocationCoordinate2D)arg2;
- (void)loadShiDate;
- (double)distanceBetweenOrderBy:(double)arg1:(double)arg2:(double)arg3:(double)arg4;
- (id)createView:(id)arg1;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)willStartLocatingUser;
- (void)mapview:(id)arg1 onDoubleClick:(struct CLLocationCoordinate2D)arg2;
- (float)getMapNum:(float)arg1;
- (void)hiddeAndSelectFanwei:(id)arg1;
- (void)hiddeAndSelectTuBiao:(id)arg1;
- (double)popoverListView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)popoverListView:(id)arg1 didSelectIndexPath:(id)arg2;
- (long long)popoverListView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)popoverListView:(id)arg1 cellForIndexPath:(id)arg2;
- (void)imageClick:(id)arg1;
- (_Bool)isNet;
- (void)showInputView;
- (void)print;
- (void)onClickImage;
- (id)initWithCoder:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadImage;
- (void)addclick;
- (void)righttMenuSelected:(id)arg1;
- (void)location;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

