//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSNumber, NSString;

@interface THXUser : NSObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *age; // @dynamic age;
@property(retain, nonatomic) NSNumber *apnUserId; // @dynamic apnUserId;
@property(retain, nonatomic) NSData *createDate; // @dynamic createDate;
@property(retain, nonatomic) NSString *email; // @dynamic email;
@property(retain, nonatomic) NSString *imei; // @dynamic imei;
@property(retain, nonatomic) NSString *online; // @dynamic online;
@property(retain, nonatomic) NSString *password; // @dynamic password;
@property(retain, nonatomic) NSString *phoneNumber; // @dynamic phoneNumber;
@property(retain, nonatomic) NSString *portrait; // @dynamic portrait;
@property(retain, nonatomic) NSNumber *sex; // @dynamic sex;
@property(retain, nonatomic) NSString *state; // @dynamic state;
@property(retain, nonatomic) NSData *updateDate; // @dynamic updateDate;
@property(retain, nonatomic) NSString *username; // @dynamic username;
@end

