//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray;

@interface WYPopoverOverlayView : UIView
{
    _Bool _isAccessible;
    _Bool _testHits;
    id <WYPopoverOverlayViewDelegate> _delegate;
    NSArray *_passthroughViews;
}

@property(nonatomic) NSArray *passthroughViews; // @synthesize passthroughViews=_passthroughViews;
@property(nonatomic) _Bool testHits; // @synthesize testHits=_testHits;
@property(nonatomic) id <WYPopoverOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)accessibilityElementDidLoseFocus;
- (void)accessibilityElementDidBecomeFocused;
- (_Bool)isPassthroughView:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

