//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ASSSettingModelOpen : NSObject
{
}

+ (void)clearSetting;
+ (void)saveSetting;
+ (void)initializeSettings;
+ (void)setLogUploadSwitch:(_Bool)arg1;
+ (_Bool)getLogUploadSwitch;
+ (void)setGidSwitch:(_Bool)arg1;
+ (_Bool)getGidSwitch;
+ (void)setVkeySwitchInDataMode:(_Bool)arg1;
+ (_Bool)getVkeySwitchInDataMode;
+ (void)setVkeySwitchInTokenMode:(_Bool)arg1;
+ (_Bool)getVkeySwitchInTokenMode;
+ (void)setWebrtcSwitch:(id)arg1;
+ (id)getWebrtcSwitch;

@end

