//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "AwesomeMenuItemDelegate.h"

@class AwesomeMenuItem, NSArray, NSString, NSTimer, UIImage;

@interface AwesomeMenu : UIView <AwesomeMenuItemDelegate>
{
    NSArray *_menusArray;
    unsigned long long _flag;
    NSTimer *_timer;
    AwesomeMenuItem *_startButton;
    id <AwesomeMenuDelegate> _delegate;
    _Bool _isAnimating;
    _Bool rotateAddButton;
    _Bool _expanding;
    double nearRadius;
    double endRadius;
    double farRadius;
    double timeOffset;
    double rotateAngle;
    double menuWholeAngle;
    double expandRotation;
    double closeRotation;
    double animationDuration;
    struct CGPoint startPoint;
}

@property(copy, nonatomic) NSArray *menusArray; // @synthesize menusArray=_menusArray;
@property(nonatomic) __weak id <AwesomeMenuDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool rotateAddButton; // @synthesize rotateAddButton;
@property(nonatomic) double animationDuration; // @synthesize animationDuration;
@property(nonatomic) double closeRotation; // @synthesize closeRotation;
@property(nonatomic) double expandRotation; // @synthesize expandRotation;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint;
@property(nonatomic) double menuWholeAngle; // @synthesize menuWholeAngle;
@property(nonatomic) double rotateAngle; // @synthesize rotateAngle;
@property(nonatomic) double timeOffset; // @synthesize timeOffset;
@property(nonatomic) double farRadius; // @synthesize farRadius;
@property(nonatomic) double endRadius; // @synthesize endRadius;
@property(nonatomic) double nearRadius; // @synthesize nearRadius;
- (void).cxx_destruct;
- (id)_shrinkAnimationAtPoint:(struct CGPoint)arg1;
- (id)_blowupAnimationAtPoint:(struct CGPoint)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_close;
- (void)_expand;
@property(nonatomic, getter=isExpanding) _Bool expanding; // @synthesize expanding=_expanding;
- (void)_setMenu;
- (void)AwesomeMenuItemTouchesEnd:(id)arg1;
- (void)AwesomeMenuItemTouchesBegan:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) UIImage *highlightedContentImage;
@property(retain, nonatomic) UIImage *contentImage;
@property(retain, nonatomic) UIImage *highlightedImage;
@property(retain, nonatomic) UIImage *image;
- (id)initWithFrame:(struct CGRect)arg1 startItem:(id)arg2 optionMenus:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

