//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSString;

@interface BaiduMobStatLogManager : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *locationManager_;
    CDStruct_2c43369c currentLoc_;
    double timestamp_;
    NSString *appId;
    double lastSendTimestamp;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
- (void)resetLogSentIndexPerSession;
- (void)_setLogSentIndexPerSession:(int)arg1;
- (int)_logSentIndexPerSession;
@property(nonatomic) double lastSendTimestamp; // @synthesize lastSendTimestamp;
- (void)summarize;
- (void)log;
- (void)sendLog:(_Bool)arg1;
- (unsigned long long)getOBJSizeForJSON:(id)arg1;
- (unsigned long long)logSize;
- (_Bool)_syncSendLog:(id)arg1;
- (void)_syncSendAllLog;
- (void)putEventWithDurationTime:(id)arg1;
- (void)putEvent:(id)arg1;
- (void)putException:(id)arg1;
- (void)_syncPutException:(id)arg1;
- (void)_syncPutEvent:(id)arg1;
- (void)_syncPutEventWithDurationTime:(id)arg1;
- (id)getInprogressSession;
- (void)putInprogressSession:(id)arg1;
- (void)putSession:(id)arg1;
- (void)_syncPutSession:(id)arg1;
- (id)createLogHeader;
- (id)createBlankLog;
- (id)init;
- (id)gzipDeflate:(id)arg1;
- (id)gzipInflate:(id)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)asyncGetLocation;

@end

