//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BaiduMobStatDeviceInfo : NSObject
{
}

+ (int)totalDiskSpace;
+ (id)modelType;
+ (id)memory;
+ (id)platform;
+ (id)getInternetConnection;
+ (id)getBundleVersion;
+ (id)getBundleIdentifier;
+ (struct CGSize)getScreenResolution;
+ (id)getNOP;
+ (id)getMacAddress;
+ (void)printAppInfo;

@end

