//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface BaiduMobStatExceptionHandler : NSObject
{
    _Bool dismissed;
    int _analyzerStarted;
    _Bool _crashReportActivated;
    NSData *_crashData;
}

+ (void)unregisterUncaughtExceptionHandler;
+ (void)registerUncaughtExceptionHandler;
- (void)handleException:(id)arg1;
- (void)validateAndSaveCriticalApplicationData;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;

@end

