//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface BaiduMobStatSession : NSObject
{
    int logSentCount;
    double sStart;
    double sEnd;
    NSString *Id;
    NSMutableArray *pageViews;
}

@property(readonly, nonatomic) NSMutableArray *pageViews; // @synthesize pageViews;
@property(nonatomic) int logSentCount; // @synthesize logSentCount;
@property(readonly, nonatomic) NSString *Id; // @synthesize Id;
@property(readonly, nonatomic) double sEnd; // @synthesize sEnd;
@property(readonly, nonatomic) double sStart; // @synthesize sStart;
- (id)dictionaryRepresentation;
- (void)dealloc;
- (void)addPageView:(id)arg1;
- (void)end;
- (void)start;
- (id)init;

@end

