//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UILabel, UIView;

@interface BaseViewController : SuperViewController <UITextFieldDelegate>
{
    UIView *_navView;
    UIButton *_backBtn;
    UILabel *_titleLabel;
    UILabel *_rightLabel;
}

@property(retain, nonatomic) UILabel *_rightLabel; // @synthesize _rightLabel;
@property(retain, nonatomic) UILabel *_titleLabel; // @synthesize _titleLabel;
@property(retain, nonatomic) UIButton *_backBtn; // @synthesize _backBtn;
@property(retain, nonatomic) UIView *_navView; // @synthesize _navView;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyboard;
- (void)clickBack:(id)arg1;
- (float)boolLabelLength:(id)arg1;
- (void)showNavBar:(id)arg1 rightStr:(id)arg2 back:(_Bool)arg3;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

