//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BPushRequest.h"

@class NSString;

@interface BPushBindRequest : BPushRequest
{
    NSString *_deviceToken;
}

@property(retain, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
- (void).cxx_destruct;
- (id)HttpBody;
- (id)init;

@end

