//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSString;

@interface CallServiceActionSheetView : UIView <UIGestureRecognizerDelegate>
{
    CDUnknownBlockType _buttonSelectedBlock;
    UIView *_bgView;
    UIView *_mainView;
}

@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType buttonSelectedBlock; // @synthesize buttonSelectedBlock=_buttonSelectedBlock;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)showAnimations;
- (void)hideAnimations;
- (void)tapGesture;
- (void)hide;
- (void)show;
- (void)showWithCompletion:(CDUnknownBlockType)arg1;
- (void)buttonDidClicked:(id)arg1;
- (void)setupActionSheetViewWithCancelButtonTitle:(id)arg1 otherButtonTitle:(id)arg2;
- (id)initWithCancelButtonTitle:(id)arg1 otherButtonTitle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

