//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface CarTypeNoEstimateResultCollectionViewCell : UICollectionViewCell
{
    UIImageView *_backgroundImageView;
    UIImageView *_carTypeImageView;
    UILabel *_carTypeNameLabel;
    UILabel *_mileagePriceLabel;
    UILabel *_timePriceLabel;
    NSLayoutConstraint *_carTypeImageViewBottomSpaceConstraint;
    NSLayoutConstraint *_carTypeImageViewHeightConstraint;
    NSLayoutConstraint *_carTypeNameLabelTopConstraint;
    NSLayoutConstraint *_overHLineHeightConstraint;
    NSLayoutConstraint *_overVLineHeightConstraint;
    UIView *_overHLineView;
    UIView *_chargeStandardContentView;
}

@property(nonatomic) __weak UIView *chargeStandardContentView; // @synthesize chargeStandardContentView=_chargeStandardContentView;
@property(nonatomic) __weak UIView *overHLineView; // @synthesize overHLineView=_overHLineView;
@property(nonatomic) __weak NSLayoutConstraint *overVLineHeightConstraint; // @synthesize overVLineHeightConstraint=_overVLineHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *overHLineHeightConstraint; // @synthesize overHLineHeightConstraint=_overHLineHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeNameLabelTopConstraint; // @synthesize carTypeNameLabelTopConstraint=_carTypeNameLabelTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeImageViewHeightConstraint; // @synthesize carTypeImageViewHeightConstraint=_carTypeImageViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeImageViewBottomSpaceConstraint; // @synthesize carTypeImageViewBottomSpaceConstraint=_carTypeImageViewBottomSpaceConstraint;
@property(nonatomic) __weak UILabel *timePriceLabel; // @synthesize timePriceLabel=_timePriceLabel;
@property(nonatomic) __weak UILabel *mileagePriceLabel; // @synthesize mileagePriceLabel=_mileagePriceLabel;
@property(nonatomic) __weak UILabel *carTypeNameLabel; // @synthesize carTypeNameLabel=_carTypeNameLabel;
@property(nonatomic) __weak UIImageView *carTypeImageView; // @synthesize carTypeImageView=_carTypeImageView;
@property(nonatomic) __weak UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
- (void).cxx_destruct;
- (void)configSize:(struct CGSize)arg1;
- (void)configCellWithCarTypeModel:(id)arg1;
- (void)awakeFromNib;

@end

