//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface CommentModel : NSObject
{
    int _commentID;
    NSString *_content;
    NSString *_nickName;
    NSString *_fastContent;
    NSString *_insertTime;
    double _star;
    NSString *_imageURL;
    UIImage *_image;
}

@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(nonatomic) double star; // @synthesize star=_star;
@property(copy, nonatomic) NSString *insertTime; // @synthesize insertTime=_insertTime;
@property(nonatomic) int commentID; // @synthesize commentID=_commentID;
@property(copy, nonatomic) NSString *fastContent; // @synthesize fastContent=_fastContent;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)initWithCommentID:(int)arg1 andNickName:(id)arg2 andFastContent:(id)arg3 andContent:(id)arg4 andImageURL:(id)arg5 andInsertTime:(id)arg6 andStar:(double)arg7;

@end

