//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPRequestOperationManager, NSString;

@interface Config : NSObject
{
    AFHTTPRequestOperationManager *httpManager;
    unsigned long long _csvlineCount;
    NSString *_combinationtoken;
}

+ (void)getHomeRedEnvelopeShareInfo;
+ (void)getCityADBannerInfo;
+ (void)getGeneralADBannerInfo;
+ (void)downLoadDowngradeOrderPicture:(id)arg1;
+ (void)getDowngradeOrderInfo;
+ (void)getEventPageInfo;
+ (id)sharedSingleton;
@property(copy, nonatomic) NSString *combinationtoken; // @synthesize combinationtoken=_combinationtoken;
@property(nonatomic) unsigned long long csvlineCount; // @synthesize csvlineCount=_csvlineCount;
- (void).cxx_destruct;
- (void)getToken:(CDUnknownBlockType)arg1;
- (void)getCSVconfigInfo;
- (void)getCityServices;
- (void)getCityServicesWithFinishBlock:(CDUnknownBlockType)arg1;
- (void)saveSysParams:(id)arg1 cityId:(long long)arg2;
- (void)getAppSysParamsWithCityId:(long long)arg1;
- (id)getSysParamsWithCityId:(long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)getADInfoFinishBlock:(CDUnknownBlockType)arg1;
- (void)loadOrderCancelReasons;
- (id)getStationKeywordWithCityId:(id)arg1;
- (void)getStationKeyword;
- (void)setMileageRatio:(double)arg1 timeRatio:(double)arg2;
- (void)getInitParams;
- (id)combinationToken;
- (unsigned long long)csvLineCount;

@end

