//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CoreAnimationEffect : NSObject
{
}

+ (void)animationCameraClose:(id)arg1;
+ (void)animationCameraOpen:(id)arg1;
+ (void)animationRippleEffect:(id)arg1;
+ (void)animationSuckEffect:(id)arg1;
+ (void)animationCubeFromBottom:(id)arg1;
+ (void)animationCubeFromTop:(id)arg1;
+ (void)animationCubeFromRight:(id)arg1;
+ (void)animationCubeFromLeft:(id)arg1;
+ (void)animationFlipFromBottom:(id)arg1;
+ (void)animationFlipFromTop:(id)arg1;
+ (void)animationRotateAndScaleDownUp:(id)arg1;
+ (void)animationRotateAndScaleEffects:(id)arg1;
+ (void)animationMoveRight:(id)arg1;
+ (void)animationMoveLeft:(id)arg1;
+ (void)animationMoveDown:(id)arg1 duration:(double)arg2;
+ (void)animationMoveUp:(id)arg1 duration:(double)arg2;
+ (void)animationPushRight:(id)arg1;
+ (void)animationPushLeft:(id)arg1;
+ (void)animationPushDown:(id)arg1;
+ (void)animationPushUp:(id)arg1;
+ (void)animationCurlDown:(id)arg1;
+ (void)animationCurlUp:(id)arg1;
+ (void)animationFlipFromRigh:(id)arg1;
+ (void)animationFlipFromLeft:(id)arg1;
+ (void)animationEaseOut:(id)arg1;
+ (void)animationEaseIn:(id)arg1;
+ (void)animationRevealFromRight:(id)arg1;
+ (void)animationRevealFromLeft:(id)arg1;
+ (void)animationRevealFromTop:(id)arg1;
+ (void)animationRevealFromBottom:(id)arg1;
+ (void)showAnimationType:(id)arg1 withSubType:(id)arg2 duration:(double)arg3 timingFunction:(id)arg4 view:(id)arg5;

@end

