//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CRSA : NSObject
{
    struct rsa_st *_rsa;
}

+ (id)shareInstance;
- (int)getBlockSizeWithRSA_PADDING_TYPE:(int)arg1;
- (id)decryptByRsa:(id)arg1 withKeyType:(int)arg2 resultEncoding:(int)arg3;
- (id)decryptByRsa:(id)arg1 withKeyType:(int)arg2;
- (id)encryptByRsa:(id)arg1 withKeyType:(int)arg2 resultEncoding:(int)arg3;
- (id)encryptByRsa:(id)arg1 withKeyType:(int)arg2;
- (_Bool)importRSAKeyWithType:(int)arg1;

@end

