//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BMKGeoCodeSearchDelegate.h"

@class BMKReverseGeoCodeResult, CustomBMKGeoCodeSearch;

@protocol CustomBMKGeoCodeSearchDelegate <BMKGeoCodeSearchDelegate>
- (void)onGetReverseGeoCodeResult:(CustomBMKGeoCodeSearch *)arg1 result:(BMKReverseGeoCodeResult *)arg2 errorCode:(int)arg3;
@end

