//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MJRefreshBackFooter.h"

@class NSLayoutConstraint, UIActivityIndicatorView, UILabel, UIView;

@interface CustomMJRefreshBackFooter : MJRefreshBackFooter
{
    UIView *_contentView;
    UILabel *_label;
    UIActivityIndicatorView *_loading;
    double _loadingWidth;
    NSLayoutConstraint *_loadingWidthConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *loadingWidthConstraint; // @synthesize loadingWidthConstraint=_loadingWidthConstraint;
@property(nonatomic) double loadingWidth; // @synthesize loadingWidth=_loadingWidth;
@property(nonatomic) __weak UIActivityIndicatorView *loading; // @synthesize loading=_loading;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
- (void).cxx_destruct;
- (void)setPullingPercent:(double)arg1;
- (void)setState:(long long)arg1;
- (void)scrollViewPanStateDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)placeSubviews;
- (void)layoutSubviews;
- (void)prepare;

@end

