//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class MyPageControl, NSMutableArray, NSString, NSTimer, UIScrollView;

@interface CycleScrollView : UIView <UIScrollViewDelegate>
{
    double scrollViewStartContentOffsetX;
    UIScrollView *_scrollView;
    CDUnknownBlockType _totalPagesCount;
    CDUnknownBlockType _fetchContentViewAtIndex;
    CDUnknownBlockType _scrollAtIndex;
    CDUnknownBlockType _TapActionBlock;
    long long _currentPageIndex;
    long long _totalPageCount;
    NSMutableArray *_contentViews;
    NSTimer *_animationTimer;
    double _animationDuration;
    MyPageControl *_pageControl;
}

@property(retain, nonatomic) MyPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
@property(retain, nonatomic) NSMutableArray *contentViews; // @synthesize contentViews=_contentViews;
@property(nonatomic) long long totalPageCount; // @synthesize totalPageCount=_totalPageCount;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(copy, nonatomic) CDUnknownBlockType TapActionBlock; // @synthesize TapActionBlock=_TapActionBlock;
@property(copy, nonatomic) CDUnknownBlockType scrollAtIndex; // @synthesize scrollAtIndex=_scrollAtIndex;
@property(copy, nonatomic) CDUnknownBlockType fetchContentViewAtIndex; // @synthesize fetchContentViewAtIndex=_fetchContentViewAtIndex;
@property(copy, nonatomic) CDUnknownBlockType totalPagesCount; // @synthesize totalPagesCount=_totalPagesCount;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)contentViewTapAction:(id)arg1;
- (void)animationTimerDidFired:(id)arg1;
- (void)longTapGestureAction:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (long long)getValidNextPageIndexWithPageIndex:(long long)arg1;
- (_Bool)isValidArrayIndex:(long long)arg1;
- (void)setScrollViewContentDataSource;
- (void)configContentViews;
- (void)resumeTimer;
- (void)pauseTimer;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 animationDuration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

