//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface DragButton : UIButton
{
    _Bool _dragEnable;
    _Bool _adsorbEnable;
}

@property(nonatomic) _Bool adsorbEnable; // @synthesize adsorbEnable=_adsorbEnable;
@property(nonatomic) _Bool dragEnable; // @synthesize dragEnable=_dragEnable;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

