//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class TQStarRatingView, UIImageView, UILabel;

@interface DriverCommentCell : UITableViewCell
{
    UIImageView *_headImageView;
    UILabel *_userNameLabel;
    UILabel *_fastCommentLabel;
    TQStarRatingView *_starRatingView;
    UILabel *_commentLabel;
    UILabel *_dateLabel;
}

@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) TQStarRatingView *starRatingView; // @synthesize starRatingView=_starRatingView;
@property(retain, nonatomic) UILabel *fastCommentLabel; // @synthesize fastCommentLabel=_fastCommentLabel;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (double)getCommentHeight:(id)arg1;
- (double)getCellHeight:(id)arg1;
- (void)setDataWithCommentModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

