//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AFHTTPRequestOperationManager, NSLayoutConstraint, NSString, UILabel, UITableView, UIView;

@interface EnterpriseBalanceViewController : SuperViewController <UITableViewDataSource, UITableViewDelegate>
{
    AFHTTPRequestOperationManager *_httpManager;
    _Bool isLoadDataSuccess;
    UITableView *_tableView;
    UIView *_headerView;
    UIView *_moenyView;
    UILabel *_moenyLabel;
    UILabel *_remarkLabel;
    NSString *_descriptionText;
    NSString *_enterpriseDescriptionURL;
    NSLayoutConstraint *_moenyLabelTopConstraint;
}

+ (void)initEnterpriseBalanceViewController:(id)arg1;
@property(nonatomic) __weak NSLayoutConstraint *moenyLabelTopConstraint; // @synthesize moenyLabelTopConstraint=_moenyLabelTopConstraint;
@property(copy, nonatomic) NSString *enterpriseDescriptionURL; // @synthesize enterpriseDescriptionURL=_enterpriseDescriptionURL;
@property(copy, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
@property(nonatomic) __weak UILabel *remarkLabel; // @synthesize remarkLabel=_remarkLabel;
@property(nonatomic) __weak UILabel *moenyLabel; // @synthesize moenyLabel=_moenyLabel;
@property(nonatomic) __weak UIView *moenyView; // @synthesize moenyView=_moenyView;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)enterpriseBalanceToRechargeDescriptionAction;
- (void)addRightBarButtonItem;
- (void)getEnterpriseBalanceData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

