//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class NSTimer, UIButton, UIImage, UIImageView;

@interface EventViewController : SuperViewController
{
    NSTimer *_eventImageTimer;
    long long iTime;
    UIImage *_image;
    UIButton *_timerBtn;
    UIImageView *_eventImageView;
}

@property(retain, nonatomic) UIImageView *eventImageView; // @synthesize eventImageView=_eventImageView;
@property(nonatomic) __weak UIButton *timerBtn; // @synthesize timerBtn=_timerBtn;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)timerBtnClicked:(id)arg1;
- (void)eventImageViewTapAction;
- (void)dismissEventImage;
- (void)showEventImageAction;
- (void)removeTimer;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

