//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIPopoverMenuViewController.h"

@interface FareSelectMenuViewController : UIPopoverMenuViewController
{
}

- (void)dismiss;
- (_Bool)showFareInfo:(id)arg1 fare:(id)arg2 inView:(id)arg3 selectBlock:(CDUnknownBlockType)arg4;

@end

