//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface FeeDataManager : NSObject
{
    NSDictionary *feedataDic;
    int currentCityId;
    double _mileageRatio;
    double _timeRatio;
}

+ (id)sharedSingleton;
@property(nonatomic) double timeRatio; // @synthesize timeRatio=_timeRatio;
@property(nonatomic) double mileageRatio; // @synthesize mileageRatio=_mileageRatio;
- (void).cxx_destruct;
- (id)toKey:(int)arg1 carTypeId:(int)arg2 serviceTypeId:(int)arg3;
- (void)downFeesCityId:(long long)arg1 finish:(CDUnknownBlockType)arg2;
- (id)getChargeStandard:(int)arg1 carTypeId:(int)arg2 serviceTypeId:(int)arg3;
- (id)init;

@end

