//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BMKPlanNode, NSDate;

@interface FeeSearch : NSObject
{
    int _serviceType;
    int _carType;
    NSDate *_startTime;
    BMKPlanNode *_start;
    BMKPlanNode *_end;
}

@property(nonatomic) int carType; // @synthesize carType=_carType;
@property(nonatomic) int serviceType; // @synthesize serviceType=_serviceType;
@property(retain, nonatomic) BMKPlanNode *end; // @synthesize end=_end;
@property(retain, nonatomic) BMKPlanNode *start; // @synthesize start=_start;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)initWithStartPoint:(id)arg1 andEndPoint:(id)arg2 andStartTime:(id)arg3 andServiceType:(int)arg4;

@end

