//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<FileDownloadManagerDelegate>;

@interface FileDownloadManager : NSObject
{
    NSObject<FileDownloadManagerDelegate> *_delegate;
}

+ (id)shareManager;
@property(retain, nonatomic) NSObject<FileDownloadManagerDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)addSkipBackupAttributeToItemAtURL:(id)arg1;
- (id)md5NSData:(id)arg1;
- (_Bool)writeImage:(id)arg1 toFileAtPath:(id)arg2;
- (void)startIconDownload:(id)arg1 downloadHtm:(id)arg2 downloadPath:(id)arg3;

@end

