//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIImageView, UILabel, UIView;

@interface GiftTableViewCell : UITableViewCell
{
    _Bool _isFold;
    UILabel *_statusLabel;
    UILabel *_unfoldNameLabel;
    UILabel *_foldNameLabel;
    UILabel *_timeLabel;
    UILabel *_vLabel;
    UIView *_statusBgView;
    UIImageView *_arrowImageView;
    UIView *_bgBarcodeView;
    UIImageView *_barcodeImageView;
    UIView *_reloadBgView;
    NSString *_barCodeUrl;
}

@property(retain, nonatomic) NSString *barCodeUrl; // @synthesize barCodeUrl=_barCodeUrl;
@property(nonatomic) _Bool isFold; // @synthesize isFold=_isFold;
@property(retain, nonatomic) UIView *reloadBgView; // @synthesize reloadBgView=_reloadBgView;
@property(retain, nonatomic) UIImageView *barcodeImageView; // @synthesize barcodeImageView=_barcodeImageView;
@property(retain, nonatomic) UIView *bgBarcodeView; // @synthesize bgBarcodeView=_bgBarcodeView;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIView *statusBgView; // @synthesize statusBgView=_statusBgView;
@property(retain, nonatomic) UILabel *vLabel; // @synthesize vLabel=_vLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *foldNameLabel; // @synthesize foldNameLabel=_foldNameLabel;
@property(retain, nonatomic) UILabel *unfoldNameLabel; // @synthesize unfoldNameLabel=_unfoldNameLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void).cxx_destruct;
- (void)reloadBtnDidClicked:(id)arg1;
- (void)setupLoadBarcode;
- (void)setDataWithGift:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

