//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GPSLocationData : NSObject
{
    double _time;
    struct CLLocationCoordinate2D _location;
}

@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) struct CLLocationCoordinate2D location; // @synthesize location=_location;

@end

