//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JGHUD : NSObject
{
}

+ (void)progressHUD:(id)arg1 didDismissFromView:(id)arg2;
+ (void)progressHUD:(id)arg1 willDismissFromView:(id)arg2;
+ (void)progressHUD:(id)arg1 didPresentInView:(id)arg2;
+ (void)progressHUD:(id)arg1 willPresentInView:(id)arg2;
+ (id)showPayStatusInView:(id)arg1 text:(id)arg2 payStatus:(int)arg3;
+ (id)hideHUD;
+ (id)showInView:(id)arg1 text:(id)arg2 dismissAfterDelay:(double)arg3 showIndicatorView:(_Bool)arg4;
+ (id)showInView:(id)arg1 text:(id)arg2 dismissAfterDelay:(double)arg3;
+ (id)showInView:(id)arg1 text:(id)arg2 showIndicatorView:(_Bool)arg3;
+ (id)showInView:(id)arg1 text:(id)arg2;
+ (id)showInView:(id)arg1;
+ (id)showText:(id)arg1 autoHideInView:(id)arg2;
+ (id)showText:(id)arg1 dismissAfterDelay:(double)arg2;
+ (id)showText:(id)arg1;

@end

