//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JGProgressHUDIndicatorView.h"

@class UIColor;

@interface JGProgressHUDPieIndicatorView : JGProgressHUDIndicatorView
{
    UIColor *_color;
    UIColor *_fillColor;
}

+ (Class)layerClass;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;
- (id)initWithContentView:(id)arg1;
- (id)initWithHUDStyle:(unsigned long long)arg1;

@end

