//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface JGProgressHUDIndicatorView : UIView
{
    _Bool _accessibilityUpdateScheduled;
    float _progress;
    UIView *_contentView;
}

+ (void)runBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) float progress; // @synthesize progress=_progress;
- (void).cxx_destruct;
- (void)setProgress:(float)arg1 animated:(_Bool)arg2;
- (void)updateAccessibility;
- (void)updateAccessibilityIfNeeded;
- (void)setNeedsAccessibilityUpdate;
- (id)initWithContentView:(id)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

