//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class LeftViewTableViewCellData, NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface LeftViewTableViewCell : UITableViewCell
{
    LeftViewTableViewCellData *_data;
    UIImageView *_iconImageView;
    UIImageView *_badgeImageView;
    UIImageView *_newfunctionImageView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_numberLabel;
    UIView *_separatorLineView;
    UIImageView *_rightArrowImageView;
    NSLayoutConstraint *_separatorLineHeightContraint;
    NSLayoutConstraint *_iconImageViewHeightConstraint;
    NSLayoutConstraint *_iconImageViewWidthConstraint;
    NSLayoutConstraint *_titleLabelLeftConstraint;
    NSLayoutConstraint *_iconImageViewLeftConstraint;
    NSLayoutConstraint *_rightArrowImageLeftConstraint;
    NSLayoutConstraint *_rightArrowImageWidthConstraint;
    NSLayoutConstraint *_rightArrowImageHeightConstraint;
    NSLayoutConstraint *_numberLabelWidthConstraint;
    NSLayoutConstraint *_badgeImageHeightConstraint;
    NSLayoutConstraint *_badgeImageWidthConstraint;
    NSLayoutConstraint *_badgeImageRightMarginConstraint;
    NSLayoutConstraint *_badgeImageTopMarginConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *badgeImageTopMarginConstraint; // @synthesize badgeImageTopMarginConstraint=_badgeImageTopMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *badgeImageRightMarginConstraint; // @synthesize badgeImageRightMarginConstraint=_badgeImageRightMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *badgeImageWidthConstraint; // @synthesize badgeImageWidthConstraint=_badgeImageWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *badgeImageHeightConstraint; // @synthesize badgeImageHeightConstraint=_badgeImageHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *numberLabelWidthConstraint; // @synthesize numberLabelWidthConstraint=_numberLabelWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *rightArrowImageHeightConstraint; // @synthesize rightArrowImageHeightConstraint=_rightArrowImageHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *rightArrowImageWidthConstraint; // @synthesize rightArrowImageWidthConstraint=_rightArrowImageWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *rightArrowImageLeftConstraint; // @synthesize rightArrowImageLeftConstraint=_rightArrowImageLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *iconImageViewLeftConstraint; // @synthesize iconImageViewLeftConstraint=_iconImageViewLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelLeftConstraint; // @synthesize titleLabelLeftConstraint=_titleLabelLeftConstraint;
@property(nonatomic) __weak NSLayoutConstraint *iconImageViewWidthConstraint; // @synthesize iconImageViewWidthConstraint=_iconImageViewWidthConstraint;
@property(nonatomic) __weak NSLayoutConstraint *iconImageViewHeightConstraint; // @synthesize iconImageViewHeightConstraint=_iconImageViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *separatorLineHeightContraint; // @synthesize separatorLineHeightContraint=_separatorLineHeightContraint;
@property(nonatomic) __weak UIImageView *rightArrowImageView; // @synthesize rightArrowImageView=_rightArrowImageView;
@property(nonatomic) __weak UIView *separatorLineView; // @synthesize separatorLineView=_separatorLineView;
@property(nonatomic) __weak UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(nonatomic) __weak UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *newfunctionImageView; // @synthesize newfunctionImageView=_newfunctionImageView;
@property(nonatomic) __weak UIImageView *badgeImageView; // @synthesize badgeImageView=_badgeImageView;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) LeftViewTableViewCellData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)setAttributedTextWithString:(id)arg1 rang:(struct _NSRange)arg2 colour:(id)arg3;
- (void)clearNewFunction;
- (void)showNewFunction;
- (void)clearBadge;
- (void)showBadge;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)getFontWithSize:(double)arg1;
- (void)awakeFromNib;
- (void)dealloc;

@end

