//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, NSMutableArray, UIView;

@interface ListOfInvoicedTableViewController : SuperTableViewController
{
    NSMutableArray *_writedInvoiceArray;
    int _writedTableViewCurrentPageNO;
    AFHTTPRequestOperationManager *_httpManager;
    UIView *_headerView;
}

@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)backBarButtonAction:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setWritedBackground;
- (void)loadWritedTableViewWithIsHeaderRefresh:(_Bool)arg1;
- (void)writedTableViewFooterRefreshAction;
- (void)writedTableViewHeaderRefreshAction;
- (void)setupRefresh;
- (void)setupViewData;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

