//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLBaseModel.h"

@class NSString;

@interface LLGoods : LLBaseModel
{
    NSString *_oid_goodsitem;
    NSString *_name_goods;
    NSString *_price_goods;
    NSString *_desc_goods;
    NSString *_num_goods;
    NSString *_oldPrice;
    NSString *_type_goodsbill;
    NSString *_url_goods;
    NSString *_tran_id;
}

@property(retain, nonatomic) NSString *tran_id; // @synthesize tran_id=_tran_id;
@property(retain, nonatomic) NSString *url_goods; // @synthesize url_goods=_url_goods;
@property(retain, nonatomic) NSString *type_goodsbill; // @synthesize type_goodsbill=_type_goodsbill;
@property(retain, nonatomic) NSString *oldPrice; // @synthesize oldPrice=_oldPrice;
@property(retain, nonatomic) NSString *num_goods; // @synthesize num_goods=_num_goods;
@property(retain, nonatomic) NSString *desc_goods; // @synthesize desc_goods=_desc_goods;
@property(retain, nonatomic) NSString *price_goods; // @synthesize price_goods=_price_goods;
@property(retain, nonatomic) NSString *name_goods; // @synthesize name_goods=_name_goods;
@property(retain, nonatomic) NSString *oid_goodsitem; // @synthesize oid_goodsitem=_oid_goodsitem;
- (void).cxx_destruct;
- (id)initWithAttributes:(id)arg1;

@end

