//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocation, CLLocationManager, CLPlacemark, NSDate, NSString;

@interface LLLocationHelper : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *_manager;
    CLLocation *_checkinLocation;
    CLPlacemark *_placeMark;
    NSDate *_lastUpdateTime;
    CDUnknownBlockType _completionHandle;
}

+ (void)updateLocationWithCompletionHandle:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType completionHandle; // @synthesize completionHandle=_completionHandle;
@property(retain, nonatomic) NSDate *lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property(retain, nonatomic) CLPlacemark *placeMark; // @synthesize placeMark=_placeMark;
@property(retain, nonatomic) CLLocation *checkinLocation; // @synthesize checkinLocation=_checkinLocation;
@property(retain, nonatomic) CLLocationManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)areaOfPlacemark:(id)arg1;
- (void)reverseGeocoding;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)locatingWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

