//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LLPaymentEncrypt : NSObject
{
}

+ (id)signHmacString:(id)arg1 withKey:(id)arg2;
+ (id)decryptData:(id)arg1 withKey:(id)arg2;
+ (id)nonceData:(id)arg1;
+ (id)encryptB64String:(id)arg1 withKey:(id)arg2 withNonce:(id)arg3;
+ (id)getRandomString:(int)arg1;
+ (id)base64Encode:(id)arg1;
+ (id)encrypt:(id)arg1;
+ (id)publicKeyVer;
+ (id)publicKey;
+ (void)saveKey:(id)arg1;

@end

