//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLRestClient, NSDictionary, NSString;

@interface LLRestEngine : NSObject
{
    int waitingCount;
    _Bool _testMode;
    NSString *_user_id;
    NSString *_oid_partner;
    NSString *_platform;
    LLRestClient *_releaseServer;
    LLRestClient *_testServer;
    LLRestClient *_testSecureServer;
    LLRestClient *_cmdServer;
    NSDictionary *_funcInfoDic;
}

+ (void)postFormWithCmd:(id)arg1 progress:(CDUnknownBlockType)arg2;
+ (void)sendCommandRequest:(id)arg1;
+ (void)netArrorAlert:(id)arg1;
+ (void)hideWaiting;
+ (void)showWaiting:(id)arg1;
+ (id)sharedInstance;
@property(nonatomic, getter=isTestMode) _Bool testMode; // @synthesize testMode=_testMode;
@property(retain, nonatomic) NSDictionary *funcInfoDic; // @synthesize funcInfoDic=_funcInfoDic;
@property(retain, nonatomic) LLRestClient *cmdServer; // @synthesize cmdServer=_cmdServer;
@property(retain, nonatomic) LLRestClient *testSecureServer; // @synthesize testSecureServer=_testSecureServer;
@property(retain, nonatomic) LLRestClient *testServer; // @synthesize testServer=_testServer;
@property(retain, nonatomic) LLRestClient *releaseServer; // @synthesize releaseServer=_releaseServer;
@property(retain, nonatomic) NSString *platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSString *oid_partner; // @synthesize oid_partner=_oid_partner;
@property(retain, nonatomic) NSString *user_id; // @synthesize user_id=_user_id;
- (void).cxx_destruct;
- (void)sendCommand:(id)arg1;
- (id)init;
- (void)dealloc;

@end

