//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSData, NSError, NSHTTPURLResponse, NSOutputStream, NSRecursiveLock, NSSet, NSString, NSURLConnection, NSURLCredential, NSURLRequest;

@interface LLURLConnectOperation : NSOperation <NSURLConnectionDelegate, NSURLConnectionDataDelegate>
{
    _Bool _allowsInvalidSSLCertificate;
    int _SSLPinningMode;
    int _state;
    NSOutputStream *_outputStream;
    NSURLCredential *_credential;
    NSData *_responseData;
    NSString *_responseString;
    unsigned long long _responseStringEncoding;
    NSURLRequest *_request;
    NSHTTPURLResponse *_response;
    NSURLConnection *_urlConnection;
    NSSet *_runLoopModes;
    id _responseJSON;
    NSError *_JSONError;
    NSError *_HTTPError;
    unsigned long long _JSONReadingOptions;
    NSRecursiveLock *_lock;
    CDUnknownBlockType _uploadProgress;
}

+ (id)acceptableStatusCodes;
+ (id)acceptableContentTypes;
+ (id)pinnedPublicKeys;
+ (id)pinnedCertificates;
+ (id)networkRequestThread;
+ (void)networkRequestThreadEntryPoint;
@property(copy, nonatomic) CDUnknownBlockType uploadProgress; // @synthesize uploadProgress=_uploadProgress;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(nonatomic) unsigned long long JSONReadingOptions; // @synthesize JSONReadingOptions=_JSONReadingOptions;
@property(retain, nonatomic) NSError *HTTPError; // @synthesize HTTPError=_HTTPError;
@property(retain, nonatomic) NSError *JSONError; // @synthesize JSONError=_JSONError;
@property(retain, nonatomic) id responseJSON; // @synthesize responseJSON=_responseJSON;
@property(retain, nonatomic) NSSet *runLoopModes; // @synthesize runLoopModes=_runLoopModes;
@property(nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) NSURLConnection *urlConnection; // @synthesize urlConnection=_urlConnection;
@property(retain, nonatomic) NSHTTPURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(nonatomic) unsigned long long responseStringEncoding; // @synthesize responseStringEncoding=_responseStringEncoding;
@property(retain, nonatomic) NSString *responseString; // @synthesize responseString=_responseString;
@property(retain, nonatomic) NSData *responseData; // @synthesize responseData=_responseData;
@property(nonatomic) int SSLPinningMode; // @synthesize SSLPinningMode=_SSLPinningMode;
@property(retain, nonatomic) NSURLCredential *credential; // @synthesize credential=_credential;
@property(nonatomic) _Bool allowsInvalidSSLCertificate; // @synthesize allowsInvalidSSLCertificate=_allowsInvalidSSLCertificate;
- (void).cxx_destruct;
- (void)setUploadProgressBlock:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;
- (_Bool)connectionShouldUseCredentialStorage:(id)arg1;
- (void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2;
- (void)resume;
- (_Bool)isPaused;
- (void)pause;
- (void)cancel;
- (void)operationDidStart;
- (void)start;
- (_Bool)isReady;
- (_Bool)isConcurrent;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)hasAcceptableContentType;
- (_Bool)hasAcceptableStatusCode;
- (id)error;
- (void)setConnectionSuccess:(CDUnknownBlockType)arg1 faildure:(CDUnknownBlockType)arg2;
- (void)setCompletionBlock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

