//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BMKPoiSearchDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AFHTTPRequestOperationManager, BMKMapView, BMKPoiSearch, CADisplayLink, MapCarPaoPaoView, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, NSTimer, UIImage, UITapGestureRecognizer;

@interface MapCarActionView : UIView <BMKPoiSearchDelegate, UIGestureRecognizerDelegate>
{
    NSObject<OS_dispatch_queue> *queue;
    AFHTTPRequestOperationManager *manager;
    BMKPoiSearch *_poiSearch;
    struct CLLocationCoordinate2D _lastCenterLocation;
    MapCarPaoPaoView *_paopaoView;
    UITapGestureRecognizer *singleTap;
    _Bool _isBusy;
    _Bool _showQiPao;
    _Bool _enterBackground;
    _Bool _addedObservers;
    _Bool _near;
    _Bool _isGettingCarTypeInstantIconInfo;
    NSMutableDictionary *_mapCars;
    BMKMapView *_mapView;
    long long _orderID;
    long long _driverID;
    NSMutableArray *_fakeMapCars;
    NSMutableArray *_fakeDrivers;
    NSMutableArray *_dirverIds;
    CADisplayLink *_frameTimer;
    NSTimer *_loadTimer;
    UIImage *_defaultCarImage;
    UIImage *_outsideCarImage;
    UIImage *_outsideCarArrowImage;
    NSMutableDictionary *_carTypeInstantIconInfo;
    NSMutableArray *_downLoaddingURLs;
    struct CLLocationCoordinate2D _centerCoordinate;
    struct CGRect _visibleRect;
    struct CGRect _outsideCarImageDrawRect;
}

@property(nonatomic) _Bool isGettingCarTypeInstantIconInfo; // @synthesize isGettingCarTypeInstantIconInfo=_isGettingCarTypeInstantIconInfo;
@property(retain, nonatomic) NSMutableArray *downLoaddingURLs; // @synthesize downLoaddingURLs=_downLoaddingURLs;
@property(retain, nonatomic) NSMutableDictionary *carTypeInstantIconInfo; // @synthesize carTypeInstantIconInfo=_carTypeInstantIconInfo;
@property(nonatomic) struct CGRect outsideCarImageDrawRect; // @synthesize outsideCarImageDrawRect=_outsideCarImageDrawRect;
@property(retain, nonatomic) UIImage *outsideCarArrowImage; // @synthesize outsideCarArrowImage=_outsideCarArrowImage;
@property(retain, nonatomic) UIImage *outsideCarImage; // @synthesize outsideCarImage=_outsideCarImage;
@property(retain, nonatomic) UIImage *defaultCarImage; // @synthesize defaultCarImage=_defaultCarImage;
@property(retain, nonatomic) NSTimer *loadTimer; // @synthesize loadTimer=_loadTimer;
@property(retain, nonatomic) CADisplayLink *frameTimer; // @synthesize frameTimer=_frameTimer;
@property(retain) NSMutableArray *dirverIds; // @synthesize dirverIds=_dirverIds;
@property(retain) NSMutableArray *fakeDrivers; // @synthesize fakeDrivers=_fakeDrivers;
@property(retain) NSMutableArray *fakeMapCars; // @synthesize fakeMapCars=_fakeMapCars;
@property(nonatomic) struct CLLocationCoordinate2D centerCoordinate; // @synthesize centerCoordinate=_centerCoordinate;
@property(nonatomic) long long driverID; // @synthesize driverID=_driverID;
@property(nonatomic) long long orderID; // @synthesize orderID=_orderID;
@property(nonatomic, getter=isNear) _Bool near; // @synthesize near=_near;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) _Bool addedObservers; // @synthesize addedObservers=_addedObservers;
@property(nonatomic) _Bool enterBackground; // @synthesize enterBackground=_enterBackground;
@property(nonatomic) _Bool showQiPao; // @synthesize showQiPao=_showQiPao;
@property(retain) NSMutableDictionary *mapCars; // @synthesize mapCars=_mapCars;
@property(nonatomic) _Bool isBusy; // @synthesize isBusy=_isBusy;
@property(nonatomic) struct CGRect visibleRect; // @synthesize visibleRect=_visibleRect;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)onGetPoiResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)gestureAction:(id)arg1;
- (struct CGPoint)getRotatePoint:(struct CGPoint)arg1 centerPoint:(struct CGPoint)arg2 angle:(double)arg3;
- (_Bool)isSameLD:(double)arg1 LD:(double)arg2;
- (void)dismissMapCarPaoPao;
- (void)showMapCarPaoPao:(id)arg1;
- (id)getMapCarByPoint:(struct CGPoint)arg1;
- (void)drawOutsideMapCarWithContext:(struct CGContext *)arg1 mapCar:(id)arg2;
- (void)drawCar:(struct CGContext *)arg1 mapCar:(id)arg2 inRect:(struct CGRect)arg3;
- (void)drawRect:(struct CGRect)arg1;
- (void)displayUpdate:(id)arg1;
- (id)parseGPSLocationsFromString:(id)arg1 lastGPS:(id)arg2;
- (double)getDistanceBetweenFirstPGS:(id)arg1 andSecondGPS:(id)arg2;
- (double)getSpeedBetweenFirstGPS:(id)arg1 andSecondGPS:(id)arg2;
- (id)getUsefulGPSLocations:(id)arg1 mapCar:(id)arg2;
- (void)parseDriver:(id)arg1 driverIds:(id *)arg2;
- (void)searchNearBusStation;
- (void)getLocations:(id)arg1;
- (void)clearMapcars;
- (void)stopAction;
- (void)initDatas;
- (void)startActionWithMapView:(id)arg1 driverID:(long long)arg2;
- (void)startActionWithMapView:(id)arg1 centerCoordinate:(struct CLLocationCoordinate2D)arg2;
- (void)startActionWithMapView:(id)arg1 centerCoordinate:(struct CLLocationCoordinate2D)arg2 orderID:(long long)arg3;
- (void)appEnterForeground;
- (void)appEnterBackground;
- (void)addObservers;
- (void)removeObservers;
- (void)loadImageByCarTypeID:(id)arg1 urlString:(id)arg2 canRotate:(id)arg3;
- (void)getCarTypeInstantIconInfo;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

