//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MapViewController, NSString;

@interface MapViewOrderEntrance : NSObject
{
    unsigned long long _serviceType;
    NSString *_currentCityName;
    MapViewController *_mapViewController;
}

@property(nonatomic) __weak MapViewController *mapViewController; // @synthesize mapViewController=_mapViewController;
@property(copy, nonatomic) NSString *currentCityName; // @synthesize currentCityName=_currentCityName;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
- (void).cxx_destruct;
- (void)startWithService:(unsigned long long)arg1 isSysPatemeter:(_Bool)arg2;
- (void)cherkIsCityOpenedService:(unsigned long long)arg1 isSysPatemeter:(_Bool)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)cherkSysParamsWithServiceType:(unsigned long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)cherkLoginStatusWithServiceType:(unsigned long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)startAnOrderWithServiceType:(unsigned long long)arg1;
- (id)initWithServiceType:(unsigned long long)arg1;

@end

