//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class CLLocation, NSString;

@interface MatchDriver : NSObject <NSCoding, NSCopying>
{
    NSString *_colour;
    NSString *_distance;
    NSString *_travelTime;
    NSString *_headPicUrl;
    NSString *_carBrand;
    NSString *_carType;
    double _estimateMoney;
    CLLocation *_location;
    NSString *_driverName;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(retain, nonatomic) NSString *driverName; // @synthesize driverName=_driverName;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) double estimateMoney; // @synthesize estimateMoney=_estimateMoney;
@property(retain, nonatomic) NSString *carType; // @synthesize carType=_carType;
@property(retain, nonatomic) NSString *carBrand; // @synthesize carBrand=_carBrand;
@property(retain, nonatomic) NSString *headPicUrl; // @synthesize headPicUrl=_headPicUrl;
@property(retain, nonatomic) NSString *travelTime; // @synthesize travelTime=_travelTime;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(retain, nonatomic) NSString *colour; // @synthesize colour=_colour;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)objectOrNilForKey:(id)arg1 fromDictionary:(id)arg2;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

