//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "UIActionSheetDelegate.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UITextFieldDelegate.h"

@class AFHTTPRequestOperationManager, NSString, UIButton, UIImage, UILabel, UITextField, UIView;

@interface ModifyViewController : BaseViewController <UIActionSheetDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UITextFieldDelegate>
{
    AFHTTPRequestOperationManager *httpManager;
    NSString *_updateHeadUrl;
    UIImage *successImage;
    UIButton *_headPic;
    UILabel *_phoneLbl;
    UITextField *_userTextField;
    UIView *_userView;
    UIView *_phoneView;
    UIButton *_manBtn;
    UIButton *_womanBtn;
}

@property(nonatomic) __weak UIButton *womanBtn; // @synthesize womanBtn=_womanBtn;
@property(nonatomic) __weak UIButton *manBtn; // @synthesize manBtn=_manBtn;
@property(nonatomic) __weak UIView *phoneView; // @synthesize phoneView=_phoneView;
@property(nonatomic) __weak UIView *userView; // @synthesize userView=_userView;
@property(nonatomic) __weak UITextField *userTextField; // @synthesize userTextField=_userTextField;
@property(nonatomic) __weak UILabel *phoneLbl; // @synthesize phoneLbl=_phoneLbl;
@property(nonatomic) __weak UIButton *headPic; // @synthesize headPic=_headPic;
- (void).cxx_destruct;
- (void)hideKeyboard;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)doModify;
- (void)modifyBtn:(id)arg1;
- (void)sexBtn:(id)arg1;
- (void)headPicBtn:(id)arg1;
- (void)backBarButtonAction;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)uploadPhotoHeadWithImage:(id)arg1;
- (void)showImagePickerWithSourceType:(long long)arg1;
- (void)womanBtn:(id)arg1;
- (void)manBtn:(id)arg1;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

