//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class NSMutableArray, UITableView;

@interface MoreTableViewController : SuperViewController
{
    NSMutableArray *_leftViewTableViewDatas;
    UITableView *_tableView;
}

+ (void)initMoreViewInTargetViewController:(id)arg1;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)goSettingAction:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)quitEnterprise;
- (void)callService;
- (void)goFeekBack;
- (void)goCleanCache;
- (void)goDriverCollection;
- (void)goValuationViewController;
- (void)goGuideViewController;
- (void)goAboutViewController;
- (void)goQuestions;
- (void)goGift;
- (void)goNotifyCenter;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)initCellDatas;
- (void)setupSettingButton;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

@end

