//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel;

@interface MyPointViewController : UIViewController
{
    UILabel *_pointLabel;
}

@property(nonatomic) __weak UILabel *pointLabel; // @synthesize pointLabel=_pointLabel;
- (void).cxx_destruct;
- (void)backBarButtonAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

