//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MapViewController, NSArray, NSString;

@interface NearByCarsDetector : NSObject
{
    NSArray *_carTypesArray;
    MapViewController *_mapViewController;
    NSString *_individuationCarTypeString;
    NSArray *_enterpriseLimitCarTypes;
}

@property(retain, nonatomic) NSArray *enterpriseLimitCarTypes; // @synthesize enterpriseLimitCarTypes=_enterpriseLimitCarTypes;
@property(copy, nonatomic) NSString *individuationCarTypeString; // @synthesize individuationCarTypeString=_individuationCarTypeString;
@property(nonatomic) __weak MapViewController *mapViewController; // @synthesize mapViewController=_mapViewController;
@property(retain, nonatomic) NSArray *carTypesArray; // @synthesize carTypesArray=_carTypesArray;
- (void).cxx_destruct;
- (void)setDefaultCarTypes;
- (void)limitCarType;
- (void)getIndividuationCarTypeWithServiceType:(unsigned long long)arg1;
- (void)loadCarTypes:(unsigned long long)arg1 date:(id)arg2 atLeastGetOneDay:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;

@end

