//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface NewAboutViewController : SuperViewController
{
    int _agreementType;
    NSString *_agreementTitle;
    struct UIEdgeInsets separatorInset;
    UIImageView *_logo;
    UIView *_centerView;
    UIView *_bottomView;
    UIButton *_serviceNumBtn;
    UITableView *_tableView;
    UIView *_footerView;
    UILabel *_versionLabel;
}

@property(retain, nonatomic) UILabel *versionLabel; // @synthesize versionLabel=_versionLabel;
@property(nonatomic) __weak UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIButton *serviceNumBtn; // @synthesize serviceNumBtn=_serviceNumBtn;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *centerView; // @synthesize centerView=_centerView;
@property(retain, nonatomic) UIImageView *logo; // @synthesize logo=_logo;
- (void).cxx_destruct;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)callButtonAction:(id)arg1;
- (void)ruleButtonAction:(id)arg1;
- (void)payAuthorizationAction:(id)arg1;
- (void)PrivacyAgreementAction:(id)arg1;
- (void)registerAgreementAction:(id)arg1;
- (void)serviceAgreementAction:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)viewDidLayoutSubviews;
- (void)setupServiceNumber;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

