//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIButton, UIImageView;

@interface NewBaseViewController : UIViewController
{
    _Bool _isExtendLayout;
    _Bool _statusBarHidden;
    _Bool _changeStatusBarAnimated;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UIImageView *_leftButtonBadge;
    UIImageView *_rightButtonBadge;
    long long _statusBarStyle;
}

@property(nonatomic) _Bool changeStatusBarAnimated; // @synthesize changeStatusBarAnimated=_changeStatusBarAnimated;
@property(nonatomic) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(nonatomic) _Bool isExtendLayout; // @synthesize isExtendLayout=_isExtendLayout;
@property(retain, nonatomic) UIImageView *rightButtonBadge; // @synthesize rightButtonBadge=_rightButtonBadge;
@property(retain, nonatomic) UIImageView *leftButtonBadge; // @synthesize leftButtonBadge=_leftButtonBadge;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)initializeSelfVCSetting;
- (void)hideNavigationBar:(_Bool)arg1 animated:(_Bool)arg2;
- (void)changeStatusBarStyle:(long long)arg1 statusBarHidden:(_Bool)arg2 changeStatusBarAnimated:(_Bool)arg3;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)setNavgationBarLineHidden:(_Bool)arg1;
- (void)backBarBtnClicked:(id)arg1;
- (void)rightBtnClicked:(id)arg1;
- (void)setRightItemWithObj:(id)arg1;
- (void)setBackBarItemWithObj:(id)arg1;
- (void)setDefaultBackBarItem;
- (void)setTitle:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

