//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface NewDriverDetailCell : UITableViewCell
{
    UILabel *_carTypeLabel;
    UIImageView *_carTypeImageView;
    UIImageView *_carTypeIconImage;
}

@property(nonatomic) __weak UIImageView *carTypeIconImage; // @synthesize carTypeIconImage=_carTypeIconImage;
@property(nonatomic) __weak UIImageView *carTypeImageView; // @synthesize carTypeImageView=_carTypeImageView;
@property(nonatomic) __weak UILabel *carTypeLabel; // @synthesize carTypeLabel=_carTypeLabel;
- (void).cxx_destruct;
- (void)setDataWithDriver:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

