//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Compare)
- (_Bool)isToday;
- (id)intervalToNow;
- (id)intervalToDate:(id)arg1;
- (_Bool)isGreaterOrEqualToDate:(id)arg1;
- (_Bool)isLessOrEqualToDate:(id)arg1;
- (_Bool)isGreaterDate:(id)arg1;
- (_Bool)isLessDate:(id)arg1;
- (_Bool)isEqualToTime:(id)arg1;
- (_Bool)isEqualToDay:(id)arg1;
@end

