//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Category)
+ (id)timestampSecond;
+ (id)timestampMillisecond;
- (id)theme;
- (id)cacheAppend;
- (id)documentAppend;
- (struct CGSize)textSize:(id)arg1 withWidth:(double)arg2;
- (id)toJSONObject;
- (id)toUTF8Data;
@end

