//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface OperationQueueManager : NSObject
{
    _Bool _loadSysPetemeterSuccess;
    _Bool _loadCityServicesSuccess;
    NSOperationQueue *_loadingSysPatemeterOperations;
    NSOperationQueue *_loadingCityServicesOperations;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareManager;
@property(retain) NSOperationQueue *loadingCityServicesOperations; // @synthesize loadingCityServicesOperations=_loadingCityServicesOperations;
@property(retain) NSOperationQueue *loadingSysPatemeterOperations; // @synthesize loadingSysPatemeterOperations=_loadingSysPatemeterOperations;
@property(getter=isLoadCityServicesSuccess) _Bool loadCityServicesSuccess; // @synthesize loadCityServicesSuccess=_loadCityServicesSuccess;
@property(getter=isLoadSysPetemeterSuccess) _Bool loadSysPetemeterSuccess; // @synthesize loadSysPetemeterSuccess=_loadSysPetemeterSuccess;
- (void).cxx_destruct;
- (void)cleartCityServicesOperationQueue;
- (void)waitCityServicesLoadOverWithBlock:(CDUnknownBlockType)arg1;
- (void)loadCityServicesWithBlock:(CDUnknownBlockType)arg1;
- (void)clearSysPatemeterOperationQueue;
- (void)waitSystemPatametersLoadOverWithBlock:(CDUnknownBlockType)arg1;
- (void)loadSystemPatametersWithBlock:(CDUnknownBlockType)arg1;
@property(readonly, getter=isLoadingCityServices) _Bool loadingCityServices;
@property(readonly, getter=isLoadingSysPetemeter) _Bool loadingSysPetemeter;

@end

