//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "NewAddressBookDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class AddressBook, NSArray, NSMutableArray, NSString, UIButton, UITableView, UITextField;

@interface OrderCarSelectPassengerViewController : SuperViewController <NewAddressBookDelegate, UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    NSArray *contactsArray;
    _Bool _isSelectSelf;
    _Bool _isThemeCar;
    UIButton *_selfBtn;
    UIButton *_contactBtn;
    UITableView *_historyPassengersTable;
    UITextField *_passengerNameField;
    UITextField *_passengerPhoneNumberField;
    id <OrderCarSelectPassengerDelegate> _delegate;
    AddressBook *_fromAddressBook;
    unsigned long long _serviceType;
    NSMutableArray *_historyPassengers;
}

@property(retain, nonatomic) NSMutableArray *historyPassengers; // @synthesize historyPassengers=_historyPassengers;
@property(nonatomic) _Bool isThemeCar; // @synthesize isThemeCar=_isThemeCar;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
@property(retain, nonatomic) AddressBook *fromAddressBook; // @synthesize fromAddressBook=_fromAddressBook;
@property(nonatomic) _Bool isSelectSelf; // @synthesize isSelectSelf=_isSelectSelf;
@property(nonatomic) id <OrderCarSelectPassengerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UITextField *passengerPhoneNumberField; // @synthesize passengerPhoneNumberField=_passengerPhoneNumberField;
@property(nonatomic) __weak UITextField *passengerNameField; // @synthesize passengerNameField=_passengerNameField;
@property(nonatomic) __weak UITableView *historyPassengersTable; // @synthesize historyPassengersTable=_historyPassengersTable;
@property(nonatomic) __weak UIButton *contactBtn; // @synthesize contactBtn=_contactBtn;
@property(nonatomic) __weak UIButton *selfBtn; // @synthesize selfBtn=_selfBtn;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)createDeleteButton:(id)arg1 indexPath:(id)arg2 inCell:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)newAddressBookDidSelectBack;
- (void)newAddressBookDidSelect:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)goContacts:(id)arg1;
- (void)done:(id)arg1;
- (void)back:(id)arg1;
- (void)selectSelf:(id)arg1;
- (void)nextPage:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

