//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderCarBaseViewController.h"

@class NSArray, NSMutableArray, NSString, UIImageView;

@interface OrderCarBaoCheViewController : OrderCarBaseViewController
{
    double _baoCheTime;
    long long _baoCheMileage;
    double _systemBaoCheTime;
    long long _systemBaoCheMileage;
    long long _maxBaoCheMileage;
    double _maxBaoCheTime;
    NSString *_baoCheTimeString;
    NSString *_baoCheMileageString;
    long long _yuGuType;
    _Bool _isReturn;
    NSString *_lowConsumptionStr;
    _Bool _clickPackageCellNeedEstimate;
    UIImageView *_returnImgView;
    NSArray *_packageSelectedRows;
    NSMutableArray *_packageMileages;
    NSMutableArray *_packageTimes;
    double _maxSpeed;
    double _packageMinTime;
    double _packageMinMileage;
}

@property(nonatomic) double packageMinMileage; // @synthesize packageMinMileage=_packageMinMileage;
@property(nonatomic) double packageMinTime; // @synthesize packageMinTime=_packageMinTime;
@property(nonatomic) double maxSpeed; // @synthesize maxSpeed=_maxSpeed;
@property(retain, nonatomic) NSMutableArray *packageTimes; // @synthesize packageTimes=_packageTimes;
@property(retain, nonatomic) NSMutableArray *packageMileages; // @synthesize packageMileages=_packageMileages;
@property(retain, nonatomic) NSArray *packageSelectedRows; // @synthesize packageSelectedRows=_packageSelectedRows;
@property(retain, nonatomic) UIImageView *returnImgView; // @synthesize returnImgView=_returnImgView;
- (void).cxx_destruct;
- (_Bool)overMaxBaoCheTime;
- (_Bool)overMaxBaoCheMileage;
- (void)baoCheEstimateFailure;
- (void)setBaoCheEstimateType;
- (void)showSelectPackageViewWhenBaoCheDidNotSelectPackage;
- (void)showSelectTimeViewWhenYuYueNotEnough30Minutes;
- (void)goNext:(id)arg1;
- (id)getPackagePickerDatas;
- (_Bool)pickerSelectRows:(id)arg1;
- (void)showSelectPackageView;
- (void)returnButtonDidClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)estimateFinish:(id)arg1;
- (void)setShangCheTime:(id)arg1 hour:(id)arg2 min:(id)arg3;
- (void)getFeePriceOnline;
- (void)initPackageParamWithDate:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

