//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class AFHTTPRequestOperationManager, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel;

@interface OrderCancelViewController : SuperViewController
{
    AFHTTPRequestOperationManager *httpManager;
    NSLayoutConstraint *applyBtnHeight;
    NSLayoutConstraint *applyBtnBottom;
    NSLayoutConstraint *logoCenterY;
    _Bool _cancelNeedPay;
    UIImageView *_iconImgView;
    UILabel *_msgLbl;
    UIButton *_cancelBtn;
    UIButton *_cancelApplyBtn;
    UIButton *_continueBtn;
    NSString *_msg;
    long long _orderID;
    NSString *_orderCancelDesURL;
    CDUnknownBlockType _cancelOrderStatusBlock;
}

@property(copy, nonatomic) CDUnknownBlockType cancelOrderStatusBlock; // @synthesize cancelOrderStatusBlock=_cancelOrderStatusBlock;
@property(copy, nonatomic) NSString *orderCancelDesURL; // @synthesize orderCancelDesURL=_orderCancelDesURL;
@property(nonatomic) long long orderID; // @synthesize orderID=_orderID;
@property(nonatomic) _Bool cancelNeedPay; // @synthesize cancelNeedPay=_cancelNeedPay;
@property(copy, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) __weak UIButton *continueBtn; // @synthesize continueBtn=_continueBtn;
@property(nonatomic) __weak UIButton *cancelApplyBtn; // @synthesize cancelApplyBtn=_cancelApplyBtn;
@property(nonatomic) __weak UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(nonatomic) __weak UILabel *msgLbl; // @synthesize msgLbl=_msgLbl;
@property(nonatomic) __weak UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
- (void).cxx_destruct;
- (void)orderCancelPriceDescription;
- (void)goBackWithStatus:(long long)arg1;
- (void)cancelOrderApply;
- (void)cancelOrder;
- (void)didReceiveMemoryWarning;
- (void)goBack;
- (void)dealloc;
- (void)viewDidLoad;

@end

