//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderCarBaseViewController.h"

#import "PliaceSelectViewDelegate.h"

@class NSIndexPath, NSString, PliaceSelectViewController, ThemeCar, UIColor;

@interface OrderCarThemeCarViewController : OrderCarBaseViewController <PliaceSelectViewDelegate>
{
    ThemeCar *_themeCar;
    UIColor *tintColor;
    _Bool isCanShowSelectOtherStartAddress;
    _Bool isCanShowSelectOtherEndAddress;
    _Bool isShowActivityTime;
    NSIndexPath *currentIndexPath;
    int _tcid;
    PliaceSelectViewController *_pliaceSelectViewController;
}

@property(retain, nonatomic) PliaceSelectViewController *pliaceSelectViewController; // @synthesize pliaceSelectViewController=_pliaceSelectViewController;
@property(nonatomic) int tcid; // @synthesize tcid=_tcid;
- (void).cxx_destruct;
- (void)selectEndAddress:(id)arg1;
- (void)selectStartAddress:(id)arg1;
- (void)showPliaceSelectViewControllerIsStart:(_Bool)arg1;
- (void)selectAddressValue:(id)arg1 pointName:(id)arg2 lat:(double)arg3 lon:(double)arg4 isChangeCity:(_Bool)arg5;
- (void)sendUseCarBroadcast:(id)arg1;
- (void)goNext:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)showDateErr:(id)arg1;
- (void)setShangCheTime:(id)arg1 hour:(id)arg2 min:(id)arg3;
- (void)getFeePriceOnline;
- (void)getFeePrice;
- (void)didReceiveMemoryWarning;
- (void)calculateFee;
- (void)goFeeDetail;
- (void)pliaceSelectAddressValue:(id)arg1 lat:(double)arg2 lon:(double)arg3 addId:(int)arg4;
- (void)pliaceSelectAddressValue:(id)arg1 pointName:(id)arg2 lat:(double)arg3 lon:(double)arg4 addIsStart:(_Bool)arg5;
- (void)pliaceSelectIndexPath:(id)arg1;
- (void)pliaceSelectCancel;
- (void)setStartAdderssAndEndAdderssDatas;
- (void)getThemeCarInfo;
- (void)rightBtn;
- (void)initMainUI;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

