//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BMKMapViewDelegate.h"
#import "BMKRouteSearchDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AFHTTPRequestOperationManager, BMKMapView, BMKPolyline, BMKRouteSearch, MapCarActionView, NSString, NSTimer, OrderDetail, PublishInfo, RouteAnnotation;

@interface OrderMapView : UIView <BMKMapViewDelegate, BMKRouteSearchDelegate, UIGestureRecognizerDelegate>
{
    PublishInfo *_pubInfo;
    RouteAnnotation *sendOrderStartAnnotation;
    RouteAnnotation *sendOrderEndAnnotation;
    BMKRouteSearch *sendOrderRouteSearcher;
    BMKPolyline *sendOrderDrivingPolyLine;
    AFHTTPRequestOperationManager *httpManager;
    OrderDetail *_orderDetail;
    _Bool showDriverInCenter;
    NSTimer *driverPositionTimer;
    NSTimer *destinationTimer;
    _Bool isStartPointInCenter;
    _Bool mapCarActionViewStartUpdateDriver;
    BMKRouteSearch *routeSearcher;
    BMKRouteSearch *loactionSearcher;
    RouteAnnotation *driverAnnotation;
    RouteAnnotation *startAnnotation;
    RouteAnnotation *endAnnotation;
    BMKPolyline *onTripDrivingPolyLine;
    BMKPolyline *orderDrivingPolyLine;
    _Bool _showRouteLine;
    id <UpdateDriveDistanceDelegate> _delegate;
    BMKMapView *_mapView;
    MapCarActionView *_mapCarActionView;
}

@property(retain, nonatomic) MapCarActionView *mapCarActionView; // @synthesize mapCarActionView=_mapCarActionView;
@property(retain, nonatomic) BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) _Bool showRouteLine; // @synthesize showRouteLine=_showRouteLine;
@property(nonatomic) id <UpdateDriveDistanceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onGetDrivingRouteResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (id)getRouteAnnotationView:(id)arg1 viewForAnnotation:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (void)displayStartAndEndAnnotation:(_Bool)arg1;
- (void)updateDriverLocation:(double)arg1 lng:(double)arg2;
- (void)getDriverPositionToDestination;
- (void)getDriverPosition;
- (void)removeDestinationTimer;
- (void)addDestinationTimer;
- (void)removeDriverPositionTimer;
- (void)addDriverPositionTimer;
- (void)updateMapViewWithOrderDetail;
- (void)updateStartOrderViewWithOrderDetail:(id)arg1;
- (void)showStartPointWithSendOrderView;
- (void)updateSendOrderViewWithPublishInfo:(id)arg1;
- (void)updateMapViewInvisibleTop:(double)arg1 bottom:(double)arg2;
- (void)setupMapView;
- (void)remove;
- (void)superviewDidDisappear;
- (void)superviewWillDisappear;
- (void)superviewDidAppear;
- (void)superviewWillAppear;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

