//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSString;

@interface OrderObjectionContent : NSObject <NSCoding>
{
    NSString *_descText;
    NSArray *_contentArray;
}

@property(copy, nonatomic) NSArray *contentArray; // @synthesize contentArray=_contentArray;
@property(copy, nonatomic) NSString *descText; // @synthesize descText=_descText;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

