//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSString, OrderDetail, UIButton, UITableView;

@interface OrderFeeDetailViewController : SuperViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSMutableArray *dataSource;
    OrderDetail *_orderDetail;
    UITableView *_tableView;
    UIButton *_valuationButton;
    NSLayoutConstraint *_valuationBottomConstraint;
    NSLayoutConstraint *_valuationContentViewHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *valuationContentViewHeightConstraint; // @synthesize valuationContentViewHeightConstraint=_valuationContentViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *valuationBottomConstraint; // @synthesize valuationBottomConstraint=_valuationBottomConstraint;
@property(nonatomic) __weak UIButton *valuationButton; // @synthesize valuationButton=_valuationButton;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)setOrderDetail:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (id)setFeeDetail:(id)arg1 serviceTypeDesc:(id)arg2 detail:(id)arg3 price:(id)arg4 specialColor:(_Bool)arg5 specialFontSize:(_Bool)arg6;
- (id)formatTime:(id)arg1;
- (id)formatDay:(id)arg1;
- (void)testOrderDetail;
- (void)addData;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateFooterViewLocation;
- (void)goValuationViewController:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)didReceiveMemoryWarning;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

