//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderDetailBaseViewController.h"

@class UILabel, UITableView;

@interface OrderAuditingViewController : OrderDetailBaseViewController
{
    UITableView *_tableView;
    UILabel *_orderObjectionTipLabel;
}

@property(retain, nonatomic) UILabel *orderObjectionTipLabel; // @synthesize orderObjectionTipLabel=_orderObjectionTipLabel;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showTipWithOrderObjection;
- (void)setOrderView:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

