//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CustomIOSAlertView.h"

@class UIButton, UILabel;

@interface OrderCarDetailAppStoreCoreAlertView : CustomIOSAlertView
{
    UILabel *_titleLabel;
    UIButton *_button1;
    UIButton *_button2;
    UIButton *_button3;
    CDUnknownBlockType _targetBlock;
}

@property(copy, nonatomic) CDUnknownBlockType targetBlock; // @synthesize targetBlock=_targetBlock;
@property(retain, nonatomic) UIButton *button3; // @synthesize button3=_button3;
@property(retain, nonatomic) UIButton *button2; // @synthesize button2=_button2;
@property(retain, nonatomic) UIButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)buttonAction:(id)arg1;
- (id)createAlertButton:(id)arg1 bounds:(struct CGRect)arg2;
- (id)initWithMsg:(id)arg1 title1:(id)arg2 title2:(id)arg3 title3:(id)arg4;

@end

