//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSArray, NSString;

@interface OrderCommentStarContent : NSObject <NSCoding>
{
    int _isShowTextbox;
    int _limitNumber;
    NSString *_textboxPrompt;
    NSString *_title;
    NSArray *_contentArray;
}

@property(copy, nonatomic) NSArray *contentArray; // @synthesize contentArray=_contentArray;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int limitNumber; // @synthesize limitNumber=_limitNumber;
@property(copy, nonatomic) NSString *textboxPrompt; // @synthesize textboxPrompt=_textboxPrompt;
@property(nonatomic) int isShowTextbox; // @synthesize isShowTextbox=_isShowTextbox;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

