//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextFieldDelegate.h"

@class NSString, UIButton, UIImageView, UITextField, UIView;

@interface OrderAddressCell : UITableViewCell <UITextFieldDelegate>
{
    UIImageView *_midImgView;
    UITextField *_fromTF;
    UITextField *_toTF;
    UIView *_tfSepLine;
    UIButton *_rightBtn;
    CDUnknownBlockType _addressSelectedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType addressSelectedBlock; // @synthesize addressSelectedBlock=_addressSelectedBlock;
@property(nonatomic) __weak UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(nonatomic) __weak UIView *tfSepLine; // @synthesize tfSepLine=_tfSepLine;
@property(nonatomic) __weak UITextField *toTF; // @synthesize toTF=_toTF;
@property(nonatomic) __weak UITextField *fromTF; // @synthesize fromTF=_fromTF;
@property(nonatomic) __weak UIImageView *midImgView; // @synthesize midImgView=_midImgView;
- (void).cxx_destruct;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

