//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "OrderCommentOptionDelegate.h"
#import "RatingBarDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITextViewDelegate.h"

@class AFHTTPRequestOperationManager, NSDictionary, NSMutableArray, NSString, OrderCommentStarContent, RatingBar, UILabel;

@interface OrderCommentView : UIView <UIGestureRecognizerDelegate, RatingBarDelegate, OrderCommentOptionDelegate, UITextViewDelegate>
{
    id <OrderCommentSuccessDelegate> _delegate;
    UIView *_dialogView;
    UIView *_containerView;
    RatingBar *_ratingBar;
    NSDictionary *_evaluateDatas;
    UILabel *_countLabel;
    long long _limitInputLen;
    NSString *_commentStr;
    NSMutableArray *_starOptionBySelectedArray;
    long long _orderId;
    AFHTTPRequestOperationManager *_httpManager;
    OrderCommentStarContent *_currentStarContent;
}

@property(retain, nonatomic) OrderCommentStarContent *currentStarContent; // @synthesize currentStarContent=_currentStarContent;
@property(retain, nonatomic) AFHTTPRequestOperationManager *httpManager; // @synthesize httpManager=_httpManager;
@property(nonatomic) long long orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSMutableArray *starOptionBySelectedArray; // @synthesize starOptionBySelectedArray=_starOptionBySelectedArray;
@property(copy, nonatomic) NSString *commentStr; // @synthesize commentStr=_commentStr;
@property(nonatomic) long long limitInputLen; // @synthesize limitInputLen=_limitInputLen;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) NSDictionary *evaluateDatas; // @synthesize evaluateDatas=_evaluateDatas;
@property(retain, nonatomic) RatingBar *ratingBar; // @synthesize ratingBar=_ratingBar;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *dialogView; // @synthesize dialogView=_dialogView;
@property(nonatomic) id <OrderCommentSuccessDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setCountColor:(long long)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)didTapStarOption:(id)arg1 isSelected:(_Bool)arg2;
- (struct CGRect)countingStarOptionNeedFrameWithOrderCommentStarOption:(id)arg1 beforeOptionView:(id)arg2 beforeIsLong:(_Bool)arg3 ownIsLong:(_Bool)arg4 addHeight:(double)arg5 inView:(id)arg6 index:(int)arg7;
- (_Bool)isLongWithOrderCommentStarOption:(id)arg1 inView:(id)arg2;
- (_Bool)needAddHeightWithBeforeOptionView:(id)arg1 beforeIsLong:(_Bool)arg2 ownIsLong:(_Bool)arg3;
- (id)getSelectCode;
- (id)getSelectString;
- (void)submitButtonAction;
- (id)createContainerViewWithStarContent:(id)arg1 starNumber:(long long)arg2;
- (void)updateDialogViewWithStarNumber:(long long)arg1;
- (void)selectedStarNumber:(long long)arg1;
- (struct CGSize)countDialogSize;
- (struct CGSize)countScreenSize;
- (id)createDialogView;
- (void)dealloc;
- (void)close;
- (void)show;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)outsideTap:(id)arg1;
- (void)addGesture;
- (void)setStatusBarOrginX:(double)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)removeKeyboardNotification;
- (void)addKeyboardNotification;
- (void)setupData;
- (id)initWithOrderId:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

