//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKLocationServiceDelegate.h"
#import "BMKRouteSearchDelegate.h"
#import "CarTypeCollectionViewCellDelagate.h"
#import "OrderCarSelectPassengerDelegate.h"
#import "SelectAddressDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class AFHTTPRequestOperationManager, BMKGeoCodeSearch, BMKLocationService, BMKRouteSearch, City, CustomAlertMenuView, LocationBean, NSArray, NSDate, NSDictionary, NSLayoutConstraint, NSMutableArray, NSString, OrderCarSelectPassengerViewController, RemarkPopOverViewController, UIButton, UICollectionView, UILabel, UIPopoverMenuViewController, UITableView, UITextField, UIView;

@interface OrderCarBaseViewController : BaseViewController <BMKGeoCodeSearchDelegate, BMKLocationServiceDelegate, OrderCarSelectPassengerDelegate, CarTypeCollectionViewCellDelagate, SelectAddressDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, BMKRouteSearchDelegate>
{
    NSMutableArray *carTypeArray;
    NSDictionary *carTypeInstantIconInfo;
    _Bool isStartAddress;
    BMKRouteSearch *_routeSearcher;
    NSString *estimateFee;
    _Bool isEstimating;
    _Bool isLoactioned;
    NSString *username;
    NSString *userPhone;
    AFHTTPRequestOperationManager *httpManager;
    _Bool isSelectSelf;
    RemarkPopOverViewController *_remarkPopOverViewController;
    OrderCarSelectPassengerViewController *orderCarSelectPassenger;
    BMKGeoCodeSearch *bmkSearch;
    BMKLocationService *locationService;
    _Bool isTimeHideHUD;
    _Bool isFirstEstimateSuccess;
    _Bool isGettingCarTypeInstantIconInfo;
    struct CGRect focusViewRect;
    CustomAlertMenuView *_swtichAccountAlertMenuView;
    _Bool _isNowCall;
    _Bool _isEstimateSuccess;
    int _addId;
    unsigned long long _serviceType;
    LocationBean *_startLocation;
    LocationBean *_endLocation;
    NSDate *_selectDate;
    NSMutableArray *_pickerSelectedRows;
    NSMutableArray *_serviceMinTimeRow;
    NSString *_chufaTime;
    NSDate *_startTime;
    NSString *_carTypes;
    NSString *_yuguPrice;
    NSArray *_enterpriseLimitCarTypes;
    UICollectionView *_carTypeCollectionView;
    NSLayoutConstraint *_carTypeCollectionLeftConstraint;
    NSLayoutConstraint *_carTypeCollectionRightConstraint;
    NSLayoutConstraint *_carTypeCollectionTopConstraint;
    NSLayoutConstraint *_carTypeCollectionBottomConstraint;
    UIView *_noOpenView;
    UILabel *_estimateDescribeLabel;
    UIView *_positionView;
    UITextField *_startField;
    UITextField *_endField;
    UIView *_carTypeDetailView;
    UIButton *_nextBtn;
    City *_currentCity;
    long long _estimateFlowId;
    UIPopoverMenuViewController *_popoverMenuViewController;
    UITableView *_tableView;
    UITextField *_timeField;
    NSLayoutConstraint *_bottomViewBottom;
    NSLayoutConstraint *_tableBottom;
    NSDictionary *_lastEstimateParams;
    NSString *_individuationCarTypeString;
    struct CGSize _tableContentSize;
}

@property(copy, nonatomic) NSString *individuationCarTypeString; // @synthesize individuationCarTypeString=_individuationCarTypeString;
@property(nonatomic) struct CGSize tableContentSize; // @synthesize tableContentSize=_tableContentSize;
@property(retain, nonatomic) NSDictionary *lastEstimateParams; // @synthesize lastEstimateParams=_lastEstimateParams;
@property(retain, nonatomic) NSLayoutConstraint *tableBottom; // @synthesize tableBottom=_tableBottom;
@property(retain, nonatomic) NSLayoutConstraint *bottomViewBottom; // @synthesize bottomViewBottom=_bottomViewBottom;
@property(nonatomic) __weak UITextField *timeField; // @synthesize timeField=_timeField;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIPopoverMenuViewController *popoverMenuViewController; // @synthesize popoverMenuViewController=_popoverMenuViewController;
@property(nonatomic) long long estimateFlowId; // @synthesize estimateFlowId=_estimateFlowId;
@property(retain, nonatomic) City *currentCity; // @synthesize currentCity=_currentCity;
@property(nonatomic) __weak UIButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(nonatomic) __weak UIView *carTypeDetailView; // @synthesize carTypeDetailView=_carTypeDetailView;
@property(nonatomic) __weak UITextField *endField; // @synthesize endField=_endField;
@property(nonatomic) __weak UITextField *startField; // @synthesize startField=_startField;
@property(nonatomic) __weak UIView *positionView; // @synthesize positionView=_positionView;
@property(nonatomic) __weak UILabel *estimateDescribeLabel; // @synthesize estimateDescribeLabel=_estimateDescribeLabel;
@property(nonatomic) __weak UIView *noOpenView; // @synthesize noOpenView=_noOpenView;
@property(nonatomic) __weak NSLayoutConstraint *carTypeCollectionBottomConstraint; // @synthesize carTypeCollectionBottomConstraint=_carTypeCollectionBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeCollectionTopConstraint; // @synthesize carTypeCollectionTopConstraint=_carTypeCollectionTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeCollectionRightConstraint; // @synthesize carTypeCollectionRightConstraint=_carTypeCollectionRightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *carTypeCollectionLeftConstraint; // @synthesize carTypeCollectionLeftConstraint=_carTypeCollectionLeftConstraint;
@property(nonatomic) __weak UICollectionView *carTypeCollectionView; // @synthesize carTypeCollectionView=_carTypeCollectionView;
@property(retain, nonatomic) NSArray *enterpriseLimitCarTypes; // @synthesize enterpriseLimitCarTypes=_enterpriseLimitCarTypes;
@property(nonatomic) int addId; // @synthesize addId=_addId;
@property(nonatomic) _Bool isEstimateSuccess; // @synthesize isEstimateSuccess=_isEstimateSuccess;
@property(copy, nonatomic) NSString *yuguPrice; // @synthesize yuguPrice=_yuguPrice;
@property(copy, nonatomic) NSString *carTypes; // @synthesize carTypes=_carTypes;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSString *chufaTime; // @synthesize chufaTime=_chufaTime;
@property(retain, nonatomic) NSMutableArray *serviceMinTimeRow; // @synthesize serviceMinTimeRow=_serviceMinTimeRow;
@property(retain, nonatomic) NSMutableArray *pickerSelectedRows; // @synthesize pickerSelectedRows=_pickerSelectedRows;
@property(retain, nonatomic) NSDate *selectDate; // @synthesize selectDate=_selectDate;
@property(retain, nonatomic) LocationBean *endLocation; // @synthesize endLocation=_endLocation;
@property(retain, nonatomic) LocationBean *startLocation; // @synthesize startLocation=_startLocation;
@property(nonatomic) _Bool isNowCall; // @synthesize isNowCall=_isNowCall;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
- (void).cxx_destruct;
- (void)goOrderDetailWtihPublishInfo:(id)arg1;
- (_Bool)isUnSelectedCarType;
- (_Bool)needEstimate;
- (void)calculateFee;
- (void)estimateErrorResetFee;
- (void)showEstimateError;
- (void)setEstimateDescribe:(id)arg1;
- (void)getFeePriceOnlineWithStartTime:(id)arg1 serviceType:(unsigned long long)arg2 Url:(id)arg3 Tcid:(int)arg4 baocheDic:(id)arg5;
- (void)updateServiceCarImageInfo:(id)arg1;
- (void)getCarTypeInstantIconInfo;
- (void)getIndividuationCarType;
- (_Bool)isLimitCarType:(long long)arg1;
- (void)setDefaultCarTypes;
- (void)limitCarType;
- (id)getCityWithCityName:(id)arg1;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)didFailToLocateUserWithError:(id)arg1;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)reverseGeoCurrentCity:(struct CLLocationCoordinate2D)arg1;
- (void)removeDeleagte;
- (void)hideHud;
- (void)startLoaction;
- (void)loaction;
- (void)goOrderList;
- (void)bindCard;
- (void)goBindBankCard;
- (void)goBalance:(id)arg1;
- (void)switchAccountType;
- (void)showSwitchAccountType:(id)arg1;
- (void)goSecurityBind;
- (void)neededToBindSecurityPayWithStatusFaqi:(id)arg1;
- (void)showCallServiceWithStatusFaqi:(id)arg1;
- (void)showCreditCardInvalid:(int)arg1 smsg:(id)arg2 needPrice:(id)arg3;
- (void)showBalanceIsNotEnough:(id)arg1 needPrice:(id)arg2;
- (void)baoCheEstimateFailure;
- (void)showSelectPackageViewWhenBaoCheDidNotSelectPackage;
- (void)showSelectTimeViewWhenYuYueNotEnough30Minutes;
- (void)sendUseCarBroadcast:(id)arg1;
- (void)orderCarSelectPassenger:(id)arg1 phoneNumber:(id)arg2 isSelf:(_Bool)arg3;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (_Bool)shouldPerformSegueWithIdentifier:(id)arg1 sender:(id)arg2;
- (void)setBaoCheEstimateType;
- (void)clearEstimateResult;
- (void)estimateFinish:(id)arg1;
- (void)onGetDrivingRouteResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)evaluationPrice:(id)arg1 andStart:(id)arg2 andEnd:(id)arg3 andServiceType:(unsigned long long)arg4;
- (id)getSelectedCarTypes;
- (id)getCurrentMapCity;
- (void)selectShuttleType:(unsigned long long)arg1 segmentedType:(unsigned long long)arg2 isStartPoint:(_Bool)arg3 air:(id)arg4 city:(id)arg5 time:(id)arg6 fromService:(unsigned long long)arg7;
- (void)selectAddressValue:(id)arg1 pointName:(id)arg2 lat:(double)arg3 lon:(double)arg4 isChangeCity:(_Bool)arg5;
- (void)goFeeDetailWithCarTypeModel:(id)arg1;
- (void)goNext:(id)arg1;
- (void)showSelectAddressViewController:(_Bool)arg1;
- (void)selectEndAddress:(id)arg1;
- (void)selectStartAddress:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)getFeePriceWithStartTime:(id)arg1 serviceType:(unsigned long long)arg2;
- (void)getFeePriceOnline;
- (void)getFeePrice;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setShangCheTime:(id)arg1 hour:(id)arg2 min:(id)arg3;
- (void)showDateErr:(id)arg1;
- (void)showSelectTimeView:(id)arg1;
- (void)clickSelectTime;
- (void)carTypeCollectionViewCell:(id)arg1 clickButton:(id)arg2;
- (void)backBarButtonAction:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (void)cancelConnection;
- (void)hideKeyboard;
- (void)loadCarTypePrice;
- (void)switchAccountTypeSuccess;
- (void)updateCartypeMessage;
- (id)loadDatePickerDatasByServiceType:(unsigned long long)arg1 selectedDate:(id)arg2;
- (void)loadCarTypes:(unsigned long long)arg1 date:(id)arg2 atLeastGetOneDay:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)updateCollectionViewWidth;
- (void)updateContentHeight;
- (void)updateViewLocation;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidLoad;
- (void)updateInfo;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

