//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol OrderCommentSuccessDelegate <NSObject>
- (void)orderCommentSuccessWithIsPopupGuide:(_Bool)arg1 title:(NSString *)arg2 content1:(NSString *)arg3 content2:(NSString *)arg4 content3:(NSString *)arg5;
@end

