//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UICollectionView, UITextField, UIView;

@interface OrdinaryAmountCell : UITableViewCell
{
    UICollectionView *_ordinaryCollectionView;
    UITextField *_rechargetextFd;
    UIView *_rechargeFdBg;
    NSLayoutConstraint *_ordinaryCollectionViewHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *ordinaryCollectionViewHeightConstraint; // @synthesize ordinaryCollectionViewHeightConstraint=_ordinaryCollectionViewHeightConstraint;
@property(nonatomic) __weak UIView *rechargeFdBg; // @synthesize rechargeFdBg=_rechargeFdBg;
@property(nonatomic) __weak UITextField *rechargetextFd; // @synthesize rechargetextFd=_rechargetextFd;
@property(nonatomic) __weak UICollectionView *ordinaryCollectionView; // @synthesize ordinaryCollectionView=_ordinaryCollectionView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

