//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface PassengerStyleCell : UITableViewCell
{
    UIImageView *_leftImgView;
    UILabel *_leftLabel;
    UILabel *_rightLabel;
}

@property(nonatomic) __weak UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(nonatomic) __weak UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(nonatomic) __weak UIImageView *leftImgView; // @synthesize leftImgView=_leftImgView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

