//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PublishInfo : NSObject
{
    int isTalk;
    int isTeShuChengKe;
    int serviceType;
    int useTime;
    long long airPortId;
    NSString *ccrName;
    NSString *ccrPhone;
    long long cityId;
    NSString *des;
    NSString *shangche;
    NSString *shangCheAddress;
    double shangCheLat;
    double shangCheLng;
    NSString *shangCheTime;
    NSString *xiaChe;
    NSString *xiaCheAddress;
    double xiaCheLat;
    double xiaCheLng;
    NSString *carTypes;
    NSString *hangBanCode;
    double yuguPrice;
    double farePrice;
    long long _orderID;
    long long _estimateFlowId;
    long long _travelMileage;
    double _travelTime;
    long long _isReturn;
}

@property(nonatomic) long long isReturn; // @synthesize isReturn=_isReturn;
@property(nonatomic) double travelTime; // @synthesize travelTime=_travelTime;
@property(nonatomic) long long travelMileage; // @synthesize travelMileage=_travelMileage;
@property(nonatomic) long long estimateFlowId; // @synthesize estimateFlowId=_estimateFlowId;
@property(nonatomic) long long orderID; // @synthesize orderID=_orderID;
@property(nonatomic) double farePrice; // @synthesize farePrice;
@property double yuguPrice; // @synthesize yuguPrice;
@property(copy, nonatomic) NSString *hangBanCode; // @synthesize hangBanCode;
@property(copy, nonatomic) NSString *carTypes; // @synthesize carTypes;
@property double xiaCheLng; // @synthesize xiaCheLng;
@property double xiaCheLat; // @synthesize xiaCheLat;
@property(copy, nonatomic) NSString *xiaCheAddress; // @synthesize xiaCheAddress;
@property(copy, nonatomic) NSString *xiaChe; // @synthesize xiaChe;
@property int useTime; // @synthesize useTime;
@property(copy, nonatomic) NSString *shangCheTime; // @synthesize shangCheTime;
@property double shangCheLng; // @synthesize shangCheLng;
@property double shangCheLat; // @synthesize shangCheLat;
@property(copy, nonatomic) NSString *shangCheAddress; // @synthesize shangCheAddress;
@property(copy, nonatomic) NSString *shangche; // @synthesize shangche;
@property int serviceType; // @synthesize serviceType;
@property int isTeShuChengKe; // @synthesize isTeShuChengKe;
@property int isTalk; // @synthesize isTalk;
@property(copy, nonatomic) NSString *des; // @synthesize des;
@property long long cityId; // @synthesize cityId;
@property(copy, nonatomic) NSString *ccrPhone; // @synthesize ccrPhone;
@property(copy, nonatomic) NSString *ccrName; // @synthesize ccrName;
@property long long airPortId; // @synthesize airPortId;
- (void).cxx_destruct;
- (id)initWidthParameters:(int)arg1 cityid:(long long)arg2 carTypes:(id)arg3 airPortId:(long long)arg4 shangche:(id)arg5 shangCheAddress:(id)arg6 shangCheLng:(double)arg7 shangCheLat:(double)arg8 shangCheTime:(id)arg9 xiaChe:(id)arg10 xiaCheAddress:(id)arg11 xiaCheLng:(double)arg12 xiaCheLat:(double)arg13 useTime:(int)arg14 des:(id)arg15 isTeShuChengKe:(int)arg16 isTalk:(int)arg17 ccrName:(id)arg18 ccrPhone:(id)arg19 hangBanCode:(id)arg20 yuguPrice:(double)arg21 farePrice:(double)arg22;

@end

