//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface RatingBar : UIView
{
    _Bool _enable;
    long long _starNumber;
    unsigned long long _lowStarNumber;
    id <RatingBarDelegate> _delegate;
    UIColor *_viewColor;
    UIView *_bottomView;
    UIView *_topView;
    double _starWidth;
}

@property(nonatomic) double starWidth; // @synthesize starWidth=_starWidth;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(retain, nonatomic) UIColor *viewColor; // @synthesize viewColor=_viewColor;
@property(nonatomic) id <RatingBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long lowStarNumber; // @synthesize lowStarNumber=_lowStarNumber;
@property(nonatomic) long long starNumber; // @synthesize starNumber=_starNumber;
- (void).cxx_destruct;
- (void)pan:(id)arg1;
- (void)tap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

