//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Air, BMKPoiInfo, City, NSDate, NSString;

@protocol SelectAddressDelegate <NSObject>
- (void)selectShuttleType:(unsigned long long)arg1 segmentedType:(unsigned long long)arg2 isStartPoint:(_Bool)arg3 air:(Air *)arg4 city:(City *)arg5 time:(NSDate *)arg6 fromService:(unsigned long long)arg7;
- (void)selectGeoCodeAddressValue:(BMKPoiInfo *)arg1:(_Bool)arg2;
- (void)selectAddressValue:(NSString *)arg1 pointName:(NSString *)arg2 lat:(double)arg3 lon:(double)arg4 isChangeCity:(_Bool)arg5;
@end

