//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "BMKGeoCodeSearchDelegate.h"
#import "BMKPoiSearchDelegate.h"

@class AFHTTPRequestOperationManager, BMKGeoCodeSearch, BMKPoiInfo, BMKPoiSearch, City, CustomAddress, NSMutableArray, NSObject<SelectCustomAddressDelegate>, NSString, NSTimer, UIButton, UIImageView, UITableView, UITextField, UIView;

@interface SelectCustomAddressViewController : BaseViewController <BMKPoiSearchDelegate, BMKGeoCodeSearchDelegate>
{
    BMKPoiInfo *_selectedPoint;
    BMKPoiSearch *_poiSearch;
    BMKGeoCodeSearch *_geoCodeSearch;
    NSMutableArray *_addressArray;
    struct CLLocationCoordinate2D location;
    _Bool isEmptyText;
    NSTimer *matchTimer;
    AFHTTPRequestOperationManager *_manager;
    long long _addressId;
    int _customId;
    UIView *searchBtn;
    UIImageView *_icon;
    UITextField *_addressTextField;
    UITableView *_tableView;
    UIButton *_cityNameBtn;
    NSObject<SelectCustomAddressDelegate> *_delegate;
    City *_city;
    NSString *_cityName;
    CustomAddress *_commonAddress;
}

@property(retain, nonatomic) CustomAddress *commonAddress; // @synthesize commonAddress=_commonAddress;
@property(nonatomic) int customId; // @synthesize customId=_customId;
@property(retain, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(retain, nonatomic) City *city; // @synthesize city=_city;
@property(nonatomic) NSObject<SelectCustomAddressDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIButton *cityNameBtn; // @synthesize cityNameBtn=_cityNameBtn;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UITextField *addressTextField; // @synthesize addressTextField=_addressTextField;
@property(nonatomic) __weak UIImageView *icon; // @synthesize icon=_icon;
@property(nonatomic) __weak UIView *searchBtn; // @synthesize searchBtn;
- (void).cxx_destruct;
- (void)removeBackground;
- (void)setupBackground;
- (void)insertOrUpdateWithBMKPoiInfo:(id)arg1;
- (void)cityOnSelected:(id)arg1;
- (void)goSelectCity:(id)arg1;
- (void)onClickBack:(id *)arg1;
- (void)dismissKeyBoard;
- (void)invalidateTimer;
- (void)gotoAutoSearch:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyboard;
- (void)scrollViewDidScroll:(id)arg1;
- (void)routeInfoCellDidPress:(id)arg1;
- (void)addOrUpdateComentAddressRequest:(id)arg1 isAdd:(_Bool)arg2;
- (void)poiInfoCellDidPress:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)createRouteInfoCell:(id)arg1;
- (id)createPoiInfoCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)reloadDataAndView;
- (void)onGetPoiResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)autoSearch:(id)arg1;
- (void)search;
- (void)initMainUI;
- (void)viewDidLoad;
- (void)removeObject;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)logName:(id)arg1;
- (void)loadHistoryWithObject:(id)arg1;
- (void)initOldLinksWithCityId:(int)arg1;
- (void)initOldLinks;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

