//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AFHTTPRequestOperationManager, CallServiceActionSheetView, CountDownView, CustomIOSAlertView, FareSelectMenuViewController, NSString, NSTimer, OrderCancelActionSheetView, PublishInfo, SimpleCustomAlertView, TutorialView, UIButton, UIColor, UIImageView, UILabel;

@interface SendOrderView : UIView
{
    AFHTTPRequestOperationManager *httpManager;
    UIColor *tintColor;
    NSTimer *countdownTimer;
    NSTimer *driverNotifyTimer;
    NSTimer *driverMatchTimer;
    int countdownSeconds;
    int driverNotifySeconds;
    int driverMatchSeconds;
    int lastDriverNotify;
    _Bool isMatchingDriver;
    _Bool isMatchedDriver;
    _Bool isPass120S;
    long long isShowWaitDriverConfirm;
    SimpleCustomAlertView *alertView;
    OrderCancelActionSheetView *sheet;
    CustomIOSAlertView *anyTimeNoneDriverMatchedAlertView;
    FareSelectMenuViewController *_fareSelectMenuViewController;
    CallServiceActionSheetView *contactSheet;
    TutorialView *tutorialView;
    _Bool _isSendCoupon;
    int _second;
    int _fakeInformDriverNum;
    PublishInfo *_pubInfo;
    id <MatchDriverSuccessDelegate> _delegate;
    UIView *_driverNotifyView;
    UIImageView *_driverNotifyImgView;
    UILabel *_driverNotifyCountLbl;
    UIView *_compensateCouponMsgView;
    UIImageView *_compensateCouponMsgImgView;
    UILabel *_compensateCouponMsgLbl;
    UIView *_driverBusyView;
    UIImageView *_driverBusyImgView;
    UILabel *_driverBusyLbl;
    UIView *_willingWaitingView;
    UILabel *_willingWaitingLbl;
    UIImageView *_willingWaitingImageView;
    NSString *_waitPrompt;
    UIView *_markupPriceView;
    UIButton *_markupPriceBtn;
    CountDownView *_countDownView;
    double _selectedFare;
    long long _showFareStatus;
    NSString *_fareArrayInfo;
}

@property(copy, nonatomic) NSString *fareArrayInfo; // @synthesize fareArrayInfo=_fareArrayInfo;
@property(nonatomic) long long showFareStatus; // @synthesize showFareStatus=_showFareStatus;
@property(nonatomic) double selectedFare; // @synthesize selectedFare=_selectedFare;
@property(retain, nonatomic) CountDownView *countDownView; // @synthesize countDownView=_countDownView;
@property(retain, nonatomic) UIButton *markupPriceBtn; // @synthesize markupPriceBtn=_markupPriceBtn;
@property(retain, nonatomic) UIView *markupPriceView; // @synthesize markupPriceView=_markupPriceView;
@property(nonatomic) int fakeInformDriverNum; // @synthesize fakeInformDriverNum=_fakeInformDriverNum;
@property(copy, nonatomic) NSString *waitPrompt; // @synthesize waitPrompt=_waitPrompt;
@property(nonatomic) int second; // @synthesize second=_second;
@property(nonatomic) _Bool isSendCoupon; // @synthesize isSendCoupon=_isSendCoupon;
@property(retain, nonatomic) UIImageView *willingWaitingImageView; // @synthesize willingWaitingImageView=_willingWaitingImageView;
@property(retain, nonatomic) UILabel *willingWaitingLbl; // @synthesize willingWaitingLbl=_willingWaitingLbl;
@property(retain, nonatomic) UIView *willingWaitingView; // @synthesize willingWaitingView=_willingWaitingView;
@property(retain, nonatomic) UILabel *driverBusyLbl; // @synthesize driverBusyLbl=_driverBusyLbl;
@property(retain, nonatomic) UIImageView *driverBusyImgView; // @synthesize driverBusyImgView=_driverBusyImgView;
@property(retain, nonatomic) UIView *driverBusyView; // @synthesize driverBusyView=_driverBusyView;
@property(retain, nonatomic) UILabel *compensateCouponMsgLbl; // @synthesize compensateCouponMsgLbl=_compensateCouponMsgLbl;
@property(retain, nonatomic) UIImageView *compensateCouponMsgImgView; // @synthesize compensateCouponMsgImgView=_compensateCouponMsgImgView;
@property(retain, nonatomic) UIView *compensateCouponMsgView; // @synthesize compensateCouponMsgView=_compensateCouponMsgView;
@property(retain, nonatomic) UILabel *driverNotifyCountLbl; // @synthesize driverNotifyCountLbl=_driverNotifyCountLbl;
@property(retain, nonatomic) UIImageView *driverNotifyImgView; // @synthesize driverNotifyImgView=_driverNotifyImgView;
@property(retain, nonatomic) UIView *driverNotifyView; // @synthesize driverNotifyView=_driverNotifyView;
@property(nonatomic) id <MatchDriverSuccessDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) PublishInfo *pubInfo; // @synthesize pubInfo=_pubInfo;
- (void).cxx_destruct;
- (void)showTutorialViewWithTutorialType:(long long)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)cleanAllPopView;
- (void)dealloc;
- (long long)setCountDownSeconds;
- (void)orderCancelFailureWantGoBack;
- (void)remove;
- (void)showDriverNotifyView;
- (void)getCompensateCouponMsg;
- (void)showTransferError;
- (void)doTransfer;
- (void)automaticDoTransfer;
- (void)dismissContactSheet;
- (void)dismissAlertView;
- (void)setInteractivePopGestureRecognizeEnable:(_Bool)arg1;
- (void)backToRootViewActionAnimated:(_Bool)arg1;
- (void)showCancleError:(unsigned long long)arg1;
- (void)cancelOrderWithoutDriver:(unsigned long long)arg1;
- (void)cancelOrder:(CDUnknownBlockType)arg1;
- (void)cancelOrderAction;
- (void)getDriverMatch;
- (void)getPushStatistic;
- (void)getCouponsRemind;
- (void)getFakeInformDriverNum;
- (void)getFareInfoByOrderShowSelectMenu;
- (void)getChangeFare:(id)arg1;
- (void)showFareSelectMenu;
- (void)waitDriverOver15MinutesToContinue;
- (void)waitDriverOver15MinutesToCancelOrder;
- (void)removeRequest;
- (void)anyTime120SecondSendOrderFailureWithMsg:(id)arg1 image:(id)arg2;
- (void)sendOrderFailureMSG;
- (void)refreshTask;
- (void)driverMatchAction;
- (void)driverNotifyAction;
- (void)countdownAction;
- (void)removeAllTimer;
- (void)addAllTimer;
- (void)removeTimer:(id)arg1;
- (void)removeDriverMatchTimer;
- (void)addDriverMatchTimer;
- (void)removeDriverNotifyTimer;
- (void)addDriverNotifyTimer;
- (void)removeCountdownTimer;
- (void)addCountdownTimer;
- (void)callService;
- (void)moreBarButtonItemAction:(id)arg1;
- (void)setNavigationBarRightItem;
- (id)superVC;
- (void)setBlurBGView:(id)arg1;
- (void)addNeedSubView;
- (void)setupSendOrderView;
- (id)initSendOrderViewWithFrame:(struct CGRect)arg1 publishInfo:(id)arg2;

@end

