//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CustomIOSAlertView.h"

@class UIButton, UIColor, UILabel;

@interface SimpleCustomAlertView : CustomIOSAlertView
{
    UIColor *_normalCancelButtonTitleColor;
    UIColor *_normalOtherButtonTitleColor;
    UIColor *_highlightCancelButtonTitleColor;
    UIColor *_highlightOtherButtonTitleColor;
    UIColor *_highlightCancelButtonBackgroundColor;
    UIColor *_highlightOtherButtonBackgroundColor;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_cancelButton;
    UIButton *_otherButton;
    CDUnknownBlockType _alertViewBlock;
}

@property(copy, nonatomic) CDUnknownBlockType alertViewBlock; // @synthesize alertViewBlock=_alertViewBlock;
@property(retain, nonatomic) UIButton *otherButton; // @synthesize otherButton=_otherButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIColor *highlightOtherButtonBackgroundColor; // @synthesize highlightOtherButtonBackgroundColor=_highlightOtherButtonBackgroundColor;
@property(retain, nonatomic) UIColor *highlightCancelButtonBackgroundColor; // @synthesize highlightCancelButtonBackgroundColor=_highlightCancelButtonBackgroundColor;
@property(retain, nonatomic) UIColor *highlightOtherButtonTitleColor; // @synthesize highlightOtherButtonTitleColor=_highlightOtherButtonTitleColor;
@property(retain, nonatomic) UIColor *highlightCancelButtonTitleColor; // @synthesize highlightCancelButtonTitleColor=_highlightCancelButtonTitleColor;
@property(retain, nonatomic) UIColor *normalOtherButtonTitleColor; // @synthesize normalOtherButtonTitleColor=_normalOtherButtonTitleColor;
@property(retain, nonatomic) UIColor *normalCancelButtonTitleColor; // @synthesize normalCancelButtonTitleColor=_normalCancelButtonTitleColor;
- (void).cxx_destruct;
- (void)buttonAction:(id)arg1;
- (void)showWithSimpleCustomAlertViewBlock:(CDUnknownBlockType)arg1;
- (id)initWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 otherButtonTitle:(id)arg4;

@end

