//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SubInvoice : NSObject
{
    NSString *_subInvoiceID;
    NSString *_startPoint;
    NSString *_endPoint;
    NSString *_time;
    NSString *_price;
}

@property(retain, nonatomic) NSString *price; // @synthesize price=_price;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *endPoint; // @synthesize endPoint=_endPoint;
@property(retain, nonatomic) NSString *startPoint; // @synthesize startPoint=_startPoint;
@property(retain, nonatomic) NSString *subInvoiceID; // @synthesize subInvoiceID=_subInvoiceID;
- (void).cxx_destruct;
- (id)initWithSubInvoiceDictionary:(id)arg1;

@end

