//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface ThemeCar : NSObject
{
    int _activity_code;
    int _def_car;
    int _is_custom_only;
    int _is_def_end;
    int _is_def_start;
    int _status;
    NSString *_activity_name;
    NSArray *_carInfoArray;
    NSArray *_def_end_array;
    NSArray *_def_start_array;
    NSString *_endTime;
    NSString *_startTime;
    NSString *_name;
    NSString *_url;
    NSString *_showTime;
    NSString *_pageInfo;
}

@property(copy, nonatomic) NSString *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(copy, nonatomic) NSString *showTime; // @synthesize showTime=_showTime;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) int is_def_start; // @synthesize is_def_start=_is_def_start;
@property(nonatomic) int is_def_end; // @synthesize is_def_end=_is_def_end;
@property(nonatomic) int is_custom_only; // @synthesize is_custom_only=_is_custom_only;
@property(copy, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSArray *def_start_array; // @synthesize def_start_array=_def_start_array;
@property(copy, nonatomic) NSArray *def_end_array; // @synthesize def_end_array=_def_end_array;
@property(nonatomic) int def_car; // @synthesize def_car=_def_car;
@property(copy, nonatomic) NSArray *carInfoArray; // @synthesize carInfoArray=_carInfoArray;
@property(copy, nonatomic) NSString *activity_name; // @synthesize activity_name=_activity_name;
@property(nonatomic) int activity_code; // @synthesize activity_code=_activity_code;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

