//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ThemeCarDefAddress : NSObject
{
    NSString *_address;
    NSString *_name;
    NSString *_city;
    NSString *_longitude;
    NSString *_latitude;
    NSString *_province;
}

@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
- (void).cxx_destruct;
- (id)initWithAddress:(id)arg1 andName:(id)arg2 andCity:(id)arg3 andLongitude:(double)arg4 andLatitude:(double)arg5 andProvince:(id)arg6;
- (id)initWithThemeCarDefAddressDictionary:(id)arg1;

@end

