//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel;

@interface ToolView : UIView
{
    id <ToolViewDelegate> _delegate;
    UILabel *_titleLbl;
    UIButton *_cancelBtn;
    UIButton *_okBtn;
    UIButton *_cancelBgBtn;
    UIButton *_okBgBtn;
}

@property(nonatomic) __weak UIButton *okBgBtn; // @synthesize okBgBtn=_okBgBtn;
@property(nonatomic) __weak UIButton *cancelBgBtn; // @synthesize cancelBgBtn=_cancelBgBtn;
@property(nonatomic) __weak UIButton *okBtn; // @synthesize okBtn=_okBtn;
@property(nonatomic) __weak UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(nonatomic) id <ToolViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)buttonDidPress:(id)arg1;
- (id)initWithTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initUI;

@end

