//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TouchHelper : NSObject
{
    _Bool _isLaunchApp;
    _Bool _isActiveFrom3DTouch;
    _Bool _firstStartApp;
    unsigned long long _currentTouchType;
}

+ (id)shareInstance;
@property(nonatomic) unsigned long long currentTouchType; // @synthesize currentTouchType=_currentTouchType;
@property(nonatomic) _Bool firstStartApp; // @synthesize firstStartApp=_firstStartApp;
@property(nonatomic) _Bool isActiveFrom3DTouch; // @synthesize isActiveFrom3DTouch=_isActiveFrom3DTouch;
@property(nonatomic) _Bool isLaunchApp; // @synthesize isLaunchApp=_isLaunchApp;
- (void)hideAllAlertView;
- (id)topViewControllerWithRootViewController:(id)arg1;
- (id)topViewController;
- (void)backToRootViewController:(CDUnknownBlockType)arg1;
- (void)goLogin;
- (void)actionGoNow;
- (void)actionGoAppointment;
- (void)actionGoMyOrder;
- (void)action3DTouchByLaunchAppInMapViewController:(id)arg1;
- (void)action3DTouchWithTouchType:(id)arg1;

@end

