//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface TSCENTERReportRequest : NSObject
{
    NSString *_bizType;
    NSString *_rpcVersion;
    NSString *_os;
    NSString *_appName;
    NSString *_appVersion;
    NSString *_sdkName;
    NSString *_sdkVersion;
    NSDictionary *_bizData;
    NSString *_deviceData;
}

+ (Class)bizDataElementClass;
@property(retain, nonatomic) NSString *deviceData; // @synthesize deviceData=_deviceData;
@property(retain, nonatomic) NSDictionary *bizData; // @synthesize bizData=_bizData;
@property(retain, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(retain, nonatomic) NSString *sdkName; // @synthesize sdkName=_sdkName;
@property(retain, nonatomic) NSString *appVersion; // @synthesize appVersion=_appVersion;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *os; // @synthesize os=_os;
@property(retain, nonatomic) NSString *rpcVersion; // @synthesize rpcVersion=_rpcVersion;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
- (void).cxx_destruct;

@end

