//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TSCENTERBaseResultOpen.h"

@class NSString;

@interface TSCENTERAppListCmdResultOpen : TSCENTERBaseResultOpen
{
    _Bool _needRetry;
    NSString *_appListVer;
    NSString *_appListData;
}

@property(nonatomic) _Bool needRetry; // @synthesize needRetry=_needRetry;
@property(retain, nonatomic) NSString *appListData; // @synthesize appListData=_appListData;
@property(retain, nonatomic) NSString *appListVer; // @synthesize appListVer=_appListVer;
- (void).cxx_destruct;

@end

