//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (MLPFlatColors)
+ (id)randomFlatColorIncludeLightShades:(_Bool)arg1 darkShades:(_Bool)arg2;
+ (id)randomFlatDarkColor;
+ (id)randomFlatLightColor;
+ (id)randomFlatColor;
+ (id)flatDarkBlackColor;
+ (id)flatBlackColor;
+ (id)flatDarkWhiteColor;
+ (id)flatWhiteColor;
+ (id)flatDarkGrayColor;
+ (id)flatGrayColor;
+ (id)flatDarkOrangeColor;
+ (id)flatOrangeColor;
+ (id)flatDarkYellowColor;
+ (id)flatYellowColor;
+ (id)flatDarkPurpleColor;
+ (id)flatPurpleColor;
+ (id)flatDarkTealColor;
+ (id)flatTealColor;
+ (id)flatDarkBlueColor;
+ (id)flatBlueColor;
+ (id)flatDarkGreenColor;
+ (id)flatGreenColor;
+ (id)flatDarkRedColor;
+ (id)flatRedColor;
@end

