//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (SystemInfo)
+ (id)appName;
+ (unsigned long long)deviceSystemMajorVersion;
+ (id)appStoreVersion;
+ (id)appBundleVersion;
+ (id)appVersion;
+ (float)batteryLevel;
+ (long long)batteryState;
+ (_Bool)batteryMonitoringEnabled;
+ (float)systemVersionValue;
+ (id)systemVersion;
+ (id)systemName;
+ (id)localizedModel;
+ (id)model;
+ (id)name;
@end

