//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIBarButtonItem, UIPopoverController, UIView;

@interface UIPopoverMenuViewController : UIViewController
{
    UIPopoverController *popver;
    UIBarButtonItem *currentItem;
    id itemTarget;
    UIView *currentView;
    CDUnknownBlockType _menuSelectedBlock;
    CDUnknownBlockType _dateSelectedBlock;
    CDUnknownBlockType _pickerSelectedBlock;
    UIViewController *_currentViewController;
}

@property(retain, nonatomic) UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(copy, nonatomic) CDUnknownBlockType pickerSelectedBlock; // @synthesize pickerSelectedBlock=_pickerSelectedBlock;
@property(copy, nonatomic) CDUnknownBlockType dateSelectedBlock; // @synthesize dateSelectedBlock=_dateSelectedBlock;
@property(copy, nonatomic) CDUnknownBlockType menuSelectedBlock; // @synthesize menuSelectedBlock=_menuSelectedBlock;
- (void).cxx_destruct;
- (void)hideView;
- (void)removeHideView:(id)arg1;
- (void)handleTapRecognizer:(id)arg1;
- (void)showPopoverDate4iPhoneInView:(id)arg1 dateFormatter:(id)arg2 datePickerMode:(long long)arg3 minDate:(id)arg4 maxDate:(id)arg5 title:(id)arg6;
- (void)showPopoverDate4iPhoneInView:(id)arg1 dateFormatter:(id)arg2 minDate:(id)arg3 maxDate:(id)arg4;
- (void)showPopoverDate4iPhoneInView:(id)arg1 dateFormatter:(id)arg2 datePickerMode:(long long)arg3;
- (void)showPopoverDate4iPhoneInView:(id)arg1 datePickerMode:(long long)arg2;
- (void)showPopoverDate4iPhoneInView:(id)arg1 dateFormatter:(id)arg2;
- (void)showPopoverDate4iPhoneInView:(id)arg1;
- (id)createPicker:(id)arg1 showTitle:(id)arg2 numberOfComponents:(long long)arg3 selectedRows:(id)arg4 widthBlock:(CDUnknownBlockType)arg5 endScrollBlock:(CDUnknownBlockType)arg6 inView:(id)arg7;
- (void)showPickerMenu4iPhone:(id)arg1 numberOfComponents:(long long)arg2 selectedRows:(id)arg3 showTitle:(id)arg4 groupKey:(id)arg5 dataKey:(id)arg6 autoReset:(_Bool)arg7 widthBlock:(CDUnknownBlockType)arg8 endScrollBlock:(CDUnknownBlockType)arg9 inView:(id)arg10;
- (void)showPickerMenu4iPhone:(id)arg1 selectedRow:(long long)arg2 showTitle:(id)arg3 inView:(id)arg4;
- (void)showPickerMenu4iPhone:(id)arg1 showTitle:(id)arg2 inView:(id)arg3;
- (void)showPickerMenu4iPhone:(id)arg1 inView:(id)arg2;
- (void)hidePopover;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2 dateFormatter:(id)arg3 datePickerMode:(long long)arg4 minDate:(id)arg5 maxDate:(id)arg6;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2 dateFormatter:(id)arg3 minDate:(id)arg4 maxDate:(id)arg5;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2 dateFormatter:(id)arg3 datePickerMode:(long long)arg4;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2 datePickerMode:(long long)arg3;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2 dateFormatter:(id)arg3;
- (void)showPopoverDate4iPad:(id)arg1 inView:(id)arg2;
- (void)showPopoverTableMenu4iPad:(id)arg1 sender:(id)arg2 inView:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

