//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UILabel;

@interface UserLevelCell : UITableViewCell
{
    CDUnknownBlockType _marketBlock;
    UILabel *_LVDetailL;
    UILabel *_LV;
    UIButton *_marketBtn;
}

@property(nonatomic) __weak UIButton *marketBtn; // @synthesize marketBtn=_marketBtn;
@property(nonatomic) __weak UILabel *LV; // @synthesize LV=_LV;
@property(nonatomic) __weak UILabel *LVDetailL; // @synthesize LVDetailL=_LVDetailL;
@property(copy, nonatomic) CDUnknownBlockType marketBlock; // @synthesize marketBlock=_marketBlock;
- (void).cxx_destruct;
- (void)pointMacketBtnClicked:(id)arg1;
- (void)updateCellWithLevel:(long long)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

