//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

#import "UITextFieldDelegate.h"

@class AFHTTPRequestOperationManager, NSArray, NSDictionary, NSMutableArray, NSString, UIImageView, UILabel, UIPopoverMenuViewController, UITableViewCell, UITextField, UIView;

@interface WritingInvoiceTableViewController : SuperTableViewController <UITextFieldDelegate>
{
    NSString *_price;
    NSString *_orderID;
    _Bool _isFirstSelect;
    NSString *_title;
    NSString *_recevier;
    NSString *_mobilePhone;
    NSString *_address;
    NSString *_zipCode;
    AFHTTPRequestOperationManager *_httpManager;
    UIPopoverMenuViewController *_popoverMenuViewController;
    _Bool _isLoadingOnlineAreas;
    _Bool _needLoadOnlineAreas;
    UILabel *_priceLabel;
    UILabel *_priceDescLabel;
    UILabel *_serviceLabel;
    UITableViewCell *_serviceCell;
    UIImageView *_selectService;
    UITextField *_titleTextField;
    UITextField *_recevierTextField;
    UITextField *_mobilePhoneTextField;
    UITextField *_zipCodeTextField;
    UITextField *_areaTextField;
    UITextField *_addressTextField;
    UIView *_headerView;
    NSArray *_pickerArray;
    NSString *_context;
    NSDictionary *_areaDict;
    NSDictionary *_invoiceParamConfig;
    NSMutableArray *_selectedArray;
}

@property(retain, nonatomic) NSMutableArray *selectedArray; // @synthesize selectedArray=_selectedArray;
@property(retain, nonatomic) NSDictionary *invoiceParamConfig; // @synthesize invoiceParamConfig=_invoiceParamConfig;
@property(retain, nonatomic) NSDictionary *areaDict; // @synthesize areaDict=_areaDict;
@property(retain, nonatomic) NSString *context; // @synthesize context=_context;
@property(retain, nonatomic) NSArray *pickerArray; // @synthesize pickerArray=_pickerArray;
@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak UITextField *addressTextField; // @synthesize addressTextField=_addressTextField;
@property(nonatomic) __weak UITextField *areaTextField; // @synthesize areaTextField=_areaTextField;
@property(nonatomic) __weak UITextField *zipCodeTextField; // @synthesize zipCodeTextField=_zipCodeTextField;
@property(nonatomic) __weak UITextField *mobilePhoneTextField; // @synthesize mobilePhoneTextField=_mobilePhoneTextField;
@property(nonatomic) __weak UITextField *recevierTextField; // @synthesize recevierTextField=_recevierTextField;
@property(nonatomic) __weak UITextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(nonatomic) __weak UIImageView *selectService; // @synthesize selectService=_selectService;
@property(nonatomic) __weak UITableViewCell *serviceCell; // @synthesize serviceCell=_serviceCell;
@property(nonatomic) __weak UILabel *serviceLabel; // @synthesize serviceLabel=_serviceLabel;
@property(nonatomic) __weak UILabel *priceDescLabel; // @synthesize priceDescLabel=_priceDescLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
- (void).cxx_destruct;
- (void)backBarButtonAction:(id)arg1;
- (_Bool)checkInput;
- (void)commit;
- (void)conformButtonAction:(id)arg1;
- (void)setPrice:(id)arg1 andOrderID:(id)arg2;
- (void)dealloc;
- (void)allTextFieldResignFirstResponder;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)showAreaPickerView;
- (void)showInvoiceTypePickerView;
- (void)loadAvailableInvoiceTypeIsFrist:(_Bool)arg1;
- (void)loadOnlineAreas:(_Bool)arg1;
- (void)loadLocalAreas;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

