//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPSessionManager;

@interface XXNetWork : NSObject
{
    AFHTTPSessionManager *_manager;
}

+ (id)shareInstance;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (id)postWithURL:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 succeed:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)postWithURL:(id)arg1 parameters:(id)arg2 succeed:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)init;

@end

