//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaiduMobStat, BaiduMobStatSession, NSMutableArray, NSMutableDictionary, NSString, NSTimer;

@interface BaiduMobStatController : NSObject
{
    NSTimer *timerSendStats;
    BaiduMobStatSession *session;
    NSMutableDictionary *currentPageView;
    NSMutableArray *eventArray;
    _Bool started;
    BaiduMobStat *statTracker;
    NSString *appId;
}

+ (id)sharedController;
@property(retain, nonatomic) NSMutableArray *eventArray; // @synthesize eventArray;
@property(retain, nonatomic) BaiduMobStatSession *session; // @synthesize session;
@property(retain, nonatomic) NSTimer *timerSendStats; // @synthesize timerSendStats;
@property(readonly) _Bool started; // @synthesize started;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(retain, nonatomic) BaiduMobStat *statTracker; // @synthesize statTracker;
- (void)dealloc;
- (void)resetLastVisitPageViewName;
- (id)getLastVisitPageViewName;
- (void)recordLastVistePageViewName:(id)arg1;
- (void)logEvent:(id)arg1 eventLabel:(id)arg2;
- (void)logEventWithDurationTime:(id)arg1 eventLabel:(id)arg2 durationTime:(unsigned long long)arg3;
- (void)logEventEnd:(id)arg1 eventLabel:(id)arg2;
- (void)logEventStart:(id)arg1 eventLabel:(id)arg2;
- (void)endPageView:(id)arg1 syncToCache:(_Bool)arg2;
- (void)startPageView:(id)arg1;
- (void)endSession;
- (void)startSession;
- (void)startSendTimer;
- (void)successSendLong:(id)arg1;
- (void)sendLog;
- (id)init;
- (void)startWithLastPageView;
- (void)enteredForeground:(id)arg1;
- (void)enteredBackground:(id)arg1;
- (void)checkAppKey;

@end

