//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, CustomIOSAlertView, Login, NSTimer, UIButton, UITapGestureRecognizer, UITextField, YearMonthViewController;

@interface BandCreditCardViewController : SuperTableViewController
{
    NSTimer *codeTimer;
    int limitTime;
    Login *login;
    AFHTTPRequestOperationManager *httpManager;
    UITapGestureRecognizer *_tapGestureRecognizer;
    CustomIOSAlertView *_alertView;
    id <BandCreditCardDelegate> _delegate;
    UITextField *_creditCardField;
    UITextField *_validDateField;
    UITextField *_cvn2Field;
    UITextField *_nameField;
    UITextField *_IDCardFeild;
    UITextField *_phoneField;
    UITextField *_verificationCodeField;
    UIButton *_codeBtn;
    UIButton *_useBtn;
    YearMonthViewController *_yearMonthViewController;
}

@property(retain, nonatomic) YearMonthViewController *yearMonthViewController; // @synthesize yearMonthViewController=_yearMonthViewController;
@property(nonatomic) __weak UIButton *useBtn; // @synthesize useBtn=_useBtn;
@property(nonatomic) __weak UIButton *codeBtn; // @synthesize codeBtn=_codeBtn;
@property(nonatomic) __weak UITextField *verificationCodeField; // @synthesize verificationCodeField=_verificationCodeField;
@property(nonatomic) __weak UITextField *phoneField; // @synthesize phoneField=_phoneField;
@property(nonatomic) __weak UITextField *IDCardFeild; // @synthesize IDCardFeild=_IDCardFeild;
@property(nonatomic) __weak UITextField *nameField; // @synthesize nameField=_nameField;
@property(nonatomic) __weak UITextField *cvn2Field; // @synthesize cvn2Field=_cvn2Field;
@property(nonatomic) __weak UITextField *validDateField; // @synthesize validDateField=_validDateField;
@property(nonatomic) __weak UITextField *creditCardField; // @synthesize creditCardField=_creditCardField;
@property(nonatomic) id <BandCreditCardDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)showYearMonthView;
- (void)timeCountdown;
- (void)removeTimer;
- (void)addTimer;
- (void)setCodeBtnIsEnable;
- (void)setUseButtonIsEnable;
- (void)bindCard;
- (void)getInviteCode;
- (void)backBarButtonAction:(id)arg1;
- (void)hideKeyboard;
- (void)touchOutAlert:(id)arg1;
- (void)showAlertView:(id)arg1;
- (void)clickCVV2Help;
- (void)clickValidDate;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)testData;
- (void)viewDidLoad;

@end

