//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface BankIconInfo : NSObject
{
    NSString *_iconMD5;
    NSString *_bankName;
    NSString *_bankcode;
    NSString *_iconUrl;
}

@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *bankcode; // @synthesize bankcode=_bankcode;
@property(retain, nonatomic) NSString *bankName; // @synthesize bankName=_bankName;
@property(retain, nonatomic) NSString *iconMD5; // @synthesize iconMD5=_iconMD5;
- (void).cxx_destruct;

@end

