//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, NSMutableArray, NSString;

@interface BankCardTableViewController : SuperTableViewController
{
    NSMutableArray *_bankCardArray;
    AFHTTPRequestOperationManager *_httpManager;
    NSString *_customId;
    _Bool _isModelMode;
}

+ (void)initBankCardViewInViewController:(id)arg1 withIsModelMode:(_Bool)arg2;
@property(nonatomic) _Bool isModelMode; // @synthesize isModelMode=_isModelMode;
- (void).cxx_destruct;
- (void)setupAddBankCardFooterView;
- (void)postNotification;
- (void)bindingSuccess;
- (void)bankCardBindingSucess;
- (void)bandCreditCardView:(id)arg1 isSuccess:(_Bool)arg2 message:(id)arg3;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)setupNoneBankCardBackground;
- (void)setupViewData;
- (void)willPresentActionSheet:(id)arg1;
- (void)deleteWithIndexPath:(id)arg1;
- (void)bindUPPay;
- (void)bindYeePay;
- (void)addBankCardBarButtonAction:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)bankCardCell:(id)arg1 didPressDeleteBtn:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

