//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class UITextView;

@interface BindAlipayDiscriptionViewController : SuperViewController
{
    UITextView *_textview;
}

@property(nonatomic) __weak UITextView *textview; // @synthesize textview=_textview;
- (void).cxx_destruct;
- (void)setBlurBGView:(id)arg1;
- (void)backAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

