//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LABaseRequest.h"

@interface BPushBaseRequest : LABaseRequest
{
}

- (void)handleError:(id)arg1 callBack:(CDUnknownBlockType)arg2;

@end

