//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LABaseManager.h"

@class NSMutableDictionary;

@interface BPushSettingManager : LABaseManager
{
    NSMutableDictionary *_settings;
}

@property(retain, nonatomic) NSMutableDictionary *settings; // @synthesize settings=_settings;
- (void).cxx_destruct;
- (void)setSetting:(id)arg1 forType:(long long)arg2;
- (id)getSetting:(long long)arg1;
- (id)settingKeyForType:(long long)arg1;
- (void)setup;
- (id)init;

@end

