//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct BMMapMsgObserver {
    CDUnknownFunctionPointerType *_field1;
};

struct BMMapStatus {
    double fLevel;
    double fRotation;
    double fOverlooking;
    struct BMPoint ptCenter;
    struct BMQuadrangle mapRound;
    struct BMRect winRound;
    double centerXoffset;
    double centerYoffset;
};

struct BMPoint {
    double x;
    double y;
};

struct BMQuadrangle {
    struct BMPoint lb;
    struct BMPoint lt;
    struct BMPoint rt;
    struct BMPoint rb;
};

struct BMRect {
    long long left;
    long long right;
    long long top;
    long long bottom;
};

struct CATransform3D {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
    double _field10;
    double _field11;
    double _field12;
    double _field13;
    double _field14;
    double _field15;
    double _field16;
};

struct CAssoc;

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct CMapGesture {
    CDUnknownFunctionPointerType *_vptr$CMapGesture;
    int m_bMouseDown;
    struct CVPoint m_ptMove;
    struct CVPoint m_ptUp;
    struct CVPoint m_ptDown;
    unsigned long long m_LastDownTime;
    float m_level;
    struct CVArray<tag_PaoPaoAttribute, tag_PaoPaoAttribute &> m_PaopaoAtt;
    struct IVMapbaseInterface *m_mapControl;
    float m_minZoomLevel;
    float m_maxZoomLevel;
};

struct CMapModeEngine {
    CDUnknownFunctionPointerType *_vptr$CMapModeEngine;
    struct IVMapbaseInterface *m_mapControl;
};

struct CSearchInterface {
    CDUnknownFunctionPointerType *_field1;
};

struct CVArray<_baidu_vi::CVBundle, _baidu_vi::CVBundle &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVBundle *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
};

struct CVArray<_baidu_vi::CVString, _baidu_vi::CVString &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVString *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
};

struct CVArray<tag_PaoPaoAttribute, tag_PaoPaoAttribute &> {
    CDUnknownFunctionPointerType *_vptr$CVArray;
    struct tag_PaoPaoAttribute *m_pData;
    int m_iSize;
    int m_iMaxSize;
    int m_iGrowBy;
    int m_iTemp;
};

struct CVBundle {
    struct CVMapStringToPtr _field1;
};

struct CVGpsDetailInfo {
    int _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    unsigned short _field8;
    unsigned short _field9;
    struct tagVTime _field10;
    int _field11;
};

struct CVMapStringToPtr {
    CDUnknownFunctionPointerType *_field1;
    struct CAssoc **_field2;
    unsigned int _field3;
    int _field4;
    struct CAssoc *_field5;
    int _field6;
    struct CVPlex *_field7;
};

struct CVPlex;

struct CVPoint {
    int x;
    int y;
};

struct CVString {
    CDUnknownFunctionPointerType *_field1;
    unsigned short *_field2;
};

struct IVMapbaseInterface {
    CDUnknownFunctionPointerType *_field1;
};

struct NSDictionary {
    Class _field1;
};

struct PLCrashHostInfoVersion {
    unsigned long long major;
    unsigned long long minor;
    unsigned long long revision;
};

struct PLCrashReporterCallbacks {
    unsigned short _field1;
    void *_field2;
    CDUnknownFunctionPointerType _field3;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct UPPasswordTool {
    struct UPXProguardUtil *_field1;
    struct UPXPasswordUtil *_field2;
    int _field3;
};

struct UPXPasswordUtil;

struct UPXProguardUtil {
    int _field1;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _PLCrashReportDecoder {
    struct _Plcrash__CrashReport *_field1;
};

struct _Plcrash__CrashReport {
    struct _ProtobufCMessage _field1;
    struct _Plcrash__CrashReport__SystemInfo *_field2;
    struct _Plcrash__CrashReport__ApplicationInfo *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Thread **_field5;
    unsigned long long _field6;
    struct _Plcrash__CrashReport__BinaryImage **_field7;
    struct _Plcrash__CrashReport__Exception *_field8;
    struct _Plcrash__CrashReport__Signal *_field9;
    struct _Plcrash__CrashReport__ProcessInfo *_field10;
    struct _Plcrash__CrashReport__MachineInfo *_field11;
    struct _Plcrash__CrashReport__ReportInfo *_field12;
};

struct _Plcrash__CrashReport__ApplicationInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
};

struct _Plcrash__CrashReport__BinaryImage;

struct _Plcrash__CrashReport__Exception {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Thread__StackFrame **_field5;
};

struct _Plcrash__CrashReport__MachineInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    struct _Plcrash__CrashReport__Processor *_field3;
    unsigned int _field4;
    unsigned int _field5;
};

struct _Plcrash__CrashReport__ProcessInfo {
    struct _ProtobufCMessage _field1;
    char *_field2;
    unsigned int _field3;
    char *_field4;
    char *_field5;
    unsigned int _field6;
    int _field7;
    int _field8;
    unsigned long long _field9;
};

struct _Plcrash__CrashReport__Processor {
    struct _ProtobufCMessage _field1;
    int _field2;
    int _field3;
    unsigned long long _field4;
    unsigned long long _field5;
};

struct _Plcrash__CrashReport__ReportInfo;

struct _Plcrash__CrashReport__Signal {
    struct _ProtobufCMessage _field1;
    char *_field2;
    char *_field3;
    unsigned long long _field4;
    struct _Plcrash__CrashReport__Signal__MachException *_field5;
};

struct _Plcrash__CrashReport__Signal__MachException {
    struct _ProtobufCMessage _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long *_field4;
};

struct _Plcrash__CrashReport__Symbol {
    struct _ProtobufCMessage _field1;
    char *_field2;
    unsigned long long _field3;
    int _field4;
    unsigned long long _field5;
};

struct _Plcrash__CrashReport__SystemInfo {
    struct _ProtobufCMessage _field1;
    int _field2;
    int _field3;
    char *_field4;
    int _field5;
    long long _field6;
    char *_field7;
};

struct _Plcrash__CrashReport__Thread;

struct _Plcrash__CrashReport__Thread__StackFrame {
    struct _ProtobufCMessage _field1;
    unsigned long long _field2;
    struct _Plcrash__CrashReport__Symbol *_field3;
};

struct _ProtobufCMessage {
    struct _ProtobufCMessageDescriptor *_field1;
    unsigned int _field2;
    struct _ProtobufCMessageUnknownField *_field3;
};

struct _ProtobufCMessageDescriptor;

struct _ProtobufCMessageUnknownField;

struct _utils {
    CDUnknownFunctionPointerType _field1;
};

struct bignum_st;

struct bn_blinding_st;

struct bn_mont_ctx_st;

struct crypto_ex_data_st {
    struct stack_st_void *_field1;
    int _field2;
};

struct engine_st;

struct in_addr {
    unsigned int _field1;
};

struct internal_state;

struct plcrash_exception_server_context {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    CDUnknownFunctionPointerType _field5;
    void *_field6;
    struct _opaque_pthread_mutex_t {
        long long _field1;
        char _field2[56];
    } _field7;
    struct _opaque_pthread_cond_t {
        long long _field1;
        char _field2[40];
    } _field8;
    unsigned int _field9;
    _Bool _field10;
};

struct plcrash_mach_exception_port_set {
    unsigned int count;
    unsigned int masks[13];
    unsigned int ports[13];
    int behaviors[13];
    int flavors[13];
};

struct rsa_meth_st;

struct rsa_st {
    int _field1;
    long long _field2;
    struct rsa_meth_st *_field3;
    struct engine_st *_field4;
    struct bignum_st *_field5;
    struct bignum_st *_field6;
    struct bignum_st *_field7;
    struct bignum_st *_field8;
    struct bignum_st *_field9;
    struct bignum_st *_field10;
    struct bignum_st *_field11;
    struct bignum_st *_field12;
    struct crypto_ex_data_st _field13;
    int _field14;
    int _field15;
    struct bn_mont_ctx_st *_field16;
    struct bn_mont_ctx_st *_field17;
    struct bn_mont_ctx_st *_field18;
    char *_field19;
    struct bn_blinding_st *_field20;
    struct bn_blinding_st *_field21;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct stack_st_void;

struct tagVTime {
    union {
        struct {
            unsigned long long _field1;
            unsigned int :4;
            unsigned int :5;
            unsigned int :5;
            unsigned int :6;
            unsigned int :6;
            unsigned int :6;
        } _field1;
        unsigned long long _field2;
        unsigned long long _field3;
    } _field1;
};

struct tag_PaoPaoAttribute;

struct timeval {
    long long tv_sec;
    int tv_usec;
};

struct tm {
    int _field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    int _field7;
    int _field8;
    int _field9;
    long long _field10;
    char *_field11;
};

struct z_stream_s {
    char *next_in;
    unsigned int avail_in;
    unsigned long long total_in;
    char *next_out;
    unsigned int avail_out;
    unsigned long long total_out;
    char *msg;
    struct internal_state *state;
    CDUnknownFunctionPointerType zalloc;
    CDUnknownFunctionPointerType zfree;
    void *opaque;
    int data_type;
    unsigned long long adler;
    unsigned long long reserved;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    int _field1;
    int _field2;
    int _field3;
} CDStruct_77932685;

typedef struct {
    long long _field1;
    void *_field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    CDUnknownFunctionPointerType _field5;
} CDStruct_e097db04;

typedef struct {
    long long _field1;
    long long _field2;
} CDStruct_912cb5d2;

typedef struct {
    struct CLLocationCoordinate2D _field1;
    struct {
        double _field1;
        double _field2;
    } _field2;
} CDStruct_26e8d939;

// Ambiguous groups
typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    double latitude;
    double longitude;
} CDStruct_2c43369c;

typedef struct {
    struct {
        double _field1;
        double _field2;
    } _field1;
    struct {
        double _field1;
        double _field2;
    } _field2;
} CDStruct_90e2a262;

typedef struct {
    CDStruct_2c43369c northEast;
    CDStruct_2c43369c southWest;
} CDStruct_dafdc2cb;

typedef struct {
    struct {
        double x;
        double y;
    } origin;
    struct {
        double width;
        double height;
    } size;
} CDStruct_02837cd9;

typedef struct CVArray<_baidu_vi::CVBundle, _baidu_vi::CVBundle &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVBundle *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
} CVArray_4812fe32;

typedef struct CVArray<_baidu_vi::CVString, _baidu_vi::CVString &> {
    CDUnknownFunctionPointerType *_field1;
    struct CVString *_field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
} CVArray_59d409db;

