//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class ChargeStandard, NSString;

@interface CityServicesCar : NSObject <NSCoding, NSCopying>
{
    long long _serviceType;
    long long _orderBy;
    long long _carTypeId;
    long long _cityId;
    NSString *_carTypeName;
    ChargeStandard *_chargeStandard;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(retain, nonatomic) ChargeStandard *chargeStandard; // @synthesize chargeStandard=_chargeStandard;
@property(copy, nonatomic) NSString *carTypeName; // @synthesize carTypeName=_carTypeName;
@property(nonatomic) long long cityId; // @synthesize cityId=_cityId;
@property(nonatomic) long long carTypeId; // @synthesize carTypeId=_carTypeId;
@property(nonatomic) long long orderBy; // @synthesize orderBy=_orderBy;
@property(nonatomic) long long serviceType; // @synthesize serviceType=_serviceType;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

