//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface Coupon : NSObject
{
    int _couponID;
    int _cityID;
    int _status;
    int _selectDefault;
    NSString *_cityName;
    NSString *_getTime;
    NSString *_couponName;
    NSString *_priceString;
    double _priceDouble;
    NSString *_startTime;
    NSString *_endTime;
    NSString *_remark;
    NSString *_detail;
}

@property(nonatomic) int selectDefault; // @synthesize selectDefault=_selectDefault;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) int status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double priceDouble; // @synthesize priceDouble=_priceDouble;
@property(copy, nonatomic) NSString *priceString; // @synthesize priceString=_priceString;
@property(copy, nonatomic) NSString *couponName; // @synthesize couponName=_couponName;
@property(copy, nonatomic) NSString *getTime; // @synthesize getTime=_getTime;
@property(copy, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(nonatomic) int cityID; // @synthesize cityID=_cityID;
@property(nonatomic) int couponID; // @synthesize couponID=_couponID;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

