//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CADisplayLink, UIImage;

@interface CoustomProgressImageView : UIView
{
    UIImage *_image;
    CADisplayLink *_frameTimer;
    double _angle;
}

@property(nonatomic) double angle; // @synthesize angle=_angle;
@property(retain, nonatomic) CADisplayLink *frameTimer; // @synthesize frameTimer=_frameTimer;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (void)displayUpdate:(id)arg1;
- (void)startProgress;
- (void)stopProgress;
- (void)dealloc;
- (void)appEnterForeground;
- (void)appEnterBackground;
- (id)init;

@end

