//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIButton, UIWebView;

@interface CustomWebViewController : SuperViewController <UIWebViewDelegate>
{
    UIButton *closeButton;
    NSString *_rootTitle;
    NSString *_urlString;
    UIWebView *_webView;
}

+ (void)initWebViewController:(id)arg1 withIsModelMode:(_Bool)arg2 urlString:(id)arg3 rootTitle:(id)arg4;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(copy, nonatomic) NSString *rootTitle; // @synthesize rootTitle=_rootTitle;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)close;
- (void)back;
- (void)hiddenCloseItem;
- (void)showCloseItem;
- (void)initViews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

