//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DiscountCoupon : NSObject
{
    int _activityId;
    int _defaultSelect;
    int _maxDeduction;
    int _orderId;
    int _quota;
    int _status;
    int _youhuiId;
    int _youhuiType;
    int _willPxpireDay;
    int _isWillPxpire;
    NSString *_endDate;
    double _faceValue;
    NSString *_faceValueString;
    double _discountRate;
    NSString *_discountRateString;
    NSString *_getTime;
    NSString *_limitCityIds;
    NSString *_limitCityNames;
    NSString *_limitMoneyStr;
    NSString *_limitTimeStr;
    NSString *_startDate;
    NSString *_useRulesStr;
    NSString *_youhuiName;
    double _youhuiPrice;
    double _needPayPrice;
    NSString *_willPxpireStr;
}

@property(nonatomic) int isWillPxpire; // @synthesize isWillPxpire=_isWillPxpire;
@property(nonatomic) int willPxpireDay; // @synthesize willPxpireDay=_willPxpireDay;
@property(copy, nonatomic) NSString *willPxpireStr; // @synthesize willPxpireStr=_willPxpireStr;
@property(nonatomic) double needPayPrice; // @synthesize needPayPrice=_needPayPrice;
@property(nonatomic) double youhuiPrice; // @synthesize youhuiPrice=_youhuiPrice;
@property(nonatomic) int youhuiType; // @synthesize youhuiType=_youhuiType;
@property(copy, nonatomic) NSString *youhuiName; // @synthesize youhuiName=_youhuiName;
@property(nonatomic) int youhuiId; // @synthesize youhuiId=_youhuiId;
@property(copy, nonatomic) NSString *useRulesStr; // @synthesize useRulesStr=_useRulesStr;
@property(nonatomic) int status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) int quota; // @synthesize quota=_quota;
@property(nonatomic) int orderId; // @synthesize orderId=_orderId;
@property(nonatomic) int maxDeduction; // @synthesize maxDeduction=_maxDeduction;
@property(copy, nonatomic) NSString *limitTimeStr; // @synthesize limitTimeStr=_limitTimeStr;
@property(copy, nonatomic) NSString *limitMoneyStr; // @synthesize limitMoneyStr=_limitMoneyStr;
@property(copy, nonatomic) NSString *limitCityNames; // @synthesize limitCityNames=_limitCityNames;
@property(copy, nonatomic) NSString *limitCityIds; // @synthesize limitCityIds=_limitCityIds;
@property(copy, nonatomic) NSString *getTime; // @synthesize getTime=_getTime;
@property(copy, nonatomic) NSString *discountRateString; // @synthesize discountRateString=_discountRateString;
@property(nonatomic) double discountRate; // @synthesize discountRate=_discountRate;
@property(copy, nonatomic) NSString *faceValueString; // @synthesize faceValueString=_faceValueString;
@property(nonatomic) double faceValue; // @synthesize faceValue=_faceValue;
@property(copy, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(nonatomic) int defaultSelect; // @synthesize defaultSelect=_defaultSelect;
@property(nonatomic) int activityId; // @synthesize activityId=_activityId;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

