//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "BMKMapViewDelegate.h"
#import "BMKRouteSearchDelegate.h"

@class AFHTTPRequestOperationManager, BMKMapView, BMKRouteSearch, NSString, NSTimer, RouteAnnotation;

@interface DriverLocationViewController : SuperViewController <BMKMapViewDelegate, BMKRouteSearchDelegate>
{
    BMKMapView *_mapView;
    AFHTTPRequestOperationManager *_httpManager;
    BMKRouteSearch *_routeSearcher;
    double _startLatitude;
    double _startLongitude;
    double _endLatitude;
    double _endLongitude;
    long long _driverID;
    RouteAnnotation *driverAnnotation;
    NSTimer *reloadDriverLoactionTimer;
    int cityID;
}

@property int cityID; // @synthesize cityID;
- (void).cxx_destruct;
- (void)removeTimer;
- (void)addTimer;
- (void)refreshDriverLocation:(id)arg1;
- (void)displayOrderRoute;
- (void)setStartLatitude:(double)arg1 andStartLongitude:(double)arg2 andEndLatitude:(double)arg3 andEndLongitude:(double)arg4 andDriverID:(long long)arg5;
- (void)getDriverPosition;
- (void)backBarButtonAction:(id)arg1;
- (void)onGetDrivingRouteResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (id)getRouteAnnotationView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

