//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, NSMutableArray;

@interface DriverCollectionTableViewController : SuperTableViewController
{
    NSMutableArray *_driverCollectionArray;
    AFHTTPRequestOperationManager *_httpManager;
    NSMutableArray *_driverImageArray;
}

- (void).cxx_destruct;
- (void)editBarButtonAction:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)setupBackground;
- (void)setupViewData;
- (void)deleteDirverInTableVieW:(id)arg1 forRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)createDeleteButton:(id)arg1 indexPath:(id)arg2 inCell:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setNavigationBarRightItem;
- (void)viewDidLoad;
- (id)initWithStyle:(long long)arg1;

@end

