//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EstimateResult : NSObject
{
    _Bool _isPackage;
    _Bool _isLow;
    _Bool _canSelectCoupons;
    int _carTypeId;
    int _nightServiceMode;
    int _nightServiceTime_seconds;
    int _nightServiceTime_chargedDuration_mins;
    int _totalCoupons;
    double _totalCost;
    double _estimateSum;
    double _basePrice;
    double _packagePrice;
    double _packageTotalPrice;
    double _packageKM;
    double _packageTime;
    long long _packageBuyLogId;
    long long _packageDetailId;
    NSString *_packageOverKmStr;
    double _packageOverKmPrice;
    double _totalPriceSiji;
    NSString *_packageKmStr;
    NSString *_packageKmNumStr;
    NSString *_basePriceDesc;
    double _mileageCost;
    double _mileage;
    double _mileagePrice;
    NSString *_mileageCostDesc;
    double _overMileageCost;
    double _overMileage;
    double _overMileagePrice;
    NSString *_overMileageCostDesc;
    double _timeCost;
    double _time;
    double _timePrice;
    NSString *_timeCostDesc;
    double _overTimeCost;
    double _overTime;
    double _overTimePrice;
    NSString *_overTimeCostDesc;
    double _nightFee;
    NSString *_nightStart;
    NSString *_nightEnd;
    NSString *_nightFeeDesc;
    NSString *_nightFeeStartToEnd;
    NSString *_priceFloatRate;
    NSString *_priceFloatRateTxt;
    NSString *_floatAddPriceTitle;
    double _floatAddPrice;
    NSString *_floatAddPriceTxt;
    NSString *_floatAddPriceDesc;
    NSString *_priceTag;
    NSString *_adjustmentConfirmStr;
    NSString *_adjustmentIdo;
    NSString *_adjustmentIno;
    NSString *_adjustmentPrice;
    NSString *_adjustmentRateB;
    NSString *_adjustmentRateO;
    double _adjustmentRateT;
    NSString *_adjustmentRemarkStr;
    double _lowConsumption;
    double _nightServiceTimeUnitPrice;
    double _max_yh_money;
    NSString *_maxYhMoneyDes;
    NSString *_couponsStatisticsStr;
    NSString *_fareInfo;
    double _farePrice;
    NSString *_entDiscountRate;
}

@property(copy, nonatomic) NSString *entDiscountRate; // @synthesize entDiscountRate=_entDiscountRate;
@property(nonatomic) double farePrice; // @synthesize farePrice=_farePrice;
@property(copy, nonatomic) NSString *fareInfo; // @synthesize fareInfo=_fareInfo;
@property(copy, nonatomic) NSString *couponsStatisticsStr; // @synthesize couponsStatisticsStr=_couponsStatisticsStr;
@property(copy, nonatomic) NSString *maxYhMoneyDes; // @synthesize maxYhMoneyDes=_maxYhMoneyDes;
@property(nonatomic) double max_yh_money; // @synthesize max_yh_money=_max_yh_money;
@property(nonatomic) int totalCoupons; // @synthesize totalCoupons=_totalCoupons;
@property(nonatomic) _Bool canSelectCoupons; // @synthesize canSelectCoupons=_canSelectCoupons;
@property(nonatomic) int nightServiceTime_chargedDuration_mins; // @synthesize nightServiceTime_chargedDuration_mins=_nightServiceTime_chargedDuration_mins;
@property(nonatomic) int nightServiceTime_seconds; // @synthesize nightServiceTime_seconds=_nightServiceTime_seconds;
@property(nonatomic) double nightServiceTimeUnitPrice; // @synthesize nightServiceTimeUnitPrice=_nightServiceTimeUnitPrice;
@property(nonatomic) int nightServiceMode; // @synthesize nightServiceMode=_nightServiceMode;
@property(nonatomic) _Bool isLow; // @synthesize isLow=_isLow;
@property(nonatomic) double lowConsumption; // @synthesize lowConsumption=_lowConsumption;
@property(copy, nonatomic) NSString *adjustmentRemarkStr; // @synthesize adjustmentRemarkStr=_adjustmentRemarkStr;
@property(nonatomic) double adjustmentRateT; // @synthesize adjustmentRateT=_adjustmentRateT;
@property(copy, nonatomic) NSString *adjustmentRateO; // @synthesize adjustmentRateO=_adjustmentRateO;
@property(copy, nonatomic) NSString *adjustmentRateB; // @synthesize adjustmentRateB=_adjustmentRateB;
@property(copy, nonatomic) NSString *adjustmentPrice; // @synthesize adjustmentPrice=_adjustmentPrice;
@property(copy, nonatomic) NSString *adjustmentIno; // @synthesize adjustmentIno=_adjustmentIno;
@property(copy, nonatomic) NSString *adjustmentIdo; // @synthesize adjustmentIdo=_adjustmentIdo;
@property(copy, nonatomic) NSString *adjustmentConfirmStr; // @synthesize adjustmentConfirmStr=_adjustmentConfirmStr;
@property(copy, nonatomic) NSString *priceTag; // @synthesize priceTag=_priceTag;
@property(copy, nonatomic) NSString *floatAddPriceDesc; // @synthesize floatAddPriceDesc=_floatAddPriceDesc;
@property(copy, nonatomic) NSString *floatAddPriceTxt; // @synthesize floatAddPriceTxt=_floatAddPriceTxt;
@property(nonatomic) double floatAddPrice; // @synthesize floatAddPrice=_floatAddPrice;
@property(copy, nonatomic) NSString *floatAddPriceTitle; // @synthesize floatAddPriceTitle=_floatAddPriceTitle;
@property(retain, nonatomic) NSString *priceFloatRateTxt; // @synthesize priceFloatRateTxt=_priceFloatRateTxt;
@property(retain, nonatomic) NSString *priceFloatRate; // @synthesize priceFloatRate=_priceFloatRate;
@property(retain, nonatomic) NSString *nightFeeStartToEnd; // @synthesize nightFeeStartToEnd=_nightFeeStartToEnd;
@property(retain, nonatomic) NSString *nightFeeDesc; // @synthesize nightFeeDesc=_nightFeeDesc;
@property(retain, nonatomic) NSString *nightEnd; // @synthesize nightEnd=_nightEnd;
@property(retain, nonatomic) NSString *nightStart; // @synthesize nightStart=_nightStart;
@property(nonatomic) double nightFee; // @synthesize nightFee=_nightFee;
@property(retain, nonatomic) NSString *overTimeCostDesc; // @synthesize overTimeCostDesc=_overTimeCostDesc;
@property(nonatomic) double overTimePrice; // @synthesize overTimePrice=_overTimePrice;
@property(nonatomic) double overTime; // @synthesize overTime=_overTime;
@property(nonatomic) double overTimeCost; // @synthesize overTimeCost=_overTimeCost;
@property(retain, nonatomic) NSString *timeCostDesc; // @synthesize timeCostDesc=_timeCostDesc;
@property(nonatomic) double timePrice; // @synthesize timePrice=_timePrice;
@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) double timeCost; // @synthesize timeCost=_timeCost;
@property(retain, nonatomic) NSString *overMileageCostDesc; // @synthesize overMileageCostDesc=_overMileageCostDesc;
@property(nonatomic) double overMileagePrice; // @synthesize overMileagePrice=_overMileagePrice;
@property(nonatomic) double overMileage; // @synthesize overMileage=_overMileage;
@property(nonatomic) double overMileageCost; // @synthesize overMileageCost=_overMileageCost;
@property(retain, nonatomic) NSString *mileageCostDesc; // @synthesize mileageCostDesc=_mileageCostDesc;
@property(nonatomic) double mileagePrice; // @synthesize mileagePrice=_mileagePrice;
@property(nonatomic) double mileage; // @synthesize mileage=_mileage;
@property(nonatomic) double mileageCost; // @synthesize mileageCost=_mileageCost;
@property(retain, nonatomic) NSString *basePriceDesc; // @synthesize basePriceDesc=_basePriceDesc;
@property(copy, nonatomic) NSString *packageKmNumStr; // @synthesize packageKmNumStr=_packageKmNumStr;
@property(copy, nonatomic) NSString *packageKmStr; // @synthesize packageKmStr=_packageKmStr;
@property(nonatomic) double totalPriceSiji; // @synthesize totalPriceSiji=_totalPriceSiji;
@property(nonatomic) double packageOverKmPrice; // @synthesize packageOverKmPrice=_packageOverKmPrice;
@property(copy, nonatomic) NSString *packageOverKmStr; // @synthesize packageOverKmStr=_packageOverKmStr;
@property(nonatomic) long long packageDetailId; // @synthesize packageDetailId=_packageDetailId;
@property(nonatomic) long long packageBuyLogId; // @synthesize packageBuyLogId=_packageBuyLogId;
@property(nonatomic) double packageTime; // @synthesize packageTime=_packageTime;
@property(nonatomic) double packageKM; // @synthesize packageKM=_packageKM;
@property(nonatomic) double packageTotalPrice; // @synthesize packageTotalPrice=_packageTotalPrice;
@property(nonatomic) double packagePrice; // @synthesize packagePrice=_packagePrice;
@property(nonatomic) _Bool isPackage; // @synthesize isPackage=_isPackage;
@property(nonatomic) double basePrice; // @synthesize basePrice=_basePrice;
@property(nonatomic) double estimateSum; // @synthesize estimateSum=_estimateSum;
@property(nonatomic) double totalCost; // @synthesize totalCost=_totalCost;
@property(nonatomic) int carTypeId; // @synthesize carTypeId=_carTypeId;
- (void).cxx_destruct;

@end

