//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, InvoiceDetail, UILabel, UITableViewCell, UIView;

@interface InfoOfInvoicedTableViewController : SuperTableViewController
{
    long long _invoiceID;
    InvoiceDetail *_invoiceDetail;
    AFHTTPRequestOperationManager *_httpManager;
    UILabel *_priceLabel;
    UILabel *_titleLabel;
    UILabel *_serviceLabel;
    UILabel *_recevierLabel;
    UILabel *_mobilePhoneLabel;
    UILabel *_addressLabel;
    UILabel *_zipCodeLabel;
    UILabel *_courierCompanyLabel;
    UILabel *_courierNumberLabel;
    UITableViewCell *_courierCompanyCell;
    UITableViewCell *_courierNumberCell;
    UIView *_headerView;
}

@property(nonatomic) __weak UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) __weak UITableViewCell *courierNumberCell; // @synthesize courierNumberCell=_courierNumberCell;
@property(nonatomic) __weak UITableViewCell *courierCompanyCell; // @synthesize courierCompanyCell=_courierCompanyCell;
@property(nonatomic) __weak UILabel *courierNumberLabel; // @synthesize courierNumberLabel=_courierNumberLabel;
@property(nonatomic) __weak UILabel *courierCompanyLabel; // @synthesize courierCompanyLabel=_courierCompanyLabel;
@property(nonatomic) __weak UILabel *zipCodeLabel; // @synthesize zipCodeLabel=_zipCodeLabel;
@property(nonatomic) __weak UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(nonatomic) __weak UILabel *mobilePhoneLabel; // @synthesize mobilePhoneLabel=_mobilePhoneLabel;
@property(nonatomic) __weak UILabel *recevierLabel; // @synthesize recevierLabel=_recevierLabel;
@property(nonatomic) __weak UILabel *serviceLabel; // @synthesize serviceLabel=_serviceLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
- (void).cxx_destruct;
- (void)cancelInvoiced;
- (void)setupData;
- (void)setupViewData;
- (void)setInvoiceID:(long long)arg1;
- (void)backBarButtonAction:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

