//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class UIImageView;

@interface InitialViewController : SuperViewController
{
    UIImageView *_imgView;
}

@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)initMainUI;
- (void)initGuidanceView;
- (void)isFirstOpenApp;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

