//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface InviteMessage : NSObject
{
    NSString *_introduce;
    NSString *_SMS;
    NSString *_inviteCode;
}

@property(retain, nonatomic) NSString *inviteCode; // @synthesize inviteCode=_inviteCode;
@property(retain, nonatomic) NSString *SMS; // @synthesize SMS=_SMS;
@property(retain, nonatomic) NSString *introduce; // @synthesize introduce=_introduce;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

