//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface InvoiceDetail : NSObject
{
    int _status;
    int _orderNum;
    double _price;
    NSString *_title;
    NSString *_context;
    NSString *_statusString;
    NSString *_time;
    NSArray *_subInvoices;
    NSString *_postAddress;
    NSString *_recipient;
    NSString *_postNum;
    NSString *_phone;
    NSString *_courierCompany;
    NSString *_courierNumber;
}

@property(retain, nonatomic) NSString *courierNumber; // @synthesize courierNumber=_courierNumber;
@property(retain, nonatomic) NSString *courierCompany; // @synthesize courierCompany=_courierCompany;
@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSString *postNum; // @synthesize postNum=_postNum;
@property(retain, nonatomic) NSString *recipient; // @synthesize recipient=_recipient;
@property(retain, nonatomic) NSString *postAddress; // @synthesize postAddress=_postAddress;
@property(retain, nonatomic) NSArray *subInvoices; // @synthesize subInvoices=_subInvoices;
@property(nonatomic) int orderNum; // @synthesize orderNum=_orderNum;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *statusString; // @synthesize statusString=_statusString;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *context; // @synthesize context=_context;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) double price; // @synthesize price=_price;
- (void).cxx_destruct;
- (id)initWithInvoiceDetailDictionary:(id)arg1;

@end

