//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface lineHisModel : NSObject
{
    long long _cityId;
    long long _customId;
    long long _id;
    NSString *_insertTime;
    NSString *_shangChe;
    NSString *_shangCheAddress;
    double _shangCheLng;
    double _shangCheLat;
    NSString *_xiaChe;
    NSString *_xiaCheAddress;
    double _xiaCheLng;
    double _xiaCheLat;
}

@property double xiaCheLat; // @synthesize xiaCheLat=_xiaCheLat;
@property double xiaCheLng; // @synthesize xiaCheLng=_xiaCheLng;
@property(retain, nonatomic) NSString *xiaCheAddress; // @synthesize xiaCheAddress=_xiaCheAddress;
@property(retain, nonatomic) NSString *xiaChe; // @synthesize xiaChe=_xiaChe;
@property double shangCheLat; // @synthesize shangCheLat=_shangCheLat;
@property double shangCheLng; // @synthesize shangCheLng=_shangCheLng;
@property(retain, nonatomic) NSString *shangCheAddress; // @synthesize shangCheAddress=_shangCheAddress;
@property(retain, nonatomic) NSString *shangChe; // @synthesize shangChe=_shangChe;
@property(retain, nonatomic) NSString *insertTime; // @synthesize insertTime=_insertTime;
@property long long id; // @synthesize id=_id;
@property long long customId; // @synthesize customId=_customId;
@property long long cityId; // @synthesize cityId=_cityId;
- (void).cxx_destruct;
- (id)initWithParameters:(long long)arg1 andCustomId:(long long)arg2 andId:(long long)arg3 andInsertTime:(id)arg4 andShangche:(id)arg5 andShangCheAddress:(id)arg6 andShangCheLng:(double)arg7 andShangCheLat:(double)arg8 andXiaChe:(id)arg9 andXiaCheAddress:(id)arg10 andXiaCheLng:(double)arg11 andXiaCheLat:(double)arg12;

@end

