//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLPaySDKCore.h"

#import "PKPaymentAuthorizationViewControllerDelegate.h"

@class NSDictionary, NSString, PKPaymentMethod;

@interface LLAPPaySDK : LLPaySDKCore <PKPaymentAuthorizationViewControllerDelegate>
{
    _Bool _isPreAuth;
    long long _apResult;
    NSString *_apTokenJson;
    NSDictionary *_apResultDic;
    CDUnknownBlockType _resultCompletion;
    PKPaymentMethod *_finalPayMethod;
    NSString *_goodsNameStr;
}

+ (void)showWalletToBindCard;
+ (unsigned long long)canDeviceSupportApplePayPayments;
+ (id)sharedSdk;
@property(retain, nonatomic) NSString *goodsNameStr; // @synthesize goodsNameStr=_goodsNameStr;
@property(retain, nonatomic) PKPaymentMethod *finalPayMethod; // @synthesize finalPayMethod=_finalPayMethod;
@property(nonatomic) _Bool isPreAuth; // @synthesize isPreAuth=_isPreAuth;
@property(copy, nonatomic) CDUnknownBlockType resultCompletion; // @synthesize resultCompletion=_resultCompletion;
@property(retain, nonatomic) NSDictionary *apResultDic; // @synthesize apResultDic=_apResultDic;
@property(retain, nonatomic) NSString *apTokenJson; // @synthesize apTokenJson=_apTokenJson;
@property(nonatomic) long long apResult; // @synthesize apResult=_apResult;
- (void).cxx_destruct;
- (void)paymentAuthorizationViewController:(id)arg1 didSelectPaymentMethod:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)paymentAuthorizationViewController:(id)arg1 didSelectShippingContact:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)paymentAuthorizationViewController:(id)arg1 didSelectShippingMethod:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)paymentAuthorizationViewControllerDidFinish:(id)arg1;
- (void)paymentAuthorizationViewController:(id)arg1 didAuthorizePayment:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)PreAuthPay;
- (void)OneTimePay;
- (void)presentAPPay;
- (void)backToOrderWithResult:(int)arg1 withDic:(id)arg2;
- (void)receiveBackNotify:(id)arg1;
- (void)cancelListen;
- (void)notificationCenter;
- (void)sdkInit;
- (void)cleanFormerResult;
- (void)getRealPresentedVc:(id)arg1;
- (void)presentSdkAPPayInViewController:(id)arg1 withTraderInfo:(id)arg2;
- (void)preauthWithTraderInfo:(id)arg1 inViewController:(id)arg2;
- (void)payWithTraderInfo:(id)arg1 inViewController:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

