//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface LLBankInfo : NSObject
{
    NSDictionary *bankInfoDic;
    NSArray *_debitbankInfoList;
    NSArray *_creditbankInfoList;
    NSString *_bank_count;
}

+ (id)bankParamWithDebitBankID:(id)arg1;
+ (id)bankParamWithCreditBankID:(id)arg1;
+ (void)downloadBankIcon:(id)arg1;
+ (void)updateBankCardList:(id)arg1;
+ (void)updateBankCardListFromLLWalletNet:(id)arg1;
+ (int)getIdType:(id)arg1;
+ (id)getUrlDownloadIconPath:(id)arg1;
+ (id)getDownloadIconPath;
+ (id)getBankPlistPathInDocument;
+ (id)getBankVersionFromPlist;
+ (_Bool)isSuspendingCreditCardInfo:(id)arg1;
+ (_Bool)isSuspendingDebitCardInfo:(id)arg1;
+ (id)supportCreditCardList;
+ (id)supportDebitCardList;
+ (id)bankNameWithID:(id)arg1;
+ (id)bankImageIconWithBankCode:(id)arg1;
+ (id)bankIconWithID:(id)arg1;
+ (void)initBankCardInfo;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *bank_count; // @synthesize bank_count=_bank_count;
@property(retain, nonatomic) NSArray *creditbankInfoList; // @synthesize creditbankInfoList=_creditbankInfoList;
@property(retain, nonatomic) NSArray *debitbankInfoList; // @synthesize debitbankInfoList=_debitbankInfoList;
@property(retain, nonatomic) NSDictionary *bankInfoDic; // @synthesize bankInfoDic;
- (void).cxx_destruct;
- (id)init;
- (void)dealloc;

@end

