//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface LLCssRule : NSObject
{
    NSString *selectorName;
    NSMutableDictionary *declarationMap;
}

@property(readonly, nonatomic) NSMutableDictionary *declarationMap; // @synthesize declarationMap;
@property(retain, nonatomic) NSString *selectorName; // @synthesize selectorName;
- (void).cxx_destruct;
- (id)valueWithProperty:(id)arg1;
- (id)init;
- (void)dealloc;

@end

