//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLBankCard, LLGoods, LLPayProduct, LLTradeInfo, LLUser, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface LLNetSession : NSObject
{
    _Bool _hasGetVerifyPayState;
    _Bool _isUAT;
    int _sdkPayState;
    NSMutableArray *_bankCards;
    LLUser *_user;
    LLUser *_encryptUser;
    LLGoods *_goods;
    NSString *_token;
    LLBankCard *_payCard;
    NSString *_sdkToken;
    LLTradeInfo *_sdkTradeInfo;
    NSMutableArray *_sdkSupportCreditCards;
    NSMutableArray *_sdkSupportDebitCards;
    NSDictionary *_outSideAcctParms;
    NSDictionary *_firstSdkTradeInfo;
    NSString *_inputPassword;
    NSString *_flag_addinfo;
    NSMutableDictionary *_addInfoDic;
    NSString *_pay_type;
    NSString *_latitude;
    NSString *_longitude;
    LLPayProduct *_payProduct;
    NSString *_pubkey;
    NSString *_ver_pubkey;
}

+ (_Bool)isFeatureShow:(int)arg1;
+ (id)traderAcctName;
+ (id)traderIDNo;
+ (id)verificationCrad;
+ (_Bool)isUserLogin;
+ (void)clean;
+ (void)cacheBindingCards:(id)arg1;
+ (id)sharedSession;
@property(retain, nonatomic) NSString *ver_pubkey; // @synthesize ver_pubkey=_ver_pubkey;
@property(retain, nonatomic) NSString *pubkey; // @synthesize pubkey=_pubkey;
@property(retain, nonatomic) LLPayProduct *payProduct; // @synthesize payProduct=_payProduct;
@property(nonatomic) _Bool isUAT; // @synthesize isUAT=_isUAT;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(nonatomic) int sdkPayState; // @synthesize sdkPayState=_sdkPayState;
@property(nonatomic) _Bool hasGetVerifyPayState; // @synthesize hasGetVerifyPayState=_hasGetVerifyPayState;
@property(retain, nonatomic) NSString *pay_type; // @synthesize pay_type=_pay_type;
@property(retain, nonatomic) NSMutableDictionary *addInfoDic; // @synthesize addInfoDic=_addInfoDic;
@property(retain, nonatomic) NSString *flag_addinfo; // @synthesize flag_addinfo=_flag_addinfo;
@property(retain, nonatomic) NSString *inputPassword; // @synthesize inputPassword=_inputPassword;
@property(retain, nonatomic) NSDictionary *firstSdkTradeInfo; // @synthesize firstSdkTradeInfo=_firstSdkTradeInfo;
@property(retain, nonatomic) NSDictionary *outSideAcctParms; // @synthesize outSideAcctParms=_outSideAcctParms;
@property(retain, nonatomic) NSMutableArray *sdkSupportDebitCards; // @synthesize sdkSupportDebitCards=_sdkSupportDebitCards;
@property(retain, nonatomic) NSMutableArray *sdkSupportCreditCards; // @synthesize sdkSupportCreditCards=_sdkSupportCreditCards;
@property(retain, nonatomic) LLTradeInfo *sdkTradeInfo; // @synthesize sdkTradeInfo=_sdkTradeInfo;
@property(retain, nonatomic) NSString *sdkToken; // @synthesize sdkToken=_sdkToken;
@property(retain, nonatomic) LLBankCard *payCard; // @synthesize payCard=_payCard;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(retain, nonatomic) LLGoods *goods; // @synthesize goods=_goods;
@property(retain, nonatomic) LLUser *encryptUser; // @synthesize encryptUser=_encryptUser;
@property(retain, nonatomic) LLUser *user; // @synthesize user=_user;
@property(retain, nonatomic) NSMutableArray *bankCards; // @synthesize bankCards=_bankCards;
- (void).cxx_destruct;

@end

