//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLNetFormData, NSMutableDictionary, NSString;

@interface LLNetworkCommand : NSObject
{
    _Bool _needTraderNO;
    _Bool _needToken;
    _Bool _useSystemErrorAlert;
    _Bool _useNormalBussErrorAlert;
    _Bool _useSystemHold;
    _Bool _isGet;
    _Bool _testMode;
    NSString *_functionName;
    NSString *_transCode;
    NSString *_pathUrl;
    NSMutableDictionary *_paramDic;
    NSMutableDictionary *_sendingDic;
    LLNetFormData *_formData;
    CDUnknownBlockType _businessSuccessHandler;
    CDUnknownBlockType _businessErrorHandler;
    CDUnknownBlockType _errorHandler;
    NSString *_systemErrorAlertTip;
    NSString *_systemHoldTip;
    NSMutableDictionary *_specicalHandleCode;
}

+ (id)cmdWithFunc:(id)arg1;
+ (id)cmd;
@property(retain, nonatomic) NSMutableDictionary *specicalHandleCode; // @synthesize specicalHandleCode=_specicalHandleCode;
@property(nonatomic, getter=isTestMode) _Bool testMode; // @synthesize testMode=_testMode;
@property(nonatomic) _Bool isGet; // @synthesize isGet=_isGet;
@property(retain, nonatomic) NSString *systemHoldTip; // @synthesize systemHoldTip=_systemHoldTip;
@property(nonatomic) _Bool useSystemHold; // @synthesize useSystemHold=_useSystemHold;
@property(nonatomic) _Bool useNormalBussErrorAlert; // @synthesize useNormalBussErrorAlert=_useNormalBussErrorAlert;
@property(retain, nonatomic) NSString *systemErrorAlertTip; // @synthesize systemErrorAlertTip=_systemErrorAlertTip;
@property(nonatomic) _Bool useSystemErrorAlert; // @synthesize useSystemErrorAlert=_useSystemErrorAlert;
@property(copy, nonatomic) CDUnknownBlockType errorHandler; // @synthesize errorHandler=_errorHandler;
@property(copy, nonatomic) CDUnknownBlockType businessErrorHandler; // @synthesize businessErrorHandler=_businessErrorHandler;
@property(copy, nonatomic) CDUnknownBlockType businessSuccessHandler; // @synthesize businessSuccessHandler=_businessSuccessHandler;
@property(retain, nonatomic) LLNetFormData *formData; // @synthesize formData=_formData;
@property(nonatomic) _Bool needToken; // @synthesize needToken=_needToken;
@property(nonatomic) _Bool needTraderNO; // @synthesize needTraderNO=_needTraderNO;
@property(retain, nonatomic) NSMutableDictionary *sendingDic; // @synthesize sendingDic=_sendingDic;
@property(retain, nonatomic) NSMutableDictionary *paramDic; // @synthesize paramDic=_paramDic;
@property(retain, nonatomic) NSString *pathUrl; // @synthesize pathUrl=_pathUrl;
@property(retain, nonatomic) NSString *transCode; // @synthesize transCode=_transCode;
@property(retain, nonatomic) NSString *functionName; // @synthesize functionName=_functionName;
- (void).cxx_destruct;
- (int)handleResonse:(id)arg1 withCode:(id)arg2;
- (id)hostAddress;
- (void)prepareForSend;
- (id)functionInfoDic;
- (_Bool)isTestSecureMode;
- (_Bool)isGetMethod;
- (id)ver_sdk;
- (id)ver_app;
- (id)signatureTitle;
- (id)signKeyTitle;
- (id)signKey;
- (id)signature;
- (void)urlEncodeParamDic;
- (void)prepareParamDic;
- (id)LLURLEncodedString:(id)arg1;
- (id)init;
- (void)dealloc;

@end

