//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLNetworkCommand.h"

@interface LLPaymentSDKCommand : LLNetworkCommand
{
}

- (id)hostAddress;
- (id)signature;
- (id)paramStringWithKeyArray:(id)arg1;
- (id)valueWithKey:(id)arg1;
- (id)paramString;
- (int)handleResonse:(id)arg1 withCode:(id)arg2;
- (void)encrypt;
- (void)prepareForSend;
- (void)prepareParamDic;
- (id)ver_sdk;
- (id)ver_app;
- (id)signatureTitle;
- (id)signKeyTitle;
- (id)signKey;
- (id)functionInfoDic;
- (id)init;

@end

