//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface LLPayProduct : NSObject
{
    NSDictionary *_functionInfoDic;
}

+ (id)product;
+ (_Bool)isUsingPreAuthApply;
@property(retain, nonatomic) NSDictionary *functionInfoDic; // @synthesize functionInfoDic=_functionInfoDic;
- (void).cxx_destruct;
- (id)hostAdress:(_Bool)arg1;
- (id)pay_chnl;
- (_Bool)supportEncrypt;
- (id)bankWapUrl:(id)arg1;
- (_Bool)isNeedPassPayType;
- (_Bool)isMustSupportIDType;
- (_Bool)isSupportInputTip;
- (_Bool)isSuspendAgreementCanTryPay;
- (_Bool)isMustPassUserInfo;
- (_Bool)isSupportWapBankPage;
- (_Bool)isSupportDebitCard;
- (id)titleOfSubjectKey:(id)arg1;
- (_Bool)isNeedSelectUnknowBank;
- (_Bool)isIDFieldEnable;
- (id)productSubName;
- (id)productName;
- (id)productCode;
- (void)parseInitParam:(id)arg1 andResultDic:(id)arg2;
- (id)payTypeIfIsCreditCard:(_Bool)arg1;

@end

