//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UINavigationControllerDelegate.h"

@class LLNetAlert, NSMutableDictionary, NSObject<LLPaySdkDelegate>, NSString, UIViewController;

@interface LLPaySDKCore : NSObject <UINavigationControllerDelegate>
{
    UIViewController *presentController;
    _Bool enableDebugInfo;
    NSMutableDictionary *_traderBillInfo;
    NSObject<LLPaySdkDelegate> *_sdkDelegate;
    LLNetAlert *_netAlert;
}

+ (void)setLLsdkPayState:(int)arg1;
+ (void)setVerifyPayState:(_Bool)arg1;
+ (void)switchToTestServer:(_Bool)arg1;
@property(retain, nonatomic) LLNetAlert *netAlert; // @synthesize netAlert=_netAlert;
@property(nonatomic) NSObject<LLPaySdkDelegate> *sdkDelegate; // @synthesize sdkDelegate=_sdkDelegate;
@property(retain, nonatomic) NSMutableDictionary *traderBillInfo; // @synthesize traderBillInfo=_traderBillInfo;
- (void).cxx_destruct;
- (void)enableDebug;
- (void)cancelListen;
- (void)backToOrderWithResult:(int)arg1 withDic:(id)arg2;
- (void)receiveBackNotify:(id)arg1;
- (void)backToOrder;
- (void)notificationCenter;
- (void)parseSessionInfo:(id)arg1;
- (_Bool)checkDevEnvAndParamValid:(id)arg1;
- (_Bool)checkDevEnv;
- (void)alertDevTip:(id)arg1;
- (void)getVerifyPayState;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

