//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LLCssBlock;

@interface LLRenderBlock : NSObject
{
    LLCssBlock *cssBlock;
    LLRenderBlock *superBlock;
}

+ (id)loadStyleFile:(id)arg1;
+ (id)globalRenderBlock;
+ (id)orderedListWithSelectorString:(id)arg1;
@property(nonatomic) LLRenderBlock *superBlock; // @synthesize superBlock;
- (void).cxx_destruct;
- (id)colorOfProperties:(id)arg1;
- (void)addCssRule:(id)arg1;
- (id)init;
- (id)fontWithSelector:(id)arg1;
- (id)backgourndImageWithSelector:(id)arg1;
- (id)colorWithSelector:(id)arg1 forProperty:(id)arg2;
- (id)backgourndColorWithSelector:(id)arg1;
- (struct CGRect)frameRectWithSelector:(id)arg1;
- (id)valueWithProperty:(id)arg1 withSelector:(id)arg2;
- (id)valueWithProperty:(id)arg1 withSelectorList:(id)arg2;

@end

