//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LLBaseModel.h"

@class NSString;

@interface LLUser : LLBaseModel
{
    NSString *_user_login;
    NSString *_mob_bind;
    NSString *_name_user;
    NSString *_level_acct;
    NSString *_amt_balance;
    NSString *_oid_userno;
    NSString *_oid_acctno;
    NSString *_no_idcard;
    NSString *_auth_flag;
    NSString *_payCard;
    NSString *_payAgree;
}

@property(retain, nonatomic) NSString *payAgree; // @synthesize payAgree=_payAgree;
@property(retain, nonatomic) NSString *payCard; // @synthesize payCard=_payCard;
@property(retain, nonatomic) NSString *auth_flag; // @synthesize auth_flag=_auth_flag;
@property(retain, nonatomic) NSString *no_idcard; // @synthesize no_idcard=_no_idcard;
@property(retain, nonatomic) NSString *oid_acctno; // @synthesize oid_acctno=_oid_acctno;
@property(retain, nonatomic) NSString *oid_userno; // @synthesize oid_userno=_oid_userno;
@property(retain, nonatomic) NSString *amt_balance; // @synthesize amt_balance=_amt_balance;
@property(retain, nonatomic) NSString *level_acct; // @synthesize level_acct=_level_acct;
@property(retain, nonatomic) NSString *name_user; // @synthesize name_user=_name_user;
@property(retain, nonatomic) NSString *mob_bind; // @synthesize mob_bind=_mob_bind;
@property(retain, nonatomic) NSString *user_login; // @synthesize user_login=_user_login;
- (void).cxx_destruct;
- (_Bool)isRealAuthCheckPassed;
- (_Bool)isSimpleAuthCheckWaiting;
- (_Bool)isSimpleAuthCheckPassed;
- (id)secureName;
- (id)initWithAttributes:(id)arg1;

@end

