//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface NeedPayOrder : NSObject <NSCoding, NSCopying>
{
    int _status;
    int _ex_status;
    int _orderCount;
    double _cityId;
    double _orderId;
    NSString *_sijiName;
    double _sijiId;
    double _totalAmt;
    double _paiedAmt;
    NSString *_orderCode;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(nonatomic) int orderCount; // @synthesize orderCount=_orderCount;
@property(nonatomic) int ex_status; // @synthesize ex_status=_ex_status;
@property(nonatomic) int status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *orderCode; // @synthesize orderCode=_orderCode;
@property(nonatomic) double paiedAmt; // @synthesize paiedAmt=_paiedAmt;
@property(nonatomic) double totalAmt; // @synthesize totalAmt=_totalAmt;
@property(nonatomic) double sijiId; // @synthesize sijiId=_sijiId;
@property(retain, nonatomic) NSString *sijiName; // @synthesize sijiName=_sijiName;
@property(nonatomic) double orderId; // @synthesize orderId=_orderId;
@property(nonatomic) double cityId; // @synthesize cityId=_cityId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)objectOrNilForKey:(id)arg1 fromDictionary:(id)arg2;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

