//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperTableViewController.h"

@class AFHTTPRequestOperationManager, DriveDetailLabel, Driver, NSDictionary, NSMutableArray, NSString, NewDirverCommentCell, UIButton, UIImageView, UILabel;

@interface NewDriverDetailTableViewController : SuperTableViewController
{
    long long _driverID;
    Driver *_driver;
    NSString *_driverNickName;
    NewDirverCommentCell *_lastCommentCell;
    NSMutableArray *_commentArray;
    AFHTTPRequestOperationManager *_httpManager;
    NSDictionary *carTypeInstantIconInfo;
    _Bool isGettingCarTypeInstantIconInfo;
    NSString *carStandardFee;
    NSString *lowConsumption;
    long long _pageNo;
    NewDirverCommentCell *_cell;
    UIImageView *_headImageView;
    UILabel *_driverNameLabel;
    DriveDetailLabel *_isServedLabel;
    UILabel *_monthOrderNumLabel;
    UILabel *_favorableLabel;
    UIButton *_collectBtn;
    UIButton *_callButton;
}

@property(nonatomic) __weak UIButton *callButton; // @synthesize callButton=_callButton;
@property(nonatomic) __weak UIButton *collectBtn; // @synthesize collectBtn=_collectBtn;
@property(nonatomic) __weak UILabel *favorableLabel; // @synthesize favorableLabel=_favorableLabel;
@property(nonatomic) __weak UILabel *monthOrderNumLabel; // @synthesize monthOrderNumLabel=_monthOrderNumLabel;
@property(nonatomic) __weak DriveDetailLabel *isServedLabel; // @synthesize isServedLabel=_isServedLabel;
@property(nonatomic) __weak UILabel *driverNameLabel; // @synthesize driverNameLabel=_driverNameLabel;
@property(nonatomic) __weak UIImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)callDriverBittonClicked:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)loadAllCommentButtonAction:(id)arg1;
- (void)loadDriverCommentData;
- (void)backBarButtonAction:(id)arg1;
- (void)deCollectedBarButtonAction;
- (void)didCollectedBarButtonAction;
- (void)deCollectedDriver;
- (void)didCollectedDriver;
- (void)loadDriverDetailData;
- (void)updateServiceCarImageInfo:(id)arg1;
- (void)getCarTypeInstantIconInfo;
- (void)setViewData;
- (void)setDriverID:(long long)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)setTableViewFooterView;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)getCellHeight:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1;

@end

