//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, RatingBar, UILabel, UIView;

@interface NewDirverCommentCell : UITableViewCell
{
    UILabel *_commentLabel;
    UILabel *_dateLabel;
    NSLayoutConstraint *_commentLabelHeightConstraint;
    UIView *_starBarView;
    RatingBar *_rateingBar;
}

@property(retain, nonatomic) RatingBar *rateingBar; // @synthesize rateingBar=_rateingBar;
@property(nonatomic) __weak UIView *starBarView; // @synthesize starBarView=_starBarView;
@property(nonatomic) __weak NSLayoutConstraint *commentLabelHeightConstraint; // @synthesize commentLabelHeightConstraint=_commentLabelHeightConstraint;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) __weak UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
- (void).cxx_destruct;
- (id)convertUserNameaToAnonymity:(id)arg1;
- (id)convertLongDateStringToShortDateString:(id)arg1;
- (double)getCommentHeight:(id)arg1;
- (double)getCellHeight:(id)arg1;
- (void)setDataWithCommentModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setupRateBar;
- (void)awakeFromNib;

@end

