//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "NewOrderCarMessageContentViewDelegate.h"

@class NSString, NewOrderCarMessageContentViewController;

@interface NewMapViewController : SuperViewController <NewOrderCarMessageContentViewDelegate>
{
    NewOrderCarMessageContentViewController *_orderCarMessageVC;
}

@property(retain, nonatomic) NewOrderCarMessageContentViewController *orderCarMessageVC; // @synthesize orderCarMessageVC=_orderCarMessageVC;
- (void).cxx_destruct;
- (void)changeChildVCFrameWithHeight:(double)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

