//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Week)
- (id)weekdayDescription;
- (id)dateByAddingWeek:(long long)arg1;
- (id)dateBySettingWeekday:(long long)arg1;
- (id)dateBySettingWeekOfMonth:(long long)arg1;
- (id)dateBySettingWeekOfYear:(long long)arg1;
- (id)dateWeekAhead;
- (id)dateWeekAgo;
- (id)dateWeekEnd;
- (id)dateWeekStart;
@property(readonly, nonatomic) long long weekday;
@property(readonly, nonatomic) long long weekOfYear;
@property(readonly, nonatomic) long long weekOfMonth;
@end

