//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Year)
- (id)dateByAddingYear:(long long)arg1;
- (id)dateBySettingYear:(long long)arg1;
- (id)dateYearAhead;
- (id)dateYearAgo;
- (id)dateYearEnd;
- (id)dateYearStart;
@property(readonly, nonatomic) long long year;
@end

