//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (AKNumericFormatter)
- (unsigned long long)indexOfCharacter:(unsigned short)arg1;
- (unsigned long long)countDecimalDigits;
- (unsigned long long)countCharsSatisfyingBlock:(CDUnknownBlockType)arg1;
- (long long)minSuffixLengthContainingDecimalDigitsCount:(unsigned long long)arg1;
- (long long)minSuffixLengthContainingCharsCount:(unsigned long long)arg1 satisfyingBlock:(CDUnknownBlockType)arg2;
- (long long)minPrefixLengthContainingDecimalDigitsCount:(unsigned long long)arg1;
- (long long)minPrefixLengthContainingCharsCount:(unsigned long long)arg1 satisfyingBlock:(CDUnknownBlockType)arg2;
- (id)stringContainingOnlyDecimalDigits;
- (id)filteredStringUsingBlock:(CDUnknownBlockType)arg1;
@end

