//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface OrderComment : NSObject <NSCoding>
{
    _Bool _isSelected;
    int _code;
    NSString *_content;
}

@property int code; // @synthesize code=_code;
@property _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithContent:(id)arg1 code:(int)arg2 isSelected:(_Bool)arg3;

@end

