//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class AFHTTPRequestOperationManager, NSLayoutConstraint, NSTimer, OrderCancelActionSheetView, PublishInfo, SimpleCustomAlertView, UIButton, UIColor, UILabel;

@interface OrderCarBaoChePublishViewController : SuperViewController
{
    AFHTTPRequestOperationManager *httpManager;
    UIColor *tintColor;
    NSTimer *driverMatchTimer;
    int driverMatchSeconds;
    OrderCancelActionSheetView *sheet;
    SimpleCustomAlertView *alertView;
    PublishInfo *_pubInfo;
    UILabel *_titleLabel;
    UILabel *_describeLabel;
    UIButton *_goHomePageBtn;
    NSLayoutConstraint *_goHomePageBtnHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *goHomePageBtnHeightConstraint; // @synthesize goHomePageBtnHeightConstraint=_goHomePageBtnHeightConstraint;
@property(nonatomic) __weak UIButton *goHomePageBtn; // @synthesize goHomePageBtn=_goHomePageBtn;
@property(nonatomic) __weak UILabel *describeLabel; // @synthesize describeLabel=_describeLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) PublishInfo *pubInfo; // @synthesize pubInfo=_pubInfo;
- (void).cxx_destruct;
- (void)goOrderDetail;
- (void)cancelOrderWithoutDriver:(unsigned long long)arg1;
- (void)showCancleError:(unsigned long long)arg1;
- (void)cancelOrder:(CDUnknownBlockType)arg1;
- (void)cancelOrderAction;
- (void)getDriverMatch;
- (void)removeRequest;
- (void)goHomePage:(id)arg1;
- (void)driverMatchAction;
- (void)removeTimer:(id)arg1;
- (void)removeDriverMatchTimer;
- (void)addDriverMatchTimer;
- (void)dismissAlertView;
- (void)setInteractivePopGestureRecognizeEnable:(_Bool)arg1;
- (void)backToRootViewActionAnimated:(_Bool)arg1;
- (void)setNavigationBarRightItem;
- (void)didReceiveMemoryWarning;
- (void)addImageViewAnimation;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)dealloc;

@end

