//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderDetailBaseViewController.h"

#import "LLPaySdkDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import "OrderSelectPayTypeDelegate.h"
#import "UPPayPluginDelegate.h"
#import "WXApiDelegate.h"

@class CustomIOSAlertView, NSDictionary, NSString, UIButton, UIImageView, UILabel, UITableView, UIView;

@interface OrderWaitForPayViewController : OrderDetailBaseViewController <OrderSelectPayTypeDelegate, MFMessageComposeViewControllerDelegate, LLPaySdkDelegate, WXApiDelegate, UPPayPluginDelegate>
{
    int payWay;
    int userChooseTipReward;
    NSString *paymainId;
    NSString *payCode;
    _Bool isVisible;
    CustomIOSAlertView *shareAlertView;
    CustomIOSAlertView *_downgradeOrderAlertView;
    CustomIOSAlertView *_orderPayFailAlertView;
    NSDictionary *orderShareInfo;
    _Bool _isAlipayAutoPay;
    UITableView *_tableView;
    UIView *_bottomView;
    UILabel *_againPayMsgLbl;
    UIView *_lastPayTypeView;
    UIButton *_lastPayTypeSelectOtherButton;
    UIImageView *_lastPayTypeImgView;
    UIView *_autoPayMsgView;
    UIButton *_goDoingBtn;
    UIButton *_xiaoFeiCanPayButton;
    UILabel *_xiaoFeiCanNotBGLabel;
}

@property(nonatomic) _Bool isAlipayAutoPay; // @synthesize isAlipayAutoPay=_isAlipayAutoPay;
@property(retain, nonatomic) UILabel *xiaoFeiCanNotBGLabel; // @synthesize xiaoFeiCanNotBGLabel=_xiaoFeiCanNotBGLabel;
@property(retain, nonatomic) UIButton *xiaoFeiCanPayButton; // @synthesize xiaoFeiCanPayButton=_xiaoFeiCanPayButton;
@property(nonatomic) __weak UIButton *goDoingBtn; // @synthesize goDoingBtn=_goDoingBtn;
@property(nonatomic) __weak UIView *autoPayMsgView; // @synthesize autoPayMsgView=_autoPayMsgView;
@property(nonatomic) __weak UIImageView *lastPayTypeImgView; // @synthesize lastPayTypeImgView=_lastPayTypeImgView;
@property(nonatomic) __weak UIButton *lastPayTypeSelectOtherButton; // @synthesize lastPayTypeSelectOtherButton=_lastPayTypeSelectOtherButton;
@property(nonatomic) __weak UIView *lastPayTypeView; // @synthesize lastPayTypeView=_lastPayTypeView;
@property(nonatomic) __weak UILabel *againPayMsgLbl; // @synthesize againPayMsgLbl=_againPayMsgLbl;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)weixinSendShareInfo:(id)arg1 Scene:(int)arg2;
- (void)closeShareAlertView;
- (void)hideshareAlertView;
- (void)orderRouteShareSMS;
- (void)orderRouteShareSendWechatMessageAtScene:(id)arg1;
- (void)orderRouteShareInfoAction;
- (void)sendOrderShareAction;
- (void)sendWechatMessageAtScene:(id)arg1;
- (void)creatingShareAlertVieWithRouteShare:(_Bool)arg1 isXiaoFei:(int)arg2;
- (void)showshareAlertViewWithOrderShareInfo:(id)arg1 isxiaofei:(int)arg2;
- (void)orderShareInfoAction:(int)arg1;
- (void)showOrderPayFailAlertViewWithText:(id)arg1;
- (void)queryPayResult:(id)arg1;
- (_Bool)cancelOrderNeedPay;
- (void)paymentEnd:(int)arg1 withResultDic:(id)arg2;
- (void)LLPayWithPayInfo:(id)arg1;
- (void)weixinPayWithPrePayResult:(id)arg1;
- (void)alipaySDKWithPayInfo:(id)arg1;
- (void)sendClientPayNotifyWithBehaviorstatus:(id)arg1 payChannelCode:(long long)arg2;
- (void)resetXiaoFei;
- (void)xiaoFeiPayCancel;
- (void)xiaoFeiPayFail;
- (void)xiaoFeiPaySuccess;
- (void)setXiaoFeiPayStatusTitle:(id)arg1 Status:(int)arg2;
- (void)setPayStatusTitle:(id)arg1 Status:(int)arg2;
- (void)xiaoFeiQueryPayResult:(id)arg1;
- (void)UPPayPluginResult:(id)arg1;
- (void)unionPayWithTn:(id)arg1;
- (void)xiaoFeiPayAction;
- (void)payOrderAction;
- (void)orderDidSelectedWithPayType:(int)arg1 isXiaoFei:(_Bool)arg2;
- (void)selectPayTypeActionWithNeedPay:(double)arg1 isXiaoFei:(_Bool)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)setOrderView:(int)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

