//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class AFHTTPRequestOperationManager, NSString, UIButton, UILabel, UIView;

@interface OrderShareViewController : SuperViewController <UIGestureRecognizerDelegate>
{
    AFHTTPRequestOperationManager *_httpManager;
    UIView *_bgView;
    UIView *_bg2View;
    UIView *_mainView;
    UIButton *_weixinButton;
    UIButton *_friendButton;
    UILabel *_shareTitleLabel;
    UILabel *_shareTextLabel;
    long long _orderID;
    id <OrderShareViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <OrderShareViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long orderID; // @synthesize orderID=_orderID;
@property(nonatomic) __weak UILabel *shareTextLabel; // @synthesize shareTextLabel=_shareTextLabel;
@property(nonatomic) __weak UILabel *shareTitleLabel; // @synthesize shareTitleLabel=_shareTitleLabel;
@property(nonatomic) __weak UIButton *friendButton; // @synthesize friendButton=_friendButton;
@property(nonatomic) __weak UIButton *weixinButton; // @synthesize weixinButton=_weixinButton;
@property(nonatomic) __weak UIView *mainView; // @synthesize mainView=_mainView;
@property(nonatomic) __weak UIView *bg2View; // @synthesize bg2View=_bg2View;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)showAnimations;
- (void)hideAnimations;
- (void)hide:(id)arg1;
- (void)show;
- (void)sendOrderShareAction;
- (void)weixinSendShareInfo:(id)arg1 Scene:(int)arg2;
- (void)sendWechatMessageAtScene:(int)arg1;
- (void)WechateTimeLineButtonAction:(id)arg1;
- (void)WechatSessionButtonAction:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)setupViewData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

