//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface OrderObjectionOption : NSObject <NSCoding>
{
    int _code;
    int _isSelected;
    NSString *_content;
}

@property(nonatomic) int isSelected; // @synthesize isSelected=_isSelected;
@property(nonatomic) int code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithContent:(id)arg1 code:(int)arg2 isSelected:(int)arg3;

@end

