//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CustomIOSAlertView.h"

#import "OrderObjectionOptionDelegate.h"

@class AFHTTPRequestOperationManager, NSMutableArray, NSString, OrderObjectionContent;

@interface OrderObjectionView : CustomIOSAlertView <OrderObjectionOptionDelegate>
{
    id <OrderObjectionSubmitSuccessDelegate> _submitDelegate;
    OrderObjectionContent *_orderObjectionContent;
    NSMutableArray *_objectionOptionBySelectedArray;
    long long _orderId;
    NSString *_title;
    AFHTTPRequestOperationManager *_httpManager;
}

@property(retain, nonatomic) AFHTTPRequestOperationManager *httpManager; // @synthesize httpManager=_httpManager;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long orderId; // @synthesize orderId=_orderId;
@property(retain, nonatomic) NSMutableArray *objectionOptionBySelectedArray; // @synthesize objectionOptionBySelectedArray=_objectionOptionBySelectedArray;
@property(retain, nonatomic) OrderObjectionContent *orderObjectionContent; // @synthesize orderObjectionContent=_orderObjectionContent;
@property(nonatomic) __weak id <OrderObjectionSubmitSuccessDelegate> submitDelegate; // @synthesize submitDelegate=_submitDelegate;
- (void).cxx_destruct;
- (void)didTapObjectionOption:(id)arg1 isSelected:(_Bool)arg2;
- (void)submitOrderObjection;
- (id)getSelectCode;
- (id)getSelectString;
- (void)cancel;
- (struct CGRect)countingObjectionOptionNeedFrameWithOrderObjectionOption:(id)arg1 beforeOptionView:(id)arg2 beforeIsLong:(_Bool)arg3 ownIsLong:(_Bool)arg4 addHeight:(double)arg5 inView:(id)arg6 index:(int)arg7;
- (_Bool)isLongWithOrderObjectionOption:(id)arg1 inView:(id)arg2;
- (_Bool)needAddHeightWithBeforeOptionView:(id)arg1 beforeIsLong:(_Bool)arg2 ownIsLong:(_Bool)arg3;
- (void)setupSubViews;
- (void)setupData;
- (id)initWithOrderId:(long long)arg1 title:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

