//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "NewAddressBookDelegate.h"
#import "UITextFieldDelegate.h"

@class AddressBook, NSArray, NSLayoutConstraint, NSString, UITableView, UITextField, UIView;

@interface OrderCarSelectUserTableViewController : SuperViewController <UITextFieldDelegate, NewAddressBookDelegate>
{
    long long currentIndex;
    NSArray *topConstraints;
    double mainViewHeight;
    _Bool isShowAddressBook;
    NSArray *contactArray;
    double _lastDistance;
    UITextField *_currentWritingFeild;
    _Bool _isSelectSelf;
    id <OrderCarSelectUserDelegate> _delegate;
    AddressBook *_fromAddressBook;
    UIView *_mainView;
    UIView *_bgView;
    UIView *_toolView;
    UITableView *_tableView;
    UITextField *_usernameField;
    UITextField *_userPhoneField;
    NSLayoutConstraint *_topConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
@property(nonatomic) __weak UITextField *userPhoneField; // @synthesize userPhoneField=_userPhoneField;
@property(nonatomic) __weak UITextField *usernameField; // @synthesize usernameField=_usernameField;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIView *toolView; // @synthesize toolView=_toolView;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) AddressBook *fromAddressBook; // @synthesize fromAddressBook=_fromAddressBook;
@property(nonatomic) _Bool isSelectSelf; // @synthesize isSelectSelf=_isSelectSelf;
@property(nonatomic) id <OrderCarSelectUserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)toolView:(id)arg1 didPressAtIndex:(long long)arg2;
- (void)setSelectOption;
- (void)setViewTop:(double)arg1 animate:(_Bool)arg2;
- (void)hide;
- (void)show;
- (void)newAddressBookDidSelectBack;
- (void)newAddressBookDidSelect:(id)arg1;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (_Bool)isThirdPartyInputMethod;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)TextFieldTextDidChange:(id)arg1;
- (void)textFieldTextDidEndEditing:(id)arg1;
- (void)textFieldTextDidBeginEditing:(id)arg1;
- (void)doKeyboardHide:(double)arg1;
- (void)doKeyboardShow:(double)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)hideKeyboard;
- (void)done:(id)arg1;
- (void)goContacts:(id)arg1;
- (void)goBack:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)removeKeyboardNotification;
- (void)addKeyboardNotification;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

