//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "BMKLocationServiceDelegate.h"
#import "BMKMapViewDelegate.h"
#import "BMKRouteSearchDelegate.h"
#import "CustomBMKGeoCodeSearchDelegate.h"
#import "OrderCarMessageContentViewDelegate.h"
#import "OrderCarSelectPassengerDelegate.h"
#import "SelectAddressDelegate.h"

@class AFHTTPRequestOperation, BMKMapView, BMKPoiInfo, BMKPolyline, BMKReverseGeoCodeResult, BMKRouteSearch, BMKUserLocation, CustomAlertMenuView, CustomBMKGeoCodeSearch, CustomBMKLocationService, FareSelectMenuViewController, MapCarActionView, NSArray, NSDictionary, NSString, OrderCarMessageContentView, RemarkPopOverViewController, RouteAnnotation, TutorialView, UIButton, UIImageView, UIView;

@interface OrderCarIndexViewController : SuperViewController <BMKRouteSearchDelegate, BMKMapViewDelegate, BMKLocationServiceDelegate, CustomBMKGeoCodeSearchDelegate, OrderCarMessageContentViewDelegate, SelectAddressDelegate, OrderCarSelectPassengerDelegate>
{
    _Bool shouldAutoLocateCurrentPosition;
    RouteAnnotation *_userLocarionAnnotation;
    RouteAnnotation *_startPointAnnotation;
    RouteAnnotation *_endPointAnnotation;
    CustomBMKLocationService *_locationService;
    CustomBMKGeoCodeSearch *_geoCodeSearch;
    CustomBMKGeoCodeSearch *_locationGeoCodeSearch;
    BMKRouteSearch *_drivingRouteSearch;
    BMKPolyline *_drivingPolyLine;
    BMKUserLocation *_userLocation;
    BMKPoiInfo *_startPoint;
    BMKPoiInfo *_lastStartPoint;
    BMKPoiInfo *_endPoint;
    BMKReverseGeoCodeResult *_geoCodeResult;
    BMKReverseGeoCodeResult *_lastGeoCodeResult;
    AFHTTPRequestOperation *_sysParamsRequestOperation;
    _Bool isSelectStartPoint;
    CustomAlertMenuView *_swtichAccountAlertMenuView;
    double _lastMapZoomLevel;
    FareSelectMenuViewController *_fareSelectMenuViewController;
    TutorialView *tutorialView;
    RemarkPopOverViewController *_remarkPopOverViewController;
    _Bool _isSelectedSelf;
    _Bool _isEstimatedSuccessed;
    _Bool _isShowingDrivingPolyLineRegion;
    _Bool _isShowReverseGeoCodeFailed;
    _Bool _isSelectedNewStartAddress;
    unsigned long long _serviceType;
    NSArray *_carTypesArray;
    BMKMapView *_mapView;
    MapCarActionView *_mapCarActionView;
    OrderCarMessageContentView *_orderCarMessageContentView;
    UIImageView *_locationImageView;
    UIImageView *_locationShadowImageView;
    UIView *_qipaoContentView;
    UIImageView *_qipaoLeftImageView;
    UIImageView *_qipaoRightImageView;
    UIButton *_qipaoButton;
    NSDictionary *_lastEstimateParams;
    NSString *_passengerName;
    NSString *_passengerPhoneNumber;
    NSArray *_enterpriseLimitCarTypes;
    long long _estimateFlowId;
    NSString *_individuationCarTypeString;
}

@property(copy, nonatomic) NSString *individuationCarTypeString; // @synthesize individuationCarTypeString=_individuationCarTypeString;
@property(nonatomic) long long estimateFlowId; // @synthesize estimateFlowId=_estimateFlowId;
@property(retain, nonatomic) NSArray *enterpriseLimitCarTypes; // @synthesize enterpriseLimitCarTypes=_enterpriseLimitCarTypes;
@property(copy, nonatomic) NSString *passengerPhoneNumber; // @synthesize passengerPhoneNumber=_passengerPhoneNumber;
@property(copy, nonatomic) NSString *passengerName; // @synthesize passengerName=_passengerName;
@property(retain, nonatomic) NSDictionary *lastEstimateParams; // @synthesize lastEstimateParams=_lastEstimateParams;
@property(nonatomic) _Bool isSelectedNewStartAddress; // @synthesize isSelectedNewStartAddress=_isSelectedNewStartAddress;
@property(nonatomic) _Bool isShowReverseGeoCodeFailed; // @synthesize isShowReverseGeoCodeFailed=_isShowReverseGeoCodeFailed;
@property(nonatomic) _Bool isShowingDrivingPolyLineRegion; // @synthesize isShowingDrivingPolyLineRegion=_isShowingDrivingPolyLineRegion;
@property(nonatomic) _Bool isEstimatedSuccessed; // @synthesize isEstimatedSuccessed=_isEstimatedSuccessed;
@property(nonatomic) _Bool isSelectedSelf; // @synthesize isSelectedSelf=_isSelectedSelf;
@property(nonatomic) __weak UIButton *qipaoButton; // @synthesize qipaoButton=_qipaoButton;
@property(nonatomic) __weak UIImageView *qipaoRightImageView; // @synthesize qipaoRightImageView=_qipaoRightImageView;
@property(nonatomic) __weak UIImageView *qipaoLeftImageView; // @synthesize qipaoLeftImageView=_qipaoLeftImageView;
@property(nonatomic) __weak UIView *qipaoContentView; // @synthesize qipaoContentView=_qipaoContentView;
@property(nonatomic) __weak UIImageView *locationShadowImageView; // @synthesize locationShadowImageView=_locationShadowImageView;
@property(nonatomic) __weak UIImageView *locationImageView; // @synthesize locationImageView=_locationImageView;
@property(nonatomic) __weak OrderCarMessageContentView *orderCarMessageContentView; // @synthesize orderCarMessageContentView=_orderCarMessageContentView;
@property(nonatomic) __weak MapCarActionView *mapCarActionView; // @synthesize mapCarActionView=_mapCarActionView;
@property(nonatomic) __weak BMKMapView *mapView; // @synthesize mapView=_mapView;
@property(retain, nonatomic) NSArray *carTypesArray; // @synthesize carTypesArray=_carTypesArray;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
- (void).cxx_destruct;
- (void)showTutorialView;
- (CDStruct_26e8d939)getRegionWithStartPoint:(id)arg1 endPoint:(id)arg2;
- (double)getDistanceBetweenFirstCoordinate:(struct CLLocationCoordinate2D)arg1 andSecondCoordinate:(struct CLLocationCoordinate2D)arg2;
- (_Bool)isSameCLLocationCoordinate2D:(struct CLLocationCoordinate2D)arg1 coordinate2:(struct CLLocationCoordinate2D)arg2;
- (void)orderCarSelectPassenger:(id)arg1 phoneNumber:(id)arg2 isSelf:(_Bool)arg3;
- (void)messageContentView:(id)arg1 statusDidChanged:(long long)arg2 fromStatus:(long long)arg3;
- (void)messageContentView:(id)arg1 didClickActionType:(long long)arg2;
- (void)selectShuttleType:(unsigned long long)arg1 segmentedType:(unsigned long long)arg2 isStartPoint:(_Bool)arg3 air:(id)arg4 city:(id)arg5 time:(id)arg6 fromService:(unsigned long long)arg7;
- (void)selectAddressValue:(id)arg1 pointName:(id)arg2 lat:(double)arg3 lon:(double)arg4 isChangeCity:(_Bool)arg5;
- (void)selectGeoCodeAddressValue:(id)arg1:(_Bool)arg2;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (id)getRouteAnnotationView:(id)arg1 viewForAnnotation:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(_Bool)arg2;
- (void)mapViewDidFinishLoading:(id)arg1;
- (void)onGetDrivingRouteResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)onGetReverseGeoCodeResult:(id)arg1 result:(id)arg2 errorCode:(int)arg3;
- (void)didFailToLocateUserWithError:(id)arg1;
- (void)didUpdateBMKUserLocation:(id)arg1;
- (void)willStartLocatingUser;
- (void)qipaoClickAction:(id)arg1;
- (void)backAction:(id)arg1;
- (void)clearMap;
- (void)updateStartPointGeoResult:(id)arg1 updateCenter:(_Bool)arg2;
- (void)changeToNewCity:(id)arg1 sysParam:(id)arg2 result:(id)arg3 fromLocation:(_Bool)arg4;
- (void)loadAppSysParamWithCity:(id)arg1 result:(id)arg2 fromLocation:(_Bool)arg3;
- (void)goFeeDetail:(id)arg1 defaultIndex:(long long)arg2;
- (void)clearEstimateResult;
- (void)setDefaultCarTypes;
- (void)limitCarType;
- (void)goOrderList;
- (void)goBindBankCard;
- (void)goBalance:(id)arg1;
- (void)showBalanceIsNotEnough:(id)arg1 needPrice:(id)arg2;
- (void)getIndividuationCarType;
- (void)switchAccountType;
- (void)showSwitchAccountType:(id)arg1;
- (void)goOrderDetailWtihPublishInfo:(id)arg1;
- (void)sendUseCarBroadcast:(id)arg1;
- (void)goNext;
- (void)estimateFinish;
- (_Bool)needEstimate:(id)arg1;
- (void)getFeePriceOnline:(_Bool)arg1;
- (void)loadCarTypes:(unsigned long long)arg1 date:(id)arg2 atLeastGetOneDay:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)showSelectAddressViewController:(_Bool)arg1;
- (void)stopDrivingRouteSearch;
- (void)startDrivingRouteSearchWithFromPoi:(id)arg1 toPoi:(id)arg2;
- (void)stopGeoCode;
- (void)showQipaoWithMessage:(id)arg1 failed:(_Bool)arg2 enabled:(_Bool)arg3;
- (void)showLocationAniamte;
- (void)startGeoCode:(struct CLLocationCoordinate2D)arg1 fromLocation:(_Bool)arg2 fromLocationButton:(_Bool)arg3;
- (void)stopLocation;
- (void)startLocation:(_Bool)arg1;
- (void)updateTitle;
- (void)showDrivingPolyLineRegion;
- (void)updateAnnotations;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)updateThemeImages;
- (void)initViews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

