//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderCarBaseViewController.h"

@interface OrderCarOnCallViewController : OrderCarBaseViewController
{
}

- (void)showSelectTimeViewWhenYuYueNotEnough30Minutes;
- (void)goNext:(id)arg1;
- (void)selectShuttleType:(unsigned long long)arg1 segmentedType:(unsigned long long)arg2 isStartPoint:(_Bool)arg3 air:(id)arg4 city:(id)arg5 time:(id)arg6 fromService:(unsigned long long)arg7;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)getFeePriceOnline;
- (void)getFeePrice;
- (void)setOnCallServiceType:(unsigned long long)arg1 selectedDate:(id)arg2 currentCity:(id)arg3;
- (void)setPublishInfo:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)dealloc;

@end

