//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSLayoutConstraint, NSString, UIButton, UICollectionView, UIImageView, UILabel;

@interface OrderCarMessageContentView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    NSString *_showingFareTitle;
    _Bool _hiddenPassengerView;
    _Bool _hasFareInfo;
    _Bool _isEstimatedSuccessed;
    long long _messageStatus;
    unsigned long long _serviceType;
    long long _selectedCarTypeIndex;
    NSString *_startAddress;
    NSString *_endAddress;
    NSString *_fareTitle;
    UIButton *_expansionButton;
    UIButton *_remarkButton;
    id <OrderCarMessageContentViewDelegate> _delegate;
    UIView *_contentView;
    UIView *_topView;
    UIView *_middleView;
    UIView *_bottomView;
    UIView *_footerView;
    UILabel *_passengerLabel;
    UIView *_startAddressContentView;
    UILabel *_startAddressLabel;
    UILabel *_startAddressDetailLabel;
    UIView *_endAddressContentView;
    UILabel *_endAddressLabel;
    UILabel *_endAddressDetailLabel;
    UICollectionView *_carTypeCollectionView;
    UIView *_estimateContentView;
    UILabel *_estimatePriceLabel;
    UILabel *_estimateFloatPriceLabel;
    UIButton *_estimateButton;
    UIButton *_submitButton;
    UIButton *_addMoneyButton;
    UIView *_middleViewMiddleLine;
    UIImageView *_middleViewLinkImageView;
    UIView *_addMoneyContentView;
    UIButton *_locationButton;
    UILabel *_noCarMessageLabel;
    UIView *_bottomViewLine2;
    NSLayoutConstraint *_lineHeightConstraint;
    NSLayoutConstraint *_topViewHeightConstraint;
    NSLayoutConstraint *_middleViewTopConstraint;
    NSLayoutConstraint *_middleViewTrailingConstraint;
    NSLayoutConstraint *_middleViewLeadingConstraint;
    NSLayoutConstraint *_middleViewStartArrowTrailingConstraint;
    NSLayoutConstraint *_footerViewBottomConstraint;
    NSLayoutConstraint *_expansionButtonCenterYConstraint;
    NSLayoutConstraint *_footerViewSpaceToBottomViewConstraint;
    NSLayoutConstraint *_addMoneyContentViewHeightConstraint;
    NSLayoutConstraint *_bottomViewTopSpaceToMiddleViewBottomConstraint;
    NSLayoutConstraint *_bottomViewBottomSpaceToMiddleViewBottomConstraint;
    NSLayoutConstraint *_footerViewHeightConstraint;
    NSLayoutConstraint *_estimateContentViewHeightConstraint;
    NSLayoutConstraint *_expansionButtonTrailingToMiddleViewConstraint;
    NSLayoutConstraint *_middleViewMiddleLineTrailing;
    NSLayoutConstraint *_remarkBtnHeightConstraint;
    NSArray *_carTypesArray;
}

@property(retain, nonatomic) NSArray *carTypesArray; // @synthesize carTypesArray=_carTypesArray;
@property(nonatomic) __weak NSLayoutConstraint *remarkBtnHeightConstraint; // @synthesize remarkBtnHeightConstraint=_remarkBtnHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleViewMiddleLineTrailing; // @synthesize middleViewMiddleLineTrailing=_middleViewMiddleLineTrailing;
@property(nonatomic) __weak NSLayoutConstraint *expansionButtonTrailingToMiddleViewConstraint; // @synthesize expansionButtonTrailingToMiddleViewConstraint=_expansionButtonTrailingToMiddleViewConstraint;
@property(nonatomic) __weak NSLayoutConstraint *estimateContentViewHeightConstraint; // @synthesize estimateContentViewHeightConstraint=_estimateContentViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *footerViewHeightConstraint; // @synthesize footerViewHeightConstraint=_footerViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomViewBottomSpaceToMiddleViewBottomConstraint; // @synthesize bottomViewBottomSpaceToMiddleViewBottomConstraint=_bottomViewBottomSpaceToMiddleViewBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomViewTopSpaceToMiddleViewBottomConstraint; // @synthesize bottomViewTopSpaceToMiddleViewBottomConstraint=_bottomViewTopSpaceToMiddleViewBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *addMoneyContentViewHeightConstraint; // @synthesize addMoneyContentViewHeightConstraint=_addMoneyContentViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *footerViewSpaceToBottomViewConstraint; // @synthesize footerViewSpaceToBottomViewConstraint=_footerViewSpaceToBottomViewConstraint;
@property(nonatomic) __weak NSLayoutConstraint *expansionButtonCenterYConstraint; // @synthesize expansionButtonCenterYConstraint=_expansionButtonCenterYConstraint;
@property(nonatomic) __weak NSLayoutConstraint *footerViewBottomConstraint; // @synthesize footerViewBottomConstraint=_footerViewBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleViewStartArrowTrailingConstraint; // @synthesize middleViewStartArrowTrailingConstraint=_middleViewStartArrowTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleViewLeadingConstraint; // @synthesize middleViewLeadingConstraint=_middleViewLeadingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleViewTrailingConstraint; // @synthesize middleViewTrailingConstraint=_middleViewTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleViewTopConstraint; // @synthesize middleViewTopConstraint=_middleViewTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *topViewHeightConstraint; // @synthesize topViewHeightConstraint=_topViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *lineHeightConstraint; // @synthesize lineHeightConstraint=_lineHeightConstraint;
@property(nonatomic) __weak UIView *bottomViewLine2; // @synthesize bottomViewLine2=_bottomViewLine2;
@property(nonatomic) __weak UILabel *noCarMessageLabel; // @synthesize noCarMessageLabel=_noCarMessageLabel;
@property(nonatomic) __weak UIButton *locationButton; // @synthesize locationButton=_locationButton;
@property(nonatomic) __weak UIView *addMoneyContentView; // @synthesize addMoneyContentView=_addMoneyContentView;
@property(nonatomic) __weak UIImageView *middleViewLinkImageView; // @synthesize middleViewLinkImageView=_middleViewLinkImageView;
@property(nonatomic) __weak UIView *middleViewMiddleLine; // @synthesize middleViewMiddleLine=_middleViewMiddleLine;
@property(nonatomic) __weak UIButton *addMoneyButton; // @synthesize addMoneyButton=_addMoneyButton;
@property(nonatomic) __weak UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(nonatomic) __weak UIButton *estimateButton; // @synthesize estimateButton=_estimateButton;
@property(nonatomic) __weak UILabel *estimateFloatPriceLabel; // @synthesize estimateFloatPriceLabel=_estimateFloatPriceLabel;
@property(nonatomic) __weak UILabel *estimatePriceLabel; // @synthesize estimatePriceLabel=_estimatePriceLabel;
@property(nonatomic) __weak UIView *estimateContentView; // @synthesize estimateContentView=_estimateContentView;
@property(nonatomic) __weak UICollectionView *carTypeCollectionView; // @synthesize carTypeCollectionView=_carTypeCollectionView;
@property(nonatomic) __weak UILabel *endAddressDetailLabel; // @synthesize endAddressDetailLabel=_endAddressDetailLabel;
@property(nonatomic) __weak UILabel *endAddressLabel; // @synthesize endAddressLabel=_endAddressLabel;
@property(nonatomic) __weak UIView *endAddressContentView; // @synthesize endAddressContentView=_endAddressContentView;
@property(nonatomic) __weak UILabel *startAddressDetailLabel; // @synthesize startAddressDetailLabel=_startAddressDetailLabel;
@property(nonatomic) __weak UILabel *startAddressLabel; // @synthesize startAddressLabel=_startAddressLabel;
@property(nonatomic) __weak UIView *startAddressContentView; // @synthesize startAddressContentView=_startAddressContentView;
@property(nonatomic) __weak UILabel *passengerLabel; // @synthesize passengerLabel=_passengerLabel;
@property(nonatomic) __weak UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIView *middleView; // @synthesize middleView=_middleView;
@property(nonatomic) __weak UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <OrderCarMessageContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIButton *remarkButton; // @synthesize remarkButton=_remarkButton;
@property(nonatomic) __weak UIButton *expansionButton; // @synthesize expansionButton=_expansionButton;
@property(copy, nonatomic) NSString *fareTitle; // @synthesize fareTitle=_fareTitle;
@property(copy, nonatomic) NSString *endAddress; // @synthesize endAddress=_endAddress;
@property(copy, nonatomic) NSString *startAddress; // @synthesize startAddress=_startAddress;
@property(nonatomic) _Bool isEstimatedSuccessed; // @synthesize isEstimatedSuccessed=_isEstimatedSuccessed;
@property(nonatomic) _Bool hasFareInfo; // @synthesize hasFareInfo=_hasFareInfo;
@property(nonatomic) _Bool hiddenPassengerView; // @synthesize hiddenPassengerView=_hiddenPassengerView;
@property(nonatomic) long long selectedCarTypeIndex; // @synthesize selectedCarTypeIndex=_selectedCarTypeIndex;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
@property(nonatomic) long long messageStatus; // @synthesize messageStatus=_messageStatus;
- (void).cxx_destruct;
- (void)updateThemeImages;
- (double)getHeightScale;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)updatePriorityWithStatus:(long long)arg1;
- (void)updateContentViewWithStatus:(long long)arg1 serviceType:(unsigned long long)arg2 animate:(_Bool)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)expansionAction:(id)arg1;
- (void)submitOrderAction:(id)arg1;
- (void)selectAddMoneyAction:(id)arg1;
- (void)clickedRemarkAction:(id)arg1;
- (void)clickEstimateDetailsAction:(id)arg1;
- (void)selectedCarTypeAction:(id)arg1;
- (void)selectEndAddressAction:(id)arg1;
- (void)selectStartAddressAction:(id)arg1;
- (void)selectPassengersAction:(id)arg1;
- (void)locationAction:(id)arg1;
- (void)setEstimateWithCarTypeModel:(id)arg1;
- (void)estimateFinish:(_Bool)arg1;
- (void)setLocationButtonHidden:(_Bool)arg1;
- (void)setCarTypeFareTitle:(id)arg1;
- (void)setCarTypeFarePrice:(double)arg1;
- (void)setCarTypes:(id)arg1;
- (void)tryShowMessageStatus;
- (void)setWillStartGeoCode;
- (void)setCarTypeArraySelectedAtFirstIndexPath;
- (void)setEndAddress:(id)arg1 detailEndAddress:(id)arg2 defaultMsg:(id)arg3;
- (void)setStartAddress:(id)arg1 detailStartAddress:(id)arg2 defaultMsg:(id)arg3;
- (void)setEndAddress:(id)arg1 detailEndAddress:(id)arg2;
- (void)setStartAddress:(id)arg1 detailStartAddress:(id)arg2;
- (void)setPassengerViewHidden:(_Bool)arg1 animate:(_Bool)arg2;
- (void)setPassengersNumber:(id)arg1 name:(id)arg2;
- (void)switchAccountTypeSuccess:(id)arg1;
- (void)dealloc;
- (void)initViews;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

