//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OrderDetailBaseViewController.h"

#import "OrderCommentSuccessDelegate.h"
#import "OrderShareViewControllerDelegate.h"

@class NSString, OrderCommentView, UIButton, UITableView;

@interface OrderWaitForAppraiseViewController : OrderDetailBaseViewController <OrderCommentSuccessDelegate, OrderShareViewControllerDelegate>
{
    OrderCommentView *_orderCommentView;
    UITableView *_tableView;
    UIButton *_shareButton;
    UIButton *_commentButton;
}

@property(retain, nonatomic) UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)goAppstore;
- (void)goFeekBack;
- (void)showAppStoreCoreView:(id)arg1 title1:(id)arg2 title2:(id)arg3 title3:(id)arg4;
- (void)orderCommentSuccessWithIsPopupGuide:(_Bool)arg1 title:(id)arg2 content1:(id)arg3 content2:(id)arg4 content3:(id)arg5;
- (void)clickedShareButton;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)isEnterpriseOrder;
- (void)setShareButtonBgImage;
- (void)didReceiveMemoryWarning;
- (void)commentButtonAction;
- (void)setCommentButtonWithStatus:(int)arg1;
- (void)shareOrderAction;
- (void)setShareButtonWithStatus:(int)arg1;
- (void)setOrderView:(int)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

