//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CarTypeModel, NSLayoutConstraint, NSMutableArray, NSString, UIButton, UILabel, UITableView, UIToolbar;

@interface OrderCarFeeDetailViewController : SuperViewController <UITableViewDataSource, UITableViewDelegate>
{
    CarTypeModel *_carTypeModel;
    unsigned long long _serviceType;
    long long _estimateFlowId;
    NSMutableArray *_dataSource;
    UIButton *_backButton;
    UITableView *_tableView;
    UILabel *_priceLabel;
    UILabel *_estimateDesLabel;
    UIToolbar *_vagueToolbar;
    NSLayoutConstraint *_lineHeightConstraint;
    NSLayoutConstraint *_tableHeightConstraint;
}

+ (void)presentInViewController:(id)arg1 withCarTypeModel:(id)arg2 andServiceType:(unsigned long long)arg3 estimateFlowId:(long long)arg4;
@property(nonatomic) __weak NSLayoutConstraint *tableHeightConstraint; // @synthesize tableHeightConstraint=_tableHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *lineHeightConstraint; // @synthesize lineHeightConstraint=_lineHeightConstraint;
@property(nonatomic) __weak UIToolbar *vagueToolbar; // @synthesize vagueToolbar=_vagueToolbar;
@property(nonatomic) __weak UILabel *estimateDesLabel; // @synthesize estimateDesLabel=_estimateDesLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) NSMutableArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long estimateFlowId; // @synthesize estimateFlowId=_estimateFlowId;
@property(nonatomic) unsigned long long serviceType; // @synthesize serviceType=_serviceType;
@property(retain, nonatomic) CarTypeModel *carTypeModel; // @synthesize carTypeModel=_carTypeModel;
- (void).cxx_destruct;
- (void)setEstimateDescribe:(id)arg1;
- (void)loadCarData;
- (id)setFeeDetail:(id)arg1 serviceTypeDesc:(id)arg2 detail:(id)arg3 price:(id)arg4 carTypeModel:(id)arg5 specialColor:(_Bool)arg6 specialFontSize:(_Bool)arg7;
- (void)addData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)matchTableHeightFromCarTypes;
- (void)chargeStandardAction:(id)arg1;
- (void)backAction:(id)arg1;
- (void)dismiss;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

