//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class NSLayoutConstraint, NSString, UIButton, UIImage, UILabel, UITableView, UIView;

@interface OrederSelectPayTypeViewController : SuperViewController <UIGestureRecognizerDelegate>
{
    UIImage *checkImage;
    UIImage *uncheckImage;
    int payWay;
    _Bool _isOpenCreditPay;
    _Bool _isOpenUnionpay;
    _Bool _isOpenApplePay;
    _Bool _isOpenWechatPay;
    _Bool _isOpenAliPay;
    _Bool _isXiaoFei;
    UIView *_bgView;
    UIView *_bg2View;
    UIButton *_cancelButton;
    UITableView *_tableView;
    NSLayoutConstraint *_bg2ViewHeightConstraint;
    id <OrderSelectPayTypeDelegate> _delegate;
    UILabel *_needPayLab;
    double _needPay;
}

@property(nonatomic) _Bool isXiaoFei; // @synthesize isXiaoFei=_isXiaoFei;
@property(nonatomic) double needPay; // @synthesize needPay=_needPay;
@property(nonatomic) __weak UILabel *needPayLab; // @synthesize needPayLab=_needPayLab;
@property(nonatomic) id <OrderSelectPayTypeDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSLayoutConstraint *bg2ViewHeightConstraint; // @synthesize bg2ViewHeightConstraint=_bg2ViewHeightConstraint;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak UIView *bg2View; // @synthesize bg2View=_bg2View;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
- (void).cxx_destruct;
- (void)goPayAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)showAnimations;
- (void)hideAnimations;
- (void)hide:(id)arg1;
- (void)show;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)setDefaultPayType;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

