//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UICollectionView, UILabel, UITextField, UIView;

@interface PackageAmountCell : UITableViewCell
{
    UICollectionView *_packageCollectionView;
    UILabel *_rechargeHintsLabel;
    UITextField *_inviteCodeField;
    UIView *_inviteCodeFdBg;
    UITextField *_packageRechargeField;
    UILabel *_symbolLabel;
    UIView *_packageRechargeFdBg;
    NSLayoutConstraint *_packageRechargeFdBgWidthConstraint;
    NSLayoutConstraint *_packageCollectionViewHeightConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *packageCollectionViewHeightConstraint; // @synthesize packageCollectionViewHeightConstraint=_packageCollectionViewHeightConstraint;
@property(nonatomic) __weak NSLayoutConstraint *packageRechargeFdBgWidthConstraint; // @synthesize packageRechargeFdBgWidthConstraint=_packageRechargeFdBgWidthConstraint;
@property(nonatomic) __weak UIView *packageRechargeFdBg; // @synthesize packageRechargeFdBg=_packageRechargeFdBg;
@property(nonatomic) __weak UILabel *symbolLabel; // @synthesize symbolLabel=_symbolLabel;
@property(nonatomic) __weak UITextField *packageRechargeField; // @synthesize packageRechargeField=_packageRechargeField;
@property(nonatomic) __weak UIView *inviteCodeFdBg; // @synthesize inviteCodeFdBg=_inviteCodeFdBg;
@property(nonatomic) __weak UITextField *inviteCodeField; // @synthesize inviteCodeField=_inviteCodeField;
@property(nonatomic) __weak UILabel *rechargeHintsLabel; // @synthesize rechargeHintsLabel=_rechargeHintsLabel;
@property(nonatomic) __weak UICollectionView *packageCollectionView; // @synthesize packageCollectionView=_packageCollectionView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

