//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PickerTitle : NSObject
{
    _Bool _isStrikeOut;
    NSString *_title;
}

+ (id)pickerTitle:(id)arg1 isStrikeOut:(_Bool)arg2;
@property(nonatomic) _Bool isStrikeOut; // @synthesize isStrikeOut=_isStrikeOut;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

