//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class NSDate, NSString, UIDatePicker, UIToolbar;

@interface PMDateViewController : UIViewController
{
    NSString *_dateFormatter;
    long long _datePickerMode;
    NSDate *_minDate;
    NSDate *_maxDate;
    NSString *_showTitle;
    CDUnknownBlockType _dateSelectedBlock;
    UIDatePicker *_datePicker;
    UIToolbar *_toolbar;
}

@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(copy, nonatomic) CDUnknownBlockType dateSelectedBlock; // @synthesize dateSelectedBlock=_dateSelectedBlock;
@property(retain, nonatomic) NSString *showTitle; // @synthesize showTitle=_showTitle;
@property(retain, nonatomic) NSDate *maxDate; // @synthesize maxDate=_maxDate;
@property(retain, nonatomic) NSDate *minDate; // @synthesize minDate=_minDate;
@property(nonatomic) long long datePickerMode; // @synthesize datePickerMode=_datePickerMode;
@property(retain, nonatomic) NSString *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
- (void).cxx_destruct;
- (void)doneAction:(id)arg1;
- (void)cancleAction:(id)arg1;
- (void)toolView:(id)arg1 didPressAtIndex:(long long)arg2;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

