//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIPickerViewDelegate.h"

@class NSArray, NSMutableArray, NSString, UIPickerView, UIToolbar;

@interface PMPickerViewController : UIViewController <UIPickerViewDelegate>
{
    long long selectRow;
    _Bool isLoading;
    _Bool _autoReset;
    NSArray *_objects;
    NSString *_showTitle;
    NSArray *_selectedRows;
    long long _currentRow;
    long long _numberOfComponents;
    NSString *_groupKey;
    NSString *_dataKey;
    CDUnknownBlockType _pickerSelectedBlock;
    CDUnknownBlockType _pickerViewWidthForComponentBlock;
    CDUnknownBlockType _pickerViewEndedScrollBlock;
    UIPickerView *_pickerView;
    UIToolbar *_toolbar;
    NSMutableArray *_selectedComponents;
}

@property(retain, nonatomic) NSMutableArray *selectedComponents; // @synthesize selectedComponents=_selectedComponents;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(copy, nonatomic) CDUnknownBlockType pickerViewEndedScrollBlock; // @synthesize pickerViewEndedScrollBlock=_pickerViewEndedScrollBlock;
@property(copy, nonatomic) CDUnknownBlockType pickerViewWidthForComponentBlock; // @synthesize pickerViewWidthForComponentBlock=_pickerViewWidthForComponentBlock;
@property(copy, nonatomic) CDUnknownBlockType pickerSelectedBlock; // @synthesize pickerSelectedBlock=_pickerSelectedBlock;
@property(nonatomic) _Bool autoReset; // @synthesize autoReset=_autoReset;
@property(copy, nonatomic) NSString *dataKey; // @synthesize dataKey=_dataKey;
@property(copy, nonatomic) NSString *groupKey; // @synthesize groupKey=_groupKey;
@property(nonatomic) long long numberOfComponents; // @synthesize numberOfComponents=_numberOfComponents;
@property(nonatomic) long long currentRow; // @synthesize currentRow=_currentRow;
@property(retain, nonatomic) NSArray *selectedRows; // @synthesize selectedRows=_selectedRows;
@property(retain, nonatomic) NSString *showTitle; // @synthesize showTitle=_showTitle;
@property(retain, nonatomic) NSArray *objects; // @synthesize objects=_objects;
- (void).cxx_destruct;
- (void)doneAction:(id)arg1;
- (void)cancleAction:(id)arg1;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (void)toolView:(id)arg1 didPressAtIndex:(long long)arg2;
- (void)selectRows:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

