//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBFileHelper : NSObject
{
}

+ (id)contentsOfDirectoryAtPath:(id)arg1;
+ (id)subpathsOfDirectoryAtPath:(id)arg1;
+ (id)subpathsAtPath:(id)arg1;
+ (_Bool)copyItemAtPath:(id)arg1 toPath:(id)arg2;
+ (_Bool)moveItemAtPath:(id)arg1 toPath:(id)arg2;
+ (void)deleteDocumentsFile:(id)arg1 inDirectory:(id)arg2;
+ (_Bool)deleteFileAtPath:(id)arg1;
+ (_Bool)writeToFileDictionary:(id)arg1 path:(id)arg2;
+ (_Bool)writeToFileArray:(id)arg1 path:(id)arg2;
+ (_Bool)createFileAtPath:(id)arg1 contents:(id)arg2;
+ (id)contentsAtPath:(id)arg1;
+ (id)createDirectoryAtPath:(id)arg1 searchPathDirectories:(unsigned long long)arg2;
+ (id)createCachesDirectoryAtPath:(id)arg1;
+ (id)createDocumentDirectoryAtPath:(id)arg1;
+ (_Bool)fileExistsAtPath:(id)arg1;
+ (id)pathForCaches:(id)arg1 inDirectory:(id)arg2;
+ (id)pathForCaches:(id)arg1;
+ (id)pathForDocuments:(id)arg1 inDirectory:(id)arg2;
+ (id)pathForDocuments:(id)arg1;
+ (id)pathForResource:(id)arg1 inDirectory:(id)arg2;
+ (id)pathForResource:(id)arg1;
+ (id)temporaryDirectory;
+ (id)homeDirectory;
+ (id)libraryDirectory;
+ (id)cachesDirectory;
+ (id)documentDirectory;
+ (id)fileManager;
+ (id)searchPathForDirectories:(unsigned long long)arg1;

@end

