//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MoreTableViewController.h"

@class UIButton, UITableView, UIView;

@interface SettingTableViewController : MoreTableViewController
{
    UIView *_logoutBtnBGView;
    UIButton *_logoutBtn;
    UITableView *_tableView;
}

+ (void)logoutActionWithoutNoti;
+ (void)logoutAction;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)logoutButtonAction:(id)arg1;
- (void)quitEnterprise;
- (void)goCommentAddress;
- (void)goCleanCache;
- (void)goFeekBack;
- (void)goAboutViewController;
- (void)updateLogoutButtonLocation;
- (void)updateLogoutButtonStatus;
- (void)initCellDatas;
- (void)setupLogOutButton;
- (void)backBarButtonAction:(id)arg1;
- (void)setupSettingButton;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;

@end

