//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

#import "UIWebViewDelegate.h"

@class NSString, UIWebView, WebViewJavascriptBridge;

@interface ShareListViewController : SuperViewController <UIWebViewDelegate>
{
    _Bool _isShareStatus;
    UIWebView *_webView;
    WebViewJavascriptBridge *_webViewJavascriptBridge;
}

@property(retain, nonatomic) WebViewJavascriptBridge *webViewJavascriptBridge; // @synthesize webViewJavascriptBridge=_webViewJavascriptBridge;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) _Bool isShareStatus; // @synthesize isShareStatus=_isShareStatus;
- (void).cxx_destruct;
- (void)goInvitation;
- (void)addWebViewJavascriptBridge;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

