//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIView;

@interface SuperViewController : UIViewController
{
    UIView *_noneView;
    UIView *_netWorkErrorView;
}

@property(retain, nonatomic) UIView *netWorkErrorView; // @synthesize netWorkErrorView=_netWorkErrorView;
@property(retain, nonatomic) UIView *noneView; // @synthesize noneView=_noneView;
- (void).cxx_destruct;
- (void)setNavgationBarLineHidden:(_Bool)arg1;
- (void)setTitle:(id)arg1;
- (void)setStatusBarPositionAtX:(int)arg1;
- (void)showStatusBar;
- (void)hiddenStatusBar;
- (void)removeNetWorkErrorView;
- (void)showNetWorkErrorViewWithReloadSEL:(SEL)arg1;
- (void)removeNoneView;
- (id)createNoneViewWithImage:(id)arg1 title:(id)arg2 buttonTitle:(id)arg3 buttonSEL:(SEL)arg4 isGlobal:(_Bool)arg5;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

