//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Tool : NSObject
{
}

+ (void)checkDebuger;
+ (void)drawPath:(id)arg1;
+ (id)thumbnailWithImageWithoutScale:(id)arg1 size:(struct CGSize)arg2;
+ (id)readResouceFile:(id)arg1 andExt:(id)arg2;
+ (id)parseColor:(id)arg1;

@end

