//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface TQStarRatingView : UIView
{
    int _numberOfStar;
    id <StarRatingViewDelegate> _delegate;
    UIView *_starBackgroundView;
    UIView *_starForegroundView;
}

@property(retain, nonatomic) UIView *starForegroundView; // @synthesize starForegroundView=_starForegroundView;
@property(retain, nonatomic) UIView *starBackgroundView; // @synthesize starBackgroundView=_starBackgroundView;
@property(nonatomic) __weak id <StarRatingViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) int numberOfStar; // @synthesize numberOfStar=_numberOfStar;
- (void).cxx_destruct;
- (void)changeStarForegroundViewWithPoint:(struct CGPoint)arg1;
- (id)buidlStarViewWithImageName:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)setScore:(float)arg1 withAnimation:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setScore:(float)arg1 withAnimation:(_Bool)arg2;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1 numberOfStar:(int)arg2;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

