//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@interface UIControl (BUIControl)
+ (unsigned long long)eventWithName:(id)arg1;
+ (id)eventName:(unsigned long long)arg1;
- (void)callActionBlock:(unsigned long long)arg1;
- (void)UIControlEventAllEvents;
- (void)UIControlEventSystemReserved;
- (void)UIControlEventApplicationReserved;
- (void)UIControlEventAllEditingEvents;
- (void)UIControlEventAllTouchEvents;
- (void)UIControlEventEditingDidEndOnExit;
- (void)UIControlEventEditingDidEnd;
- (void)UIControlEventEditingChanged;
- (void)UIControlEventEditingDidBegin;
- (void)UIControlEventValueChanged;
- (void)UIControlEventTouchCancel;
- (void)UIControlEventTouchUpOutside;
- (void)UIControlEventTouchUpInside;
- (void)UIControlEventTouchDragExit;
- (void)UIControlEventTouchDragEnter;
- (void)UIControlEventTouchDragOutside;
- (void)UIControlEventTouchDragInside;
- (void)UIControlEventTouchDownRepeat;
- (void)UIControlEventTouchDown;
- (void)handleControlEvent:(unsigned long long)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)removeHandlerForEvent:(unsigned long long)arg1;
@end

