//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface UILabel (SimpleFlickerNumber)
- (long long)countOfDivideTen:(long long)arg1 count:(long long)arg2;
- (void)flicker:(id)arg1;
- (void)flickerToNumber:(id)arg1 duration:(double)arg2 frontString:(id)arg3 backString:(id)arg4 block:(CDUnknownBlockType)arg5;
- (CDUnknownBlockType)block;
- (void)setBlock:(CDUnknownBlockType)arg1;
- (id)currentTimer;
- (void)setCurrentTimer:(id)arg1;
- (id)beginNumber;
- (void)setBeginNumber:(id)arg1;
- (id)flickerNumber;
- (void)setFlickerNumber:(id)arg1;
- (id)backString;
- (void)setBackString:(id)arg1;
- (id)frontString;
- (void)setFrontString:(id)arg1;
@end

