//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextField.h"

@class AKNumericFormatter;

@interface UITextField (AKNumericFormatter)
- (void)alertDeleteBackwards;
- (void)formatCurrentText;
- (void)handleTextChanged:(id)arg1;
- (void)deleteBackwardSwizzle;
- (_Bool)isFormatting;
- (void)setIsFormatting:(_Bool)arg1;
- (_Bool)handleDeleteBackwards;
- (void)setHandleDeleteBackwards:(_Bool)arg1;
@property(retain, nonatomic) AKNumericFormatter *numericFormatter;
@end

