//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (Layer)
- (void)setBorderColor:(id)arg1;
- (void)setBorderWidth:(double)arg1 borderColor:(id)arg2;
- (void)setCircular;
- (void)setFillet:(double)arg1;
@end

