//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SuperViewController.h"

@class UIButton, UISwitch, UIView;

@interface UnbindPaysViewController : SuperViewController
{
    unsigned long long _bindPayType;
    UIView *_bgView;
    UIButton *_descriptBtn;
    UISwitch *_unBindSwitch;
}

@property(nonatomic) __weak UISwitch *unBindSwitch; // @synthesize unBindSwitch=_unBindSwitch;
@property(nonatomic) __weak UIButton *descriptBtn; // @synthesize descriptBtn=_descriptBtn;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) unsigned long long bindPayType; // @synthesize bindPayType=_bindPayType;
- (void).cxx_destruct;
- (void)unBind;
- (void)descriptBtnClicked:(id)arg1;
- (void)unBindSwichClicked:(id)arg1;
- (void)backBarButtonAction:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

