//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIButton, UILabel;

@interface UserPointCell : UITableViewCell
{
    double lineWithd;
    long long needPoint;
    NSString *nextLevel;
    long long nLevel;
    double fLevel;
    long long _userPoint;
    UILabel *_updateNeedPointLable;
    UIButton *_paopaoButton;
}

@property(retain, nonatomic) UIButton *paopaoButton; // @synthesize paopaoButton=_paopaoButton;
@property(nonatomic) __weak UILabel *updateNeedPointLable; // @synthesize updateNeedPointLable=_updateNeedPointLable;
@property(nonatomic) long long userPoint; // @synthesize userPoint=_userPoint;
- (void).cxx_destruct;
- (void)drawLevelTextWithCenter:(struct CGPoint)arg1 level:(long long)arg2;
- (void)drawLineWithOrigin:(struct CGPoint)arg1 end:(struct CGPoint)arg2 color:(id)arg3;
- (void)drawCircleWithCenter:(struct CGPoint)arg1 color:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)updatePaoPaoBtnWithScore:(long long)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

