//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSString, NSTimer;

@interface WSCSVWriter : NSObject <CLLocationManagerDelegate>
{
    _Bool isFirst;
    NSTimer *locactionTimer;
    CDUnknownBlockType _block;
    NSString *_savePath;
    NSString *_saveCode;
    NSString *_saveNum;
    unsigned long long _encode;
    CLLocationManager *_locationManager;
    long long _errorCount;
}

+ (double)transformLonWithX:(double)arg1 withY:(double)arg2;
+ (double)transformLatWithX:(double)arg1 withY:(double)arg2;
+ (struct CLLocationCoordinate2D)transformFromWGSToGCJ:(struct CLLocationCoordinate2D)arg1;
+ (_Bool)isLocationOutOfChina:(struct CLLocationCoordinate2D)arg1;
+ (id)shareInstance;
@property(nonatomic) long long errorCount; // @synthesize errorCount=_errorCount;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(nonatomic) unsigned long long encode; // @synthesize encode=_encode;
@property(copy, nonatomic) NSString *saveNum; // @synthesize saveNum=_saveNum;
@property(copy, nonatomic) NSString *saveCode; // @synthesize saveCode=_saveCode;
@property(copy, nonatomic) NSString *savePath; // @synthesize savePath=_savePath;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
- (void).cxx_destruct;
- (struct CLLocationCoordinate2D)transformFromBaiduToGCJ:(struct CLLocationCoordinate2D)arg1;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)currentLocation:(CDUnknownBlockType)arg1;
- (void)stopLocationTimer;
- (void)startLocationTimer:(id)arg1 OrderNum:(id)arg2;
- (double)transformLon:(double)arg1 bdLon:(double)arg2;
- (double)transformLat:(double)arg1 bdLon:(double)arg2;
- (_Bool)outOfChina:(double)arg1 bdLon:(double)arg2;
- (struct CLLocationCoordinate2D)gcj02Encrypt:(double)arg1 bdLon:(double)arg2;
- (struct CLLocationCoordinate2D)wgs84ToGcj02:(struct CLLocationCoordinate2D)arg1;
- (void)updateLocation;
- (void)cleanUnpayInfo;
- (void)cleanError;
- (void)uploadCsvArray;
- (void)uploadAllFile;
- (void)uploadfile;
- (void)renamefile;
- (void)initWithPath:(id)arg1 andNum:(id)arg2;
- (void)writeData:(id)arg1;
- (void)writeArray:(id)arg1;
- (void)writeDict:(id)arg1 forFirst:(_Bool)arg2;
- (id)fullPath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

