//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIView;

@interface YearMonthViewController : UIViewController
{
    UIView *currentHideView;
    CDUnknownBlockType _dateSelectedBlock;
    UIView *_currentDateView;
}

@property(retain, nonatomic) UIView *currentDateView; // @synthesize currentDateView=_currentDateView;
@property(copy, nonatomic) CDUnknownBlockType dateSelectedBlock; // @synthesize dateSelectedBlock=_dateSelectedBlock;
- (void).cxx_destruct;
- (void)hideView;
- (void)removeHideView:(id)arg1;
- (void)handleTapRecognizer:(id)arg1;
- (void)yearMonthViewDidCancel;
- (void)yearMonthView:(id)arg1 didSelectedYear:(id)arg2 month:(id)arg3;
- (void)showInView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

