server {
  listen 443 ssl;
  listen [::]:443 ssl;

  charset utf-8;

  ssl_certificate ssl/fullchain.cer;
  ssl_certificate_key ssl/store.scfhao.cn.key;

  ssl_protocols TLSv1.2 TLSv1.3; # 支持的SSL/TLS协议版本
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256;
  ssl_prefer_server_ciphers on;
  ssl_session_cache    shared:SSL:1m;
  ssl_session_timeout  5m;

  root /var/www/html;
  index index.php;
  server_name store.scfhao.cn; # 替换为你的域名或localhost
  server_tokens off;
  
  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass wordpress:9000; # 指向PHP-FPM服务
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SCRIPT_NAME $fastcgi_script_name;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name store.scfhao.cn; # 替换为你的域名或localhost
  return 301 https://$host$request_uri;
}
